bytedance/UI-TARS-desktop

packages/action-parser/src/index.test.ts
packages/action-parser/src/index.ts
src/main/agent/execute.test.ts
src/main/agent/execute.ts
src/renderer/src/components/RunMessages/index.tsx

Currently, if I request to open a specific URL and append additional actions, e.g.
```
Open doubao.com and type "Tell me the exchange rate of the US dollar";
```
I may encounter an unexpected trailing newline (`\n`).
This will cause the page you visit to display a 404:
Since this problem is very likely to recur, a workaround is currently being implemented: This MR removes the trailing line break in the Action Parser, waiting for further discussion by the team.

fix(execute): type workaround for unexpected newline in content value

---

packages/action-parser/src/index.test.ts
packages/action-parser/src/index.ts

this minor change fixes the parsing error when vlm responses with actionInputs enclosed in [] 
for eg.
> "Thought: I need to open Chrome. I will click on the Chrome icon in the dock to launch it.\n" +
"\n" +
"Action: click(start_box='[10, 850, 50, 890]')"
this was due to incorrect regex used for parsing
this for me partially Resolves issues mentioned in #11   as click action (and i guess other action which requires coordinates) is working correctly

fix: null values while parsing action inputs

---

src/main/store/types.ts
src/main/window/index.ts
src/renderer/src/components/ChatInput/index.tsx
src/renderer/src/pages/settings/index.tsx
src/renderer/src/utils/share.ts

Introducing a configurable **Report Storage Base URL** to handle report sharing via a custom HTTP endpoint.
Close: #58
| Setting | Success | Fail |
| --- | --- | --- |
| <img width="484" alt="image" src="https://github.com/user-attachments/assets/737bfd01-2906-46d9-982f-21c62bd384e4" />| <img width="454" alt="image" src="https://github.com/user-attachments/assets/9f493648-0376-4324-9156-24a9a95b6c0a" /> | <img width="454" alt="image" src="https://github.com/user-attachments/assets/e3661817-89c1-4c99-b66e-444853b072ed" /> |
`POST /api/share`
Uploads a file and returns its accessible URL
**Headers**  
`Content-Type: multipart/form-data`
**Parameters**  
`file` (binary, required) - File to upload
**Success Response**  
`200 OK`
```json
{
"url": "string"
}
```
- Add `Report Storage Base URL` …

feat(renderer): report storage base url setting (close: #58)

---

.github/workflows/test.yml
.prettierrc.mjs
package.json
packages/shared/src/types/index.ts
packages/visualizer/src/component/detail-panel.tsx
packages/visualizer/src/component/player.tsx
pnpm-lock.yaml
src/main/agent/index.ts
src/main/main.ts
src/main/store/ScreenMarker.ts
src/main/store/create.ts
src/main/store/runAgent.ts
src/main/store/types.ts
src/renderer/src/components/ChatInput/index.tsx
src/renderer/src/components/RunMessages/index.tsx
src/renderer/src/components/ThoughtChain/index.tsx
src/renderer/src/hooks/useRunAgent.ts
src/renderer/src/pages/home/index.tsx
src/renderer/src/utils/message.ts

https://github.com/user-attachments/assets/216e145c-f3a0-4947-ad68-322f12f7fdf1
https://github.com/user-attachments/assets/cce6f314-31d0-444e-b3f1-3c9ea12f8a5d

release: v0.0.3

---

.github/workflows/test.yml
.vscode/settings.json
package.json
pnpm-lock.yaml
src/main/utils/systemPermissions.test.ts
src/main/utils/systemPermissions.ts
src/renderer/src/hooks/useDispatch.ts
src/renderer/src/hooks/usePermissions.ts
src/renderer/src/hooks/useRunAgent.ts

The original bug was that the permission updates were not timely enough. Since after `dispatch` execution, the obtained `permissions` were the old state.
Focusing the screen to request the latest permissions was done through `swr` when not all permissions were acquired.
| Before  | After |
| :---:  | :---: |
| ![image](https://github.com/user-attachments/assets/ed7834b6-f4c1-4a83-8014-571b3cb0b3c0) |   <video src="https://github.com/user-attachments/assets/ff0bc489-413a-4ba9-98d8-7d6e5abb8d2b" height="300" />     |

fix(permission): macOS permissions updates are not real-time

---

src/main/store/setting.ts
src/main/store/types.ts
tsconfig.base.json

Currently `@electron-toolkit/tsconfig`<sup>[1]</sup> sets `moduleResolution` to `node`, and [electron-store](https://github.com/sindresorhus/electron-store/blob/main/package.json)<sup>[2]</sup> is implemented based on [conf](https://github.com/sindresorhus/conf/blob/main/package.json)<sup>[3]</sup>. Currently `conf` exports types based on `exports.types`:
```json
"exports": {
"types": "./dist/source/index.d.ts",
"default": "./dist/source/index.js"
},
```
The current setup (`"moduleResolution": "node"` ) cannot properly handle the `types` field in `exports`<sup>[4]</sup>, so that `tsc` to be unable to recognize these types.
This PR enables `moduleResolution: bundler`<sup>[5]</sup> to remove all `@ts-ignore`s.
[1] https://github.com/alex8088/electron-toolkit/blob/master/packages/tsconfig/tsc …

refactor: enable `moduleResolution: bundler` to avoid `@ts-ignore`

---

src/main/shared/setOfMarks.test.ts
src/main/shared/setOfMarks.ts
src/main/store/runAgent.ts
src/main/utils/image.ts
src/main/window/ScreenMarker.ts
src/main/window/index.ts
src/renderer/index.html
src/renderer/src/components/ChatInput/index.tsx
src/renderer/src/components/RunMessages/index.tsx
src/renderer/src/hooks/useScreenRecord.ts
src/renderer/src/hooks/useStore.ts
tsconfig.web.json

Combine the three locations of `arking position in image`, `arking position on screen`, and `arking position during screen recording` into a single method call `setOfMarksOverlays`.
- Prompt: `问 ChatGPT 今天星期几？`
https://github.com/user-attachments/assets/faf1e79e-82e9-4fd2-84fc-b0aa403b5009

refactor(SoM): setOfMarks Overlays unify into `setOfMarksOverlays` function

---

src/main/agent/llm/ui-tars.ts
src/main/main.ts
src/main/services/settings.ts
src/main/services/utio.ts
src/main/store/create.ts
src/main/store/runAgent.ts
src/main/store/setting.ts
src/main/store/types.ts
src/main/store/validate.ts
src/preload/index.ts
src/renderer/src/components/ChatInput/index.tsx
src/renderer/src/hooks/useRunAgent.ts
src/renderer/src/hooks/useSetting.ts
src/renderer/src/pages/settings/PresetImport.tsx
src/renderer/src/pages/settings/index.tsx

This pull request refined the setting page ui and introduce setting `Preset`, A preset is a collection of settings, UI TARS Desktop supports setting presets via files or URLs.
Close:#57
- **Refine setting store**: Due to the instability and difficulty of `zutron`, this PR removed `SettingStore`(`electron-store`) from `store` (`zutron` and `zustand`), we'll design a new state management solution later.
- **Scroll bar in setting**: To avoid the setting window too long, we introduced a inner scroll bar similar to macOS. 
| Function | Snapshot |
| --- | ---|
| Open Setting |<img width="320" alt="image" src="https://github.com/user-attachments/assets/1d2ae27c-9b2e-4896-96a6-04832f850907" /> |
| Import Success | <img width="320" alt="image" …

feat: setting preset (close: #57)

---

README.md
forge.config.ts

```bash
brew install --cask ui-tars
```
Because the UI-TARS Github repository is less than 30 days old, we need to use `brew tap` to specify the installation for now. After the merge(https://github.com/Homebrew/homebrew-cask/pull/201519), the `brew tap` may not be necessary.

docs: brew install

---

packages/utio/src/index.ts
src/renderer/src/components/ChatInput/index.tsx

This pull request adds strong reminders from the user's perspective to the [shareReport](https://github.com/bytedance/UI-TARS-desktop/blob/main/docs/setting.md#share-report) and [report upload behaviors](https://github.com/bytedance/UI-TARS-desktop/blob/main/docs/setting.md#report-storage-base-url) in UTIO to ensure user privacy.

feat(renderer): add a strong prompt when the report needs to be uploaded

---

src/main/agent/execute.ts
src/main/window/ScreenMarker.ts

1. fix(main): resolve focus missing for typing window on Windows
- 先设置overlay window 为 non-focusable之后再设置always on top，否则overlay window在设置always on top的瞬间会抢占focus状态，导致待输入窗口丢失焦点
2. fix(main): improve hotkey handling reliability on Windows
- 优化特殊键值，增加cmd（macOS）/ win（windows）键的匹配
- 普通键值在nut-js中应使用大写字母匹配输入键值

fix: typing and key input fail

---

src/main/agent/device.test.ts
src/main/agent/device.ts
src/main/main.ts

ensure screen capture uses primary display source
Close #116

fix: ensure screen capture uses primary display source (close: #116)

---

packages/visualizer/README.md
packages/visualizer/html/report.html
packages/visualizer/modern.config.ts
packages/visualizer/package.json
packages/visualizer/pnpm-lock.yaml
packages/visualizer/scripts/build-html.ts

reduce html report size:
- remove `midscene_report_tpl` element (the content within this element is not utilized by the TARS project, **12.25 MiB -> 0**)
- minify css & external js code (**6.36 MiB -> 750 KiB**)
After optimization, the size of a local HTML report file was reduced **from 21.17 MiB to 3.3 MiB**, achieving an **85%** reduction.
close: #118

feat(visualizer): reduce html report size (close: #118)

---

packages/sdk/src/Model.ts
packages/sdk/src/core.ts

This pull request includes important updates to the `packages/sdk` module, focusing on improving the `UITarsModel` class and enhancing type exports. The most significant changes involve modifying the `factor` parameter usage and adding a new type export for better type management.
Key changes include:
* [`packages/sdk/src/Model.ts`](diffhunk://#diff-fe790ac753834c2cb21d4cfb5f46dce6b245c524897bc857ff6ad1b1608f7277L135-R135): Updated the `factor` parameter in the `actionParser` call to use `this.factors` instead of the constant `FACTORS`.
* [`packages/sdk/src/core.ts`](diffhunk://#diff-427668d1f3dc223b030d44a6a30555528c718c1912eef8958c6084ce5ade5746R14): Added a new type export for `UITarsModelConfig` to improve type management and usage across the module.

fix(sdk): should respect model's factors config

---

packages/action-parser/src/actionParser.ts
packages/action-parser/test/actionParser.test.ts

UI-TARS returns clear coordinates (`[x, y]`), but for models such as Claude, it returns a Box (`[x1, y1, x2, y2]`). Currently, UI-TARS Desktop has some problems with Box Action Parse.
Here is the differences between the before and after logic for coordinate normalization, and why the fix resolves the issue.
```ts
┌─────────────────────────────────────────────────────────────────────────┐
│                     COORDINATE NORMALIZATION ISSUE                      │
└─────────────────────────────────────────────────────────────────────────┘
┌───────────────────────────┐            ┌───────────────────────────┐
│         BEFORE            │            │          AFTER            │
└───────────────────────────┘            └───────────────────────────┘
Input Box: [348, 333, 928, 365] …
```

fix(action-parser): box coordinates normalization

---

package.json
src/main/agent/operator.ts

Close https://github.com/bytedance/UI-TARS-desktop/issues/165

fix(screenshot): screenshot thumbnail undefined

---

.changeset/config.json
.changeset/pre.json
.changeset/stale-icons-whisper.md
apps/ui-tars/package.json
packages/ui-tars/action-parser/CHANGELOG.md
packages/ui-tars/action-parser/package.json
packages/ui-tars/cli/CHANGELOG.md
packages/ui-tars/cli/package.json
packages/ui-tars/electron-ipc/CHANGELOG.md
packages/ui-tars/electron-ipc/package.json
packages/ui-tars/operators/browserbase/CHANGELOG.md
packages/ui-tars/operators/browserbase/package.json
packages/ui-tars/operators/nut-js/CHANGELOG.md
packages/ui-tars/operators/nut-js/package.json
packages/ui-tars/sdk/CHANGELOG.md
packages/ui-tars/sdk/package.json
packages/ui-tars/shared/CHANGELOG.md
packages/ui-tars/shared/package.json
packages/ui-tars/utio/CHANGELOG.md
packages/ui-tars/utio/package.json

- feat: support operator-browserbase (#132)
- fix(app): electron build issue & tweak sdk snapshot quality (#188)
- fix(operator): macos cannot type (#126) 
- fix(app): native module deps build and reduce 28% bundle size (#181)
- refactor(app): migrate to apps/desktop monorepo (#177)
- refactor(sdk): screenshot only return base64 and scaleFactor (#171)
- chore(sdk): allow custom factors via parseBoxToScreenCoords api (#162) 
Full Changelog: https://github.com/bytedance/UI-TARS-desktop/compare/v0.0.6...v0.0.7
<video src="https://github.com/user-attachments/assets/354c3b8b-681f-4ad0-9ab9-365dbde894af" height="100"

release: v0.0.7

---

apps/agent-tars/package.json
apps/agent-tars/src/main/ipcRoutes/action.ts
apps/agent-tars/src/renderer/index.html
apps/agent-tars/src/renderer/src/agent/AgentFlow.ts
apps/agent-tars/src/renderer/src/agent/mockEvents.ts
apps/agent-tars/src/renderer/src/components/ChatUI/MenuHeader.tsx
apps/agent-tars/src/renderer/src/components/ChatUI/Replay.tsx
apps/agent-tars/src/renderer/src/components/LeftSidebar/TopBar.tsx
apps/agent-tars/vite.config.ts

- **fix: ui bugfix**
- **fix: replay auto replay**

fix: replay ui bugs

---

apps/agent-tars/README.md
apps/agent-tars/package.json
apps/agent-tars/src/main/ipcRoutes/action.ts
apps/agent-tars/src/renderer/mock/ipc.ts
packages/agent-infra/mcp-client/src/index.ts
pnpm-lock.yaml

- **fix: share error**
- **fix(agent-tars): share serialize error with html artifacts**

fix(agent-tars): share serialize error with html artifacts

---

apps/agent-tars/package.json
apps/agent-tars/src/main/customTools/search.ts
apps/agent-tars/src/main/index.ts
apps/agent-tars/src/main/ipcRoutes/action.ts
apps/agent-tars/src/main/ipcRoutes/llm.ts
apps/agent-tars/src/main/store/setting.ts
apps/agent-tars/src/renderer/src/components/LeftSidebar/Settings/SearchSettingsTab.tsx
apps/agent-tars/src/renderer/src/components/LeftSidebar/Settings/searchUtils.tsx
apps/agent-tars/src/renderer/src/components/LeftSidebar/Settings/useAppSettings.ts
apps/ui-tars/src/renderer/src/pages/settings/index.tsx
packages/agent-infra/browser/src/base-browser.ts
packages/agent-infra/browser/src/local-browser.ts
packages/agent-infra/browser/src/types.ts
packages/agent-infra/search/browser-search/examples/bing-search.ts
packages/agent-infra/search/browser-search/src/browser-search.ts
packages/agent-infra/search/browser-search/src/engines/get-search-engine.ts
packages/agent-infra/search/browser-search/src/engines/index.ts
packages/agent-infra/search/browser-search/src/types.ts
packages/agent-infra/shared/src/agent-tars-types/search.ts

- **feat(tool): browser search bing engine**
- **feat(agent-tars): app updater**

feat(tool): browser search bing engine & app updater

---

apps/agent-tars/src/renderer/src/agent/Greeter.ts

feat(agent-tars): make greeter response shorter

---

apps/agent-tars/src/renderer/src/components/LeftSidebar/index.module.scss

feat(agent-tars): refactor setting icon default display position

---

apps/agent-tars/package.json
apps/agent-tars/src/main/customTools/search.ts
apps/agent-tars/src/main/index.ts
apps/agent-tars/src/main/ipcRoutes/action.ts
apps/agent-tars/src/main/ipcRoutes/agent.ts
apps/agent-tars/src/main/ipcRoutes/filesystem.ts
apps/agent-tars/src/main/ipcRoutes/llm.ts
apps/agent-tars/src/main/ipcRoutes/search.ts
apps/agent-tars/src/main/llmProvider/ProviderFactory.ts
apps/agent-tars/src/main/llmProvider/index.ts
apps/agent-tars/src/main/menu.ts
apps/agent-tars/src/main/store/setting.ts
apps/agent-tars/src/main/utils/extractToolNames.ts
apps/agent-tars/src/main/utils/logger.ts
apps/agent-tars/src/main/utils/maskSensitiveData.ts
apps/agent-tars/src/main/utils/normalizeOmegaData.ts
apps/agent-tars/src/main/utils/systemPermissions.ts
pnpm-lock.yaml

This pull request integrates a logger utility to replace console statements across multiple modules, improving maintainability and debugging within the `agent-tars` application. Key changes include enhanced search functionality and sensitive data masking in logs. Dependency updates such as adding `@agent-infra/logger` are also included.
Additional minor changes comprise the application menu setup in the `createWindow` function and introducing a `maskSensitiveData` utility for secure logging.

feat(agent-tars): support "view logs" for trouble shooting

---

apps/agent-tars/src/main/ipcRoutes/llm.ts
apps/agent-tars/src/main/ipcRoutes/settings.ts
apps/agent-tars/src/main/llmProvider/ProviderFactory.ts
apps/agent-tars/src/main/llmProvider/index.ts
apps/agent-tars/src/main/llmProvider/providers/AnthropicProvider.ts
apps/agent-tars/src/main/llmProvider/providers/AzureOpenAIProvider.ts
apps/agent-tars/src/main/llmProvider/providers/GeminiProvider.ts
apps/agent-tars/src/main/llmProvider/providers/MistralProvider.ts
apps/agent-tars/src/main/llmProvider/providers/OpenAIProvider.ts
apps/agent-tars/src/main/store/setting.ts

This pull request improves logging and enhances data protection in the `apps/agent-tars` project. Key updates include added logging statements across various files (`llm.ts`, `settings.ts`, `ProviderFactory.ts`) to monitor system behavior, while masking sensitive data such as API credentials in logs.

feat: enhance log for llm providers and settings

---

apps/agent-tars/src/main/ipcRoutes/action.ts

In https://github.com/bytedance/UI-TARS-desktop/issues/345, we found an unclear log `[object Object]` that prevented us from troubleshooting the problem:
```
[ERROR] [actionRoute.executeTool] execute tool error browser_navigate [object Object]
```
After:
```
[ERROR] [actionRoute.executeTool] Failed to execute tool "${mcpTool.name}": ${errorMessage}`
```

refactor(agent-tars): too call log

---

apps/agent-tars/src/main/menu.ts

- Import 'app' module from electron
- Add new 'Quit' menu item with proper keyboard shortcut
- Implement app.quit() function to properly terminate the application
close: #353

fix(menu): add 'Quit' option with CmdOrCtrl+Q shortcut :bug:

---

apps/agent-tars/src/main/index.ts
apps/agent-tars/src/main/utils/updateApp.ts

This pull request includes changes to the `apps/agent-tars/src/main/index.ts` file to enhance the application's cleanup process when all windows are closed. The key changes involve importing a new module and adding a cleanup routine for MCP servers.
Enhancements to cleanup process:
* [`apps/agent-tars/src/main/index.ts`](diffhunk://#diff-6bd65e9a6bcd8dfad7e2ddf5a5d45609feae1ffc7570f62c1e83eaedc541b3c9R2): Imported `mapClientRef` from `@main/mcp/client` to enable MCP server management.
* [`apps/agent-tars/src/main/index.ts`](diffhunk://#diff-6bd65e9a6bcd8dfad7e2ddf5a5d45609feae1ffc7570f62c1e83eaedc541b3c9L136-R146): Modified the `app.on('window-all-closed', async () => {` event handler to include an asynchronous cleanup routine for MCP servers, logging any errors encountered during the …

fix(agent-tars): mcp servers cleanup when windows all closed

---

apps/agent-tars/src/main/customTools/search.ts
apps/agent-tars/src/main/ipcRoutes/search.ts
apps/agent-tars/src/renderer/src/components/LeftSidebar/Settings/SearchSettingsTab.tsx

After adding the search service, its availability can only be verified within the Agent workflow. If the search service is unavailable, many tasks may fail, leading to wasted tokens. This PR adds a validation feature when setting up the search service to detect availability issues in advance.
---

feat: add search servcie connection test

---

apps/agent-tars/src/renderer/src/agent/AgentFlow.ts
apps/agent-tars/src/renderer/src/agent/Aware.ts
apps/agent-tars/src/renderer/src/agent/Executor/index.ts

This commit corrects multiple spelling errors and improves code consistency across the agent-tars codebase:
- Fixed spelling: "stratch" → "scratch", "accroding" → "according", "bacause" → "because", "Replaning" → "Replanning"
- Renamed for consistency: "excuteTools" → "executeTools" (method name and calls)
- Updated variable name: "excutorTools" → "executorTools"
- Corrected wording in system prompts: "excutor agent/tools" → "executor agent/tools"
These changes improve code readability, system prompt accuracy, and maintain consistent naming conventions throughout the codebase.

fix(agent-tars): correct spelling errors and code consistency issues

---

apps/agent-tars/src/renderer/src/components/LeftSidebar/Settings/SettingsModal.tsx
apps/agent-tars/src/renderer/src/components/LeftSidebar/Settings/useAppSettings.ts

- Close: #421
Currently, when saving MCP settings, the **UI thread** will notify the **Main thread** to update the setting store through IPC (`ipcClient.addMcpServer` or `ipcClient.updateMcpServer`), the `SettingStore` in  **Main thread** will be updated, but the local `settings` state in  `useAppSettings` hook (**UI thread**) are not updated, this causes the state to be out of sync.
This pull request make all changes in the Setting Store to be notified from **Main thread** to the **UI thread**  to ensure the update of local state in WebView.

fix(agent-tars): setting state not sync (close: #421)

---

apps/agent-tars/src/renderer/package.json
apps/agent-tars/src/renderer/src/components/LeftSidebar/Settings/AddServerModal.tsx
apps/agent-tars/src/renderer/src/components/LeftSidebar/Settings/MCPServersSettingsTab.tsx
pnpm-lock.yaml

Close https://github.com/bytedance/UI-TARS-desktop/issues/435
Ref: https://github.com/heroui-inc/heroui/issues/2844
This pull request includes significant updates to the `AddServerModal` component and the removal of the deprecated `@nextui-org/form` package. The most important changes involve the migration to `react-hook-form` for form handling, and the addition of new form validation logic.
* [`apps/agent-tars/src/renderer/package.json`](diffhunk://#diff-ea3a409804af0e27dbbc1ed58d89cd8511633bdd3423bb454b7d6b35c1906d77R7-L10): Added `react-hook-form` as a dependency and removed the deprecated `@nextui-org/form` package.
* [`apps/agent-tars/src/renderer/src/components/LeftSidebar/Settings/AddServerModal.tsx`](diffhunk://#diff-8140b546d8d26bd4c85be59c4d9a3cd8c1acbd27d71f88ff5924b79e07aa18d2L …

refactor(agent-tars): mcp servers settings form

---

apps/agent-tars/src/renderer/src/components/LeftSidebar/Settings/SearchSettingsTab.tsx
packages/agent-infra/search/browser-search/src/engines/get-search-engine.ts
packages/agent-infra/search/browser-search/src/engines/index.ts
packages/agent-infra/search/browser-search/src/engines/sogou-engine.ts
packages/agent-infra/shared/src/agent-tars-types/search.ts

browser-search: add Sogou search engine.
Example of returned result:
```ts
{
title: 'UI-TARS-desktop/CONTRIBUTING.md at main · bytedance/UI-TARS-...',
url: 'https://www.sogou.com/link?url=hedJjaC291MuovqUW6cN1ma_85f9WHYRG8g_LUqhaba655l_FzkR2_ILhpWJFprBQKqCTDjEZrZE-ib8ISenP-XxOE5J3fXM',
snippet: "about what you're running into. Provide project and platform versions (nodejs, npm, etc), ... cd ui-tars-desktop Development Install dependencies $ pnpm install Run the application ...",
content: ''
},
{
title: '小米公布SU7高速爆燃事件细节',
url: 'https://view.inews.qq.com/a/20250401A05RUU00?scene=qqsearch&qudao=qbsearch_news&query=%E5%B0%8F%E7%B1%B3SU7%E7%9A%84%E4%BA%8B%E6%95%85%E8%BF%9B%E5%B1%95',
snippet: '4月1日，小米公司发言人微博发文公布“小米SU7爆燃致三人死亡”信息摘要：已提交车辆行驶数据及系统运行信息，全力配合警方工作。 小米SU7事故引发热议 专题',
content: ''
}
```

feat(browser-search): add sogou search engine

---

apps/agent-tars/src/main/store/setting.ts
apps/agent-tars/src/renderer/src/components/LeftSidebar/Settings/useAppSettings.ts
apps/agent-tars/src/shared/constants.ts
apps/agent-tars/tsconfig.node.json

When completing the setting-related work, we found that there are many redundant constants, which triggered some hidden bugs, such as different search default values.
This PR merges it.

refactor(agent-tars): merge redundant setting constants across threads

---

apps/agent-tars/src/renderer/src/components/CanvasPanel/EventPlayer/platform/FsPanel/FileEditPreview.tsx
apps/agent-tars/src/renderer/src/components/CanvasPanel/EventPlayer/platform/FsPanel/index.tsx
apps/agent-tars/src/renderer/src/components/CanvasPanel/EventPlayer/renderPlatformPanel.tsx

**macOS** file systems are **case-insensitive** by default, while **Linux** file systems are usually **case-sensitive**. If references to file names in the code or during the build process are inconsistent with the actual file case, this may cause build errors on Linux, but may not be apparent on macOS.
ref: https://github.com/bytedance/UI-TARS-desktop/actions/runs/14304629225/job/40085662954

fix(agent-tars): Could not resolve "./platform/FSPanel" in linux build

---

apps/agent-tars/src/renderer/src/components/LeftSidebar/Settings/SettingsModal.module.scss
apps/agent-tars/src/renderer/src/components/LeftSidebar/Settings/SettingsModal.tsx

The click event of the modal close button becomes ineffective. It is affected by the `-webkit-app-region: drag` property, and this situation occurs when the width exceeds a certain value.

fix: the click event of the modal close button becomes ineffective

---

packages/agent-infra/browser-use/assets/buildDomTree.js

The highlighting styles are abnormal on some websites.
So I add `container.style.backgroundColor = 'transparent';` to playwright-highlight-container

fix(agent-tars): set highlight div backgroundColor to transparent.

---

packages/agent-infra/browser/src/local-browser.ts
packages/ui-tars/operators/browser-operator/src/browser-operator.ts

When using Puppeteer's `Page.screenshot` for capturing screenshots, viewport changes can occur, resulting in a visual effect where the page briefly flickers:
https://github.com/user-attachments/assets/1257fe6d-098f-4536-a947-b4579830d873
After reviewing [GitHub Issue #7043](https://github.com/puppeteer/puppeteer/issues/7043), it was found that setting `captureBeyondViewport: false` did not resolve the issue.
Further investigation into [StackOverflow: puppeteer-page-screenshot-resizes-viewport](https://stackoverflow.com/questions/68059664/puppeteer-page-screenshot-resizes-viewport) revealed that setting `defaultViewport: null` effectively addresses the problem. However, we have specific requirements to set `width` and `height`, so this approach is not ideal for our use case.
Based on our …

fixed page blinking caused by viewport changes when executing screenshot in Puppeteer

---

apps/ui-tars/src/main/services/runAgent.ts
apps/ui-tars/src/renderer/src/components/RunMessages/Messages.tsx
packages/ui-tars/sdk/src/GUIAgent.ts
packages/ui-tars/shared/src/types/agent.ts

This PR optimizes the error handling mechanism in GUI Agent SDK to provide a more robust and maintainable error handling system.
```mermaid
graph TD
A[GUI Agent Runtime] --> B{guiAgentErrorParser}
B --> C[Screenshot Retry Error]
B --> D[Invoke Retry Error]
B --> E[Action Execution Retry Error]
B --> F[Max Loop Error Model]
B --> G[Model Service Error]
C --> H[OnError Callback]
D --> H
E --> H
F --> H
G --> H
H --> I[Error Message Component]
```
```mermaid
classDiagram
class GUIAgentError {
+ErrorStatusEnum code
+string message
+string? stack
+string? detail
+constructor(code, message, stack?, detail?)
}
```
- Unified error handling through `OnError` callback
- Removed direct error throwing for better error management
- Centralized error parsing in `guiAgentErrorParser`
- Improved error …

feat(ui-tars): format error status and messages

---

apps/agent-tars/src/renderer/src/components/ChatUI/index.tsx

There is only one Welcome page when clicking to share.

fix(agent-tars): share reporter not work

---

packages/agent-infra/mcp-servers/browser/src/server.ts

Here's the updated PR message with additional justification:
close #566
This PR fixes an issue where the browser-click method in the browser-use MCP server was failing to handle DOM elements with index 0. The previous implementation used a logical NOT check (`!args.index`), which treated index 0 as falsy, thus rejecting valid requests to interact with elements at index 0.
The root issue was identified in the interaction between two components:
1. In `packages/agent-infra/browser-use/assets/buildDomTree.js` (line 22), the highlight indexing starts from 0:
```javascript
const { doHighlightElements, focusHighlightIndex, viewportExpansion } = args;
let highlightIndex = 0; // Reset highlight index
```
and in line 680, this code increse from index 0. 
```javascript
if (isInteractive && …
```

fix(browser-mcp): element index validation to properly handle zero index in browser tools

---

packages/agent-infra/browser/src/base-browser.ts
packages/ui-tars/operators/browser-operator/src/browser-operator.ts

In UI-TARS-Desktop, when the  `Browser Operator` mode is selected, if the user manually closes the browser instance launched by the app, the interface will freeze and fail to execute tasks during the second use of the `Browser Operator`.
This fix ensures that before each execution of the `Browser Operator`, the app checks whether the Browser instance exists. If it does not, a new browser instance will be launched.

fix(browser): where the browser does not relaunch after being manually closed

---

apps/ui-tars/src/main/window/ScreenMarker.ts
apps/ui-tars/src/renderer/src/pages/widget/index.tsx

If `lastMessage` is undefined, it causes the widget UI to crash. Additionally, since the `BrowserWindow` transparency attribute is enabled, the crash manifests as the window disappearing (instead of the typical white screen).

fix(ui-tars): fix the issue where the widget disappears in release mode

---

apps/agent-tars/dev-app-update.yml
apps/agent-tars/forge.config.ts
apps/agent-tars/package.json
apps/agent-tars/resources/app-update.yml
apps/agent-tars/src/main/electron-updater/GitHubProvider.ts
apps/agent-tars/src/main/electron-updater/util.ts
apps/agent-tars/src/main/utils/updateApp.ts
apps/ui-tars/dev-app-update.yml
apps/ui-tars/package.json
apps/ui-tars/resources/app-update.yml
apps/ui-tars/src/main/electron-updater/GitHubProvider.ts
apps/ui-tars/src/main/electron-updater/index.ts
apps/ui-tars/src/main/electron-updater/utils.ts
apps/ui-tars/src/main/main.ts
pnpm-lock.yaml
scripts/release-beta-pkgs.sh
scripts/release-pkgs.sh

Close https://github.com/bytedance/UI-TARS-desktop/issues/543
The original implementation relies on the GitHub releases feed at [https://github.com/bytedance/UI-TARS-desktop/releases.atom](https://github.com/bytedance/UI-TARS-desktop/releases.atom), which only returns the latest 10 tags.
However, since our repository includes npm releases, UI-TARS, and Agent-TARS (two Electron apps), the feed often excludes the latest Agent-TARS tags. This prevents the latest label from being updated correctly for Agent-TARS, leading to update errors.
To resolve this, we now fetch the latest release version from our existing Homebrew tap using the Formulae API: `https://formulae.brew.sh/api/cask/ui-tars.json` and `https://formulae.brew.sh/api/cask/agent-tars.json` …

fix(electron-updater): agent-tars update bug

---

multimodal/agent-tars-cli/src/config/builder.ts
multimodal/agent-tars-cli/tests/config-builder.test.ts

The following command do not work because of a historical regression issue:
```
agent-tars
--provider deepseek \
--model deepseek-chat \
--apiKey DEEPSEEK_API_KEY
```

fix(agent-tars-cli): set apiKey with env does not work

---

multimodal/agent-tars-cli/src/commands/options.ts
multimodal/agent-tars-cli/src/commands/workspace.ts
multimodal/agent-tars-cli/src/config/loader.ts
multimodal/agent-tars-cli/src/config/paths.ts
multimodal/agent-tars-cli/src/core/interactive-ui.ts
multimodal/agent-tars-cli/tests/config-paths.test.ts

Adjusting the configuration of Agent TARS through TypeScript is a very useful feature, but currently, Agent TARS CLI can only load the config passed through `--config` or the config file in the current directory. 
This Pull Request enables Agent TARS to read the configuration from the Global Workspace and give it the highest priority.

feat(agent-tars-cli): support load config from global workspce

---

multimodal/agent-tars/tests/__snapshots__/browser_tools_browser-use-only.snap
multimodal/agent-tars/tests/__snapshots__/browser_tools_mixed.snap
multimodal/agent/src/agent/tool-manager.ts

- Close: #769 
`0.1.12-beta.5` does not work in `aws_sdk_claude37_sonnet` model with `azure-openai` provider 
> Error in agent execution: Error: 400 operation error Bedrock Runtime: ConverseStream, https response error StatusCode: 400, RequestID: 9075e9e9-bf98-43e6-a615-e5e0018c5f02, ValidationException: The json schema definition at toolConfig.tools.13.toolSpec.inputSchema is invalid. Fix the following errors and try again: $.properties: null found, object expected

fix(agent): tool schema miss `properties` in native tool call (close: #769)

---

multimodal/agent-tars/src/agent-tars.ts

Always use manually generated screenshots, because browser gui agent screenshots are generated before `browser_navigate`, and they are a white background in all time.

feat(agent-tars): always create new navigation screenshot for gui agent

---

multimodal/agent-tars-cli/src/commands/run.ts
multimodal/agent-tars-cli/src/core/index.ts
multimodal/agent-tars-cli/src/core/server-run.ts
multimodal/agent-tars-server/src/server.ts

`agent-tars run` is currently fully run in memory, this pull request has introduced a new feature (`--cache`) to launch `agent-tars run` by launching the Agent TARS Server, then `agent-tars run` has the ability to automatically save Session data.
This new cli flag `--cache` is enabled by default, and user can use `no-cache` to downgrade to the old behavior.

feat(agent-tars-cli): support `agent-tars run --cache` by default

---

multimodal/agent-tars-cli/rslib.config.ts
multimodal/agent-tars-cli/src/core/headless-server.ts
multimodal/agent-tars-cli/src/core/interactive-ui.ts
multimodal/agent-tars-cli/src/env.d.ts
multimodal/agent-tars-server/src/api/controllers/system.ts
multimodal/agent-tars-server/src/api/routes/system.ts
multimodal/agent-tars-server/src/server.ts

This pull request enhances the Agent TARS Server by integrating version and build timestamp metadata.  creating a new API endpoint (`/api/v1/version`) for version details
```bash
curl --location 'http://localhost:8888/api/v1/version' \
--header 'Content-Type: application/json'
```
```json
{"version":"0.2.10","buildTime":1752213411190}
```
Renamed `ServerInjectionOptions` to `ServerExtraOptions` and expanded it to include version-related properties. Adjusted relevant server constructors and configurations to reflect the updated options structure.

feat(agent-tars-server): add `/api/v1/version`

---

multimodal/agent-tars-web-ui/src/standalone/workspace/utils/contentStandardizer/handlers.ts
multimodal/agent-tars-web-ui/src/standalone/workspace/utils/contentStandardizer/standardizer.ts

Workspace panel displays wrong status event if this tool call is successful:

fix(agent-tars-web-ui): browser vision control display wrong status

---

multimodal/agent-tars-web-ui/src/common/state/actions/eventProcessor.ts
multimodal/agent-tars-web-ui/src/common/types/index.ts
multimodal/agent-tars-web-ui/src/standalone/chat/Message/Message.css
multimodal/agent-tars-web-ui/src/standalone/chat/Message/components/MessageGroup.tsx
multimodal/agent-tars-web-ui/src/standalone/chat/Message/components/SystemMessage.tsx
multimodal/agent-tars-web-ui/src/standalone/chat/Message/index.tsx

In message group processing stage, we only filtered `user` and `assistant` message, this pull request fix this issue and refine the system error UI rendering:

fix(agent-tars-web-ui): do not render system error

---

packages/agent-infra/browser/src/local-browser.ts

`--disable-http2` will cause GraphQL to fail to connect!
| args | screenshot |
| ------ | ------ |
| `--disable-http2` | <img width="929" height="443" alt="image" src="https://github.com/user-attachments/assets/b9fecb99-6908-4feb-b911-f37934289815" /> |
| normal | <img width="986" height="261" alt="image" src="https://github.com/user-attachments/assets/e7586875-b511-477d-8ca7-080144fa097d" /> |

fix(browser): remove disable http2

---

multimodal/agent-tars/src/agent-tars.ts
multimodal/agent-tars/src/shared/workspace-path-resolver.ts
multimodal/agent-tars/tests/shared/workspace-path-resolver.test.ts

In https://github.com/bytedance/UI-TARS-desktop/pull/860 and https://github.com/bytedance/UI-TARS-desktop/pull/862 , we fixed the path resolve issue of some workspace path for some tools, in this pull request, we add full support for file and command tools.

fix(agent-tars): all file and command tools should respect workspace

---

multimodal/agent-tars-web-ui/src/standalone/workspace/components/ShareButton.tsx
multimodal/agent-tars-web-ui/src/standalone/workspace/components/WorkspaceHeader.tsx

Currently, if the Web UI supports if the query has `?focus={file}` and the file exists in Generated Files, the state switches to full screen rendering html or markdown.
This pull request add a button on the far right in the Workspace Header  to support the share button for HTML and Markdown. When the user clicks it, it essentially adds `?focus={file}` based on the current location href. Next, if others get this URL, they can directly focus on this file for display.

feat(agent-tars-web-ui): support share generate files

---

multimodal/agent-tars/cli/src/index.ts
multimodal/agent-tars/interface/src/constants.ts
multimodal/tarko/agent-cli/src/config/builder.ts
multimodal/tarko/agent-server/src/server.ts
multimodal/tarko/agent-server/src/storage/FileStorageProvider.ts
multimodal/tarko/agent-server/src/storage/SQLiteStorageProvider.ts
multimodal/tarko/agent-server/src/storage/index.ts
multimodal/tarko/interface/src/constants.ts
multimodal/tarko/interface/src/server.ts
multimodal/tarko/interface/src/storage-implementation.ts

This pull request fixes a critical backward compatibility issue introduced by the Tarko CLI Framework integration in [#1001](https://github.com/bytedance/UI-TARS-desktop/pull/1001). The framework change inadvertently modified the default SQLite database name from `~/.agent-tars/agent-tars.db` to `~/.agent-tars/tarko.db`, causing existing user databases to become inaccessible and creating breaking changes.
After the Tarko CLI Framework was introduced in PR #1001, Agent TARS CLI users experienced data loss because:
- **Previous behavior**: SQLite database stored at `~/.agent-tars/agent-tars.db`
- **New behavior**: SQLite database stored at `~/.agent-tars/tarko.db` 
- **Impact**: Existing user sessions, conversation history, and configuration data became inaccessible
This PR restores …

fix(agent-tars-cli): sqlite should consider backward compatibility

---

multimodal/tarko/agent-server/src/storage/SQLiteStorageProvider.ts

This PR implements database schema migration functionality to handle the transition from the old `workingDirectory` column to the new `workspace` column in the SQLite sessions table.
**Problem Solved:**
Users upgrading from older versions encounter database errors when the application tries to access the new `workspace` column that doesn't exist in their existing database schema:
```
SessionRestoreMiddleware Session restore middleware error: Failed to get session: no such column: workspace
Failed to get session jr5gOEY_W4K3CPTS5Q5vh: Error: no such column: workspace
at SQLiteStorageProvider.getSessionMetadata (/multimodal/tarko/agent-server/dist/index.js:18813:42)
at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
at async sessionRestoreMiddleware …
```

feat(agent-server): handle old workspace schema migration

---

packages/agent-infra/search/search/src/searxng.ts

Fixes `npx @agent-infra/mcp-server-search` failing with "Cannot find module 'node-fetch'" error by using native fetch API available in Node.js 18+.

fix: replace node-fetch with native fetch for Node.js 22

---

multimodal/tarko/agent-web-ui/src/standalone/navbar/Navbar.tsx

Optimizes navbar space utilization by implementing dynamic width calculation and intelligent truncation for agent and model name badges.
- Added `DynamicNavbarCenter` component with real-time width measurement
- Implements proportional space distribution when content exceeds available width
- Only applies truncation when absolutely necessary
- Maintains responsive behavior across different screen sizes
- Uses `useRef` and `useEffect` for DOM measurement
- Calculates text widths using temporary DOM elements
- Distributes available space proportionally between badges
- Preserves original styling and visual design
- ✅ Build passes successfully
- ✅ Component renders correctly with dynamic sizing
- ✅ Responsive behavior verified

feat(tarko): optimize navbar space for agent and model display (close: #1076)

---

multimodal/tarko/agent-web-ui/src/standalone/chat/Message/components/MultimodalContent.tsx
multimodal/tarko/agent-web-ui/src/standalone/chat/Message/index.tsx

Fixes text visibility issue in user messages by using consistent plain text rendering, avoiding markdown styling conflicts.
---
Text + Image
````md
Explain this code in image and following block:
```ts
export type TConstructor<T, U extends unknown[] = unknown[]> = new (...args: U) => T;
```
````
https://github.com/bytedance/UI-TARS-desktop/issues/1105
- ✅ Build passes
- ✅ Text now visible in all user message types
- ✅ No unwanted toolbars or styling conflicts
- ✅ Clean, simple rendering approach
Closes #1103

fix(tarko): use plain text rendering for user messages (closes #1103)

---

multimodal/pnpm-lock.yaml
multimodal/tarko/agent-web-ui/package.json
multimodal/tarko/agent-web-ui/src/common/state/actions/eventProcessor.ts
multimodal/tarko/agent-web-ui/src/common/utils/formatters.ts
multimodal/tarko/agent-web-ui/src/sdk/code-editor/DiffViewer.tsx
multimodal/tarko/agent-web-ui/src/sdk/code-editor/index.ts
multimodal/tarko/agent-web-ui/src/standalone/workspace/renderers/DiffRenderer.tsx
multimodal/tarko/agent-web-ui/src/standalone/workspace/renderers/ToolResultRenderer.tsx
multimodal/tarko/agent-web-ui/src/standalone/workspace/types.ts
multimodal/tarko/agent-web-ui/src/standalone/workspace/utils/contentStandardizer/standardizer.ts

- Closes #1090
Simplified implementation of diff visualization for `edit_file` tool results with **50% less code** than the original PR #1091.

feat(tarko): `edit_file` renderer

---

README.md

Upon trying to setup my local environment I noticed the links are pointing to an old version of the repository that points to the wrong blob. This change brings the two broken links back up.

Fix link leading to local docs for local and remote operators

---

multimodal/tarko/agent-web-ui/src/common/state/actions/eventProcessor.ts
multimodal/tarko/agent-web-ui/src/common/state/atoms/rawEvents.ts

Add raw events and tool mapping storage atoms to preserve original event data for debugging purposes.
```ts
import { useAtomValue } from 'jotai';
import { rawEventsAtom } from '@/common/state/atoms/rawEvents';
function EventsComponent({ sessionId }: { sessionId: string }) {
const rawEvents = useAtomValue(rawEventsAtom);
const events = rawEvents[sessionId] || [];
return (
<div>
<h3>Raw Events ({events.length})</h3>
{events.map((event, index) => (
<div key={index}>
<strong>{event.type}</strong> - {event.timestamp}
</div>
))}
</div>
);
}
```
```tsx
import { useAtomValue } from 'jotai';
import { rawToolMappingAtom } from '@/common/state/atoms/rawEvents';
function ToolsComponent({ sessionId }: { sessionId: string }) {
const rawToolMapping = useAtomValue(rawToolMappingAtom);
const toolMappings …
```

feat(tarko): add raw events state

---

multimodal/tarko/agent-server/src/storage/SQLiteStorageProvider.ts

Fix database migration that was deleting all events data during schema updates.
Commit 4dcc32172d8c87520fab9c39499edf5fe4358064 introduced a database migration bug where:
1. **Foreign Key Cascade Deletion**: The migration used `DROP TABLE sessions` followed by table recreation:
```typescript
// Old problematic code
this.db.exec('DROP TABLE sessions');
this.db.exec('ALTER TABLE sessions_new RENAME TO sessions');
```
2. **Events Table Constraint**: The `events` table has foreign key constraint:
```sql
FOREIGN KEY (sessionId) REFERENCES sessions (id) ON DELETE CASCADE
```
3. **Data Loss Chain**: When `sessions` table was dropped, SQLite automatically deleted all `events` records due to the CASCADE constraint, even though session data was being copied to the new table.
4. **Symptoms**: …

fix(tarko): preserve events data during database migration

---

multimodal/websites/docs/docs/en/guide/basic/workspace.mdx
multimodal/websites/docs/docs/zh/guide/basic/workspace.mdx

Correct workspace default path in English and Chinese guides.
```diff
- $pwd/gent-tars-workspace
+ $pwd/agent-tars-workspace
```

fix(docs): correct workspace default path in English and Chinese guides

---

packages/agent-infra/mcp-client/src/index.ts

Increase MCP client default timeout from 10 seconds to 60 seconds to prevent timeouts on slower operations.
Closes #1140

feat(mcp): increase default timeout from 10s to 60s

---

multimodal/tarko/agent-web-ui/src/sdk/markdown-renderer/components/CodeBlock.tsx

Fixed inline code text color in dark mode from `dark:text-gray-800` to `dark:text-gray-200` for better visibility.
```tsx
// Before
<code className="... dark:text-gray-800 ...">
// After  
<code className="... dark:text-gray-200 ...">
```

fix(tarko): inline code dark mode text color

---

multimodal/tarko/agent-cli/src/config/builder.ts
multimodal/tarko/agent-cli/src/core/cli.ts
multimodal/tarko/agent-cli/src/utils/index.ts
multimodal/tarko/agent-cli/src/utils/workspace-config.ts
multimodal/tarko/agent-cli/tests/config-builder.test.ts
multimodal/tarko/agent-cli/tests/workspace-config-e2e.test.ts
multimodal/tarko/agent-cli/tests/workspace-config.test.ts
multimodal/tarko/agent-cli/vitest.config.mts

Adds support for workspace-specific configuration files in Agent CLI. The CLI now automatically loads `.tarko/instructions.md` from the workspace directory and injects it as the agent's system prompt.
- L0: CLI Arguments (highest priority)
- **L1: Workspace Config File (.tarko/instructions.md)** ← New addition
- L2: Global Workspace Config File
- L3: CLI Config Files
- L4: CLI Remote Config
- L5: CLI Node API Config (lowest priority)
```bash
mkdir -p .tarko
echo "You are a helpful coding assistant specialized in TypeScript." > .tarko/instructions.md
tarko start
```

feat(tarko): add workspace config support for instructions.md

---

.gitignore
multimodal/tarko/agent-server/src/storage/SQLiteStorageProvider.ts
multimodal/tarko/agent-server/src/storage/__tests__/SQLiteStorageProvider.test.ts

Adds proper error handling for database rollback operations in SQLite migration to prevent unhandled exceptions when rollback fails.
```typescript
try {
this.db.exec('ROLLBACK');
} catch (rollbackError) {
console.error('Failed to rollback transaction:', rollbackError);
}
```
Fixes potential crash scenario where migration failure followed by rollback failure could cause unhandled exceptions.

fix(tarko): add rollback error handling in sqlite migration

---

multimodal/agent-tars/core/src/agent-tars.ts

Improves AgentTARS system prompt handling with a layered approach that preserves core functionality while giving user instructions higher priority.
**Problem**: Original concatenation approach (`${systemPrompt}\n\n${options.instructions}`) put user instructions at the end, making them less effective. Direct override would break agent-tars core capabilities.
**Solution**: Layered prompt strategy where:
- Core system capabilities provide the foundation (browser rules, file handling, etc.)
- User instructions are placed **after** with explicit higher priority
- Preserves all agent-tars functionality while allowing effective customization
**Before**: `${systemPrompt}\n\n${options.instructions}` - user instructions simply appended
**After**: System prompt first, then user instructions with …

feat(agent-tars): support flexible system prompt override

---

packages/agent-infra/mcp-client/README.md
packages/agent-infra/mcp-client/package.json
packages/agent-infra/mcp-client/src/index.ts
packages/agent-infra/mcp-client/test/index.test.ts
packages/agent-infra/mcp-shared/src/client/types.ts
pnpm-lock.yaml

This PR adds comprehensive filtering capabilities and testing to the MCP client:
```ts
const mcpClient = new MCPClient([
{
type: 'builtin',
name: 'FileSystem',
description: 'filesystem tool',
mcpServer: createFileSystemServer({
allowedDirectories: [omegaDir],
}),
// Filter configuration
filters: {
tools: {
allow: ['list_*', 'read_*'], // Only allow tools starting with 'list_' or 'read_'
block: ['delete_*']          // Block any tools starting with 'delete_'
},
prompts: {
allow: ['safe_*'],           // Only allow prompts starting with 'safe_'
block: ['admin_*']           // Block prompts starting with 'admin_'
}
}
}
]);
```
Close https://github.com/bytedance/UI-TARS-desktop/issues/1138
Close https://github.com/bytedance/UI-TARS-desktop/issues/1154

feat(mcp-client): add tools and prompts filtering with comprehensive tests

---

multimodal/tarko/agent-cli/README.md
multimodal/tarko/agent-cli/src/core/cli.ts
multimodal/tarko/interface/src/cli.ts

Update Tarko CLI command semantics to support `tarko run [agent]` for interactive UI and `tarko run --headless` for silent mode.
- Changed default command from `tarko [start]` to `tarko [run]`
- Added support for `tarko run [agent]` to load custom agents
- Added `--headless` flag for silent mode execution
- Updated CLI documentation and help text
- Maintained backward compatibility with existing `--agent` flag
- `tarko start` command removed (use `tarko run` instead)
- `tarko run` without `--headless` now starts interactive UI (previously was headless mode)
- `tarko start` → `tarko run` or `tarko`
- `tarko run "query"` → `tarko run --headless --input "query"`
- `tarko --agent ./agent.js` → `tarko run ./agent.js`

feat(tarko): update run command semantics

---

multimodal/tarko/agent-cli/src/core/cli.ts

Fix CLI parameter handling issue where `tarko --agent ./` command failed due to incorrect parameter order processing in the run command action handler after PR #1158.
**Problem**: After PR #1158 introduced new CLI command structure, the `tarko --agent ./` syntax stopped working because the CLI argument parsing incorrectly handled CAC's dynamic parameter passing for optional positional parameters `[run] [agent]`.
**Root Cause**: CAC library passes arguments in a specific pattern for optional positional parameters:
- `tarko --agent ./` → `args = [undefined, undefined, cliArguments]`
- `tarko run` → `args = ['run', undefined, cliArguments]`
- `tarko run ./` → `args = ['run', './', cliArguments]`
- `tarko ./` → `args = [undefined, './', cliArguments]`
**Supported Syntax**:
- `tarko --agent …

fix(tarko): handle CLI parameter order for agent argument

---

multimodal/omni-tars/code-agent/package.json
multimodal/omni-tars/code-agent/src/CodeAgentPlugin.ts
multimodal/omni-tars/gui-agent/package.json
multimodal/pnpm-lock.yaml

upgrades the `@agent-infra/sandbox` package across both code-agent and gui-agent components and introduces a sandbox health check mechanism.
- **Code Agent**: Upgraded `@agent-infra/sandbox` from version `0.0.2-beta5` to `0.0.2-beta7`
- **GUI Agent**: Upgraded `@agent-infra/sandbox` from version `0.0.1` to `0.0.2-beta7` 
- **Health Monitoring**: Added `checkSandbox()` method to `CodeAgentPlugin` that performs health checks on sandbox connections
The new `checkSandbox()` method is called during plugin initialization and leverages the `healthCheck()` method from the AioClient to ensure sandbox connectivity before executing code operations.

feat: upgrade @agent-infra/sandbox package and add health check

---

multimodal/omni-tars/core/src/AgentComposer.ts
multimodal/omni-tars/core/src/AgentPlugin.ts
multimodal/omni-tars/core/src/ComposableAgent.ts
multimodal/omni-tars/gui-agent/src/GUIAgentToolCallEngine.ts
multimodal/omni-tars/gui-agent/src/GuiAgentPlugin.ts

This update introduces a new feature in the Omni GUI Agent: on-demand screenshot execution triggered by the EachLoopEnd hook. This enhancement allows users to automatically capture the UI state at the end of each loop iteration.
Key changes include:
- Integration of screenshot trigger logic within the EachLoopEnd hook.
- Support for configurable, on-demand screenshot execution to avoid unnecessary resource usage.
- Code structure improvements to ensure stable and reliable functionality.

feat(omni-gui-agent): execute screenshot on demand on EachLoopEnd hook

---

multimodal/tarko/agent-web-ui/src/standalone/workspace/WorkspaceDetail.tsx
multimodal/tarko/agent-web-ui/src/standalone/workspace/renderers/EditFileRenderer.tsx
multimodal/tarko/agent-web-ui/src/standalone/workspace/renderers/FileRenderer.tsx
multimodal/tarko/agent-web-ui/src/standalone/workspace/renderers/FileResultRenderer.tsx
multimodal/tarko/agent-web-ui/src/standalone/workspace/renderers/generic/GenericResultRenderer.tsx
multimodal/tarko/agent-web-ui/src/standalone/workspace/renderers/generic/components/index.ts

Decoupled file rendering logic from GenericResultRenderer by migrating FileResultRenderer out of generic/components and establishing dedicated renderers with clear interfaces.
- Migrated `FileResultRenderer` from `generic/components/` to standalone renderer
- Created dedicated `FileRenderer` for `file_result` and `file` types
- Created dedicated `EditFileRenderer` for `edit_file` type  
- Updated `CONTENT_RENDERERS` registry to use new dedicated renderers
- Removed file handling logic from `GenericResultRenderer`
- Eliminated coupling between generic components and file-specific logic
- Clear architectural boundaries - generic components stay generic
- File rendering logic is now self-contained and reusable
- Explicit interfaces for file rendering
- Better maintainability and …

feat(tarko): decouple file renderers from GenericResultRenderer

---

multimodal/tarko/agent-web-ui/src/standalone/chat/Message/index.tsx
multimodal/tarko/agent-web-ui/src/standalone/workspace/renderers/BrowserControlRenderer.tsx

This pull request removes the "view final environment state" button from the chat message UI and updates the logic in `BrowserControlRenderer` to search for environment screenshots after, rather than before, the current tool call. These changes streamline the user interface and correct the screenshot retrieval logic.
**UI cleanup and feature removal:**
- Removed the "view final environment state" button and all related logic from the chat `Message` component, including click handlers, state checks, and associated imports. This simplifies the message UI and eliminates unused code. [[1]](diffhunk://#diff-2d5a5085277b5368f98d33930e0b979db0a869fcf54c63b515cfcfce85081c2cL20-R20) [[2]](diffhunk://#diff-2d5a5085277b5368f98d33930e0b979db0a869fcf54c63b515cfcfce85081c2cL78-L104) …

feat(tarko): using backward-only screenshot association

---

packages/agent-infra/mcp-client/src/index.ts
packages/agent-infra/mcp-client/test/index.test.ts
packages/agent-infra/mcp-shared/src/client/types.ts

Adds configurable timeout support for MCP Client to handle long-running tasks like unit tests and dependency installation.
**Usage:**
```typescript
// Use default 60s timeout
const client = new MCPClient(servers);
// Set custom default timeout
const client = new MCPClient(servers, { defaultTimeout: 120 });
// Server-specific timeout overrides default
const server = {
name: 'test-server',
timeout: 180, // 3 minutes for this server
// ...
};
```

feat(mcp-client): add configurable timeout

---

multimodal/omni-tars/code-agent/package.json
multimodal/omni-tars/code-agent/src/CodeAgentPlugin.ts
multimodal/omni-tars/code-agent/src/CodeToolCallEngine.ts
multimodal/omni-tars/code-agent/src/tools/ExcuteBash.ts
multimodal/omni-tars/mcp-agent/src/McpToolCallEngine.ts
multimodal/pnpm-lock.yaml

add custom timeout configuration for the `execute_bash` tool and removes `stop_sequences` configuration from the CodeToolCallEngine and McpToolCallEngine.
1. **Execute Bash Timeout Enhancement**: Added a configurable 2-minute timeout (120 seconds) for bash command execution in the ExcuteBash tool to prevent hanging operations and improve reliability.
2. **Stop Sequences Cleanup**: Removed the deprecated `stop_sequences` configuration from both CodeToolCallEngine and McpToolCallEngine, keeping only the standard OpenAI `stop` parameter.
3. **Dependency Updates**: Updated `@agent-infra/sandbox` from `0.0.2-beta7` to `0.0.2` for improved stability.
4. **Client Configuration**: Added `retries: 0` configuration to the AioClient to prevent automatic retries.

feat(o-agent): add custom timeout for execute_bash tool; remove stop_sequences config

---

multimodal/tarko/agent-web-ui/src/sdk/code-editor/MonacoCodeEditor.tsx
multimodal/tarko/agent-web-ui/src/standalone/workspace/renderers/FileResultRenderer.tsx
multimodal/tarko/agent-web-ui/src/standalone/workspace/renderers/ScriptResultRenderer.tsx

Removes unnecessary language mappings for languages that are unlikely to be used in UI-TARS desktop application context, addressing over-engineering in the codebase.
**Removed unnecessary language support:**
- Ruby, Java, Go, Rust, C/C++, PHP, SQL, Vue, Svelte
**Kept essential languages:**
- JavaScript/TypeScript (core web technologies)
- Python (primary scripting language)
- HTML/CSS (web content)
- JSON, YAML (configuration formats)
- Markdown (documentation)
- Bash (shell scripting)
**Files modified:**
- `FileResultRenderer.tsx`: Simplified language detection mapping
- `ScriptResultRenderer.tsx`: Reduced interpreter support to essentials
- `MonacoCodeEditor.tsx`: Streamlined Monaco language mapping
- **Simplified codebase**: Removes complexity for unused features
- **Focused scope**: …

refactor(tarko): remove over-designed language support

---

multimodal/websites/docs/src/components/NotFoundLayout.tsx

Fixed 404 page white screen issue in `websites/docs` by adding missing `useI18n` import in `NotFoundLayout` component.
The component was using `t()` function for translations without importing `useI18n` from `rspress/runtime`, causing `ReferenceError: t is not defined` in browser console.

docs: fix missing useI18n import in NotFoundLayout

---

multimodal/tarko/agent-web-ui/src/standalone/workspace/components/TerminalOutput.tsx
multimodal/tarko/agent-web-ui/src/standalone/workspace/renderers/ScriptResultRenderer.tsx

Fixed UI issues in `ScriptResultRenderer` where icon and text were wrapping awkwardly, and improved exit code styling in `TerminalOutput` component.

fix(tarko): improve script execution ui layout and styling

---

multimodal/tarko/agent-interface/src/agent-run-options.ts
multimodal/tarko/agent-server/src/api/controllers/queries.ts
multimodal/tarko/agent-server/src/core/AgentSession.ts
multimodal/tarko/agent-server/tests/api/queries.test.ts
multimodal/tarko/agent/src/agent/agent.ts

Adds `codebase` metadata type to contextual references in environment input, enabling proper typing for injected context introduced in [PR #1134](https://github.com/bytedance/UI-TARS-desktop/pull/1134).
- Add `metadata` field support to `environmentInput` in `AgentRunBaseOptions`
- Update Agent class to properly pass metadata when creating `environment_input` events
- Add `codebase` metadata type to contextual references in `queries.ts`
- Enables consumers to identify environment input as codebase context for better processing
Resolves remaining **issue 1** from [PR #1272](https://github.com/bytedance/UI-TARS-desktop/pull/1272)

feat(tarko): add codebase metadata to contextual references

---

multimodal/tarko/agent-cli/src/config/builder.ts
multimodal/tarko/agent/src/agent/agent.ts
multimodal/tarko/interface/src/cli.ts

Fixes `--thinking` option not working in `tarko-cli` since it passed wrong options to Agent Kernel.
Seed 1.5 VL Error:
> Error in agent execution: Error: 400 The parameter `` specified in the request are not valid: we could not parse the JSON body of your request. Request id: 021756308745160daa05a91ab0f5c619c670634a3049ce3b86e57

fix(tarko-cli): `--thinking` does not work

---

multimodal/tarko/shared-utils/src/gui-agent.ts

Fixes issue where `open_computer()` action returns incorrect `startX: 0` and `startY: 0` coordinates in `normalizedAction` response.
The problem was in `convertToNormalizedAction` function in `@tarko/shared-utils` where unknown action types fell back to click action with zero coordinates. 
**Root Cause:** Unknown action types like `open_computer` were being converted to click actions with `startX: 0, startY: 0`.
**Solution:** Modified the default case to preserve the original action type with empty inputs instead of falling back to click action.
**Changes:**
- Updated default case in `convertToNormalizedAction` to return raw action type
- Removed fallback to click action that caused incorrect coordinates
- Now `open_computer()` returns `{ type: 'open_computer', inputs: {} }` instead of `{ …

fix(tarko): handle open_computer action normalization

---

multimodal/tarko/agent-web-ui/src/common/components/JsonRenderer.tsx
multimodal/tarko/agent-web-ui/src/standalone/workspace/components/RawModeRenderer.tsx

Adds one-click copy functionality to `JsonContent` component for copying raw JSON data.
Builds on https://github.com/bytedance/UI-TARS-desktop/pull/1167 to enhance JSON renderer with copy button that appears on hover and provides visual feedback when clicked.

feat(tarko): one-click copy raw tool data

---

multimodal/tarko/agent-web-ui/src/standalone/workspace/renderers/BrowserControlRenderer.tsx
multimodal/tarko/agent-web-ui/src/standalone/workspace/renderers/browser-control/StrategySwitch.tsx

Moves `StrategySwitch` rendering after `ScreenshotDisplay` in `BrowserControlRenderer` to prevent visual flicker when switching between `browser_navigate` and `EnvironmentInputEvent` that both render Browser Screenshots.
The issue occurred because both events render screenshot content, and having the strategy switch positioned before the screenshot caused visual inconsistency during transitions.

fix(tarko): move StrategySwitch after ScreenshotDisplay to prevent flicker

---

multimodal/tarko/agent-web-ui/src/standalone/workspace/WorkspaceDetail.tsx
multimodal/tarko/agent-web-ui/src/standalone/workspace/renderers/BrowserShell.tsx

This fixes the issue where the address bar would stretch to fill all available space without any visual breathing room on the right edge.

fix(tarko): browser shell url bar takes full width without spacing

---

multimodal/tarko/agent-web-ui/src/standalone/chat/Message/components/ActionButton.tsx
multimodal/tarko/agent-web-ui/src/standalone/chat/Message/components/ToolCalls.tsx

Fixes RTL rendering issue where non-file tools like commands were incorrectly displayed with RTL direction.
Previously, all tool descriptions in Tool Call Blocks used `[direction:rtl]` styling, causing commands like `git add .` to render as `. git add` in RTL layout.
Now RTL styling is applied only to file-related tools (`read_file`, `write_file`, `edit_file`, `list_directory`, `str_replace_editor`) where showing complete relative paths is beneficial.
Ref: https://github.com/bytedance/UI-TARS-desktop/pull/1309

feat(tarko): apply RTL only to file-related tools in tool blocks

---

multimodal/tarko/agent-web-ui/src/sdk/markdown-renderer/components/CodeBlock.tsx

Removed language badge and action buttons from `CodeBlock` component to fix streaming rendering flicker issue.
The action buttons (copy, word wrap toggle) and language badge were causing visual flicker during streaming code block rendering. This change simplifies the component by removing all interactive elements and hover states that contributed to the rendering instability.

chore(tarko): remove codeblock action buttons

---

multimodal/tarko/agent-cli/src/core/commands/start.ts
multimodal/tarko/agent-server/src/api/controllers/sessions.ts
multimodal/tarko/agent-server/src/api/controllers/share.ts
multimodal/tarko/agent-server/src/services/ShareService.ts
multimodal/tarko/agent-server/src/utils/index.ts
multimodal/tarko/agent-server/src/utils/share.ts
multimodal/tarko/agent-server/src/utils/webui/config.ts
multimodal/tarko/agent-server/src/utils/webui/index.ts

Fixes issue where `AGENT_WEB_UI_CONFIG` was not persisted in shared links, causing replay mode to lose configuration.

fix(tarko): persist agent web ui config in share

---

multimodal/tarko/agent-web-ui/src/standalone/workspace/renderers/browser-control/useScreenshots.ts

Fixes screenshot flickering in `BrowserControlRenderer` when using `afterAction` strategy during real-time execution.
When using `afterAction` strategy, the action appears first but the screenshot comes later, causing an empty state that leads to flickering during real-time rendering and replay. This change makes `ScreenshotDisplay` fallback to `beforeActionImage` when `afterActionImage` is not available yet, preventing the empty state.
**Changes:**
- Modified `useScreenshots` hook to always search for `beforeActionImage` as potential fallback
- Added fallback logic in `afterAction` strategy to use `beforeActionImage` when `afterActionImage` is unavailable
- Improved console warnings to indicate fallback behavior

fix(tarko): fallback to beforeActionImage in afterAction strategy to prevent flickering

---

multimodal/tarko/agent-web-ui/src/standalone/chat/Message/components/ThinkingToggle.tsx

Unified Think rendering to use `MarkdownRenderer` instead of plain text, aligning with Message component styling and functionality.

feat(tarko): unify think rendering with markdown renderer

---

multimodal/agent-tars/core/src/agent-tars.ts
multimodal/omni-tars/code-agent/tarko.config.ts
multimodal/omni-tars/gui-agent/tarko.config.ts
multimodal/omni-tars/mcp-agent/tarko.config.ts
multimodal/omni-tars/omni-agent/src/index.ts

Fixed grammatical error in `welcomTitle` across multiple agent configurations by changing "An multimodal AI agent" to "A multimodal AI agent".
Affected files:
- `@agent-tars/core` - Agent TARS configuration
- `@omni-tars/omni-agent` - Omni Agent configuration  
- `@omni-tars/code-agent` - Code Agent configuration
- `@omni-tars/gui-agent` - GUI Agent configuration
- `@omni-tars/mcp-agent` - MCP Agent configuration

chore(all): fix grammar typo

---

multimodal/tarko/pnpm-toolkit/src/utils/git.ts

Fixed `ptk release` failing due to secretlint pre-commit hook error by adding `--no-verify` flag to release commits in `@tarko/pnpm-toolkit`.
```
⚠ Running tasks for staged files...
❯ .lintstagedrc.mjs — 35 files
❯ * — 35 files
✖ secretlint --no-maskSecrets [ENOENT]
↓ **/*.{ts,tsx} — no files
↓ src/{main,preload}/**/*.{ts,tsx} — no…
↓ src/renderer/**/*.{ts,tsx} — no files
↓ Skipped because of errors from tasks.
✔ Reverting to original state because of er…
✔ Cleaning up temporary files...
✖ secretlint --no-maskSecrets failed without output (ENOENT).
```

chore(ptk): add `--no-verify` to release commits

---

multimodal/tarko/agent-web-ui/src/standalone/navbar/ModelSelector.tsx

Added hover tooltip functionality to the Navbar's Model ID display using the unified `getTooltipProps` configuration from PR #1300.
When hovering over the model selector in the navbar, users now see a tooltip showing "Model ID: [actual-model-id]" for better visibility of the full model identifier.

feat(tarko): add model id tooltip to navbar

---

multimodal/omni-tars/omni-agent/src/index.ts

Disable `enableScreenshotRenderStrategySwitch` and `renderGUIAction` in `@omni-tars/agent` GUI configuration.

chore(o-agent): disable gui agent screenshot switch and render

---

multimodal/omni-tars/omni-agent/src/index.ts
multimodal/tarko/agent-web-ui/src/standalone/workspace/renderers/browser-control/ScreenshotDisplay.tsx
multimodal/tarko/agent-web-ui/src/standalone/workspace/renderers/browser-control/useScreenshots.ts

Simplify `ScreenshotDisplay` state management and improve fallback logic for `afterAction` strategy. Replace complex `useState` with `useMemo` for better performance and cleaner code.
**Key Changes:**
- Replace `useState` with `useMemo` in `useScreenshots` hook for better performance
- Simplify screenshot fallback logic - when `afterActionImage` is not available in `afterAction` strategy, automatically fallback to `beforeActionImage`
- Remove redundant state management and complex effect dependencies
- Improve mouse cursor display logic
- Better error handling and logging

refactor(tarko): simplify screenshot display state management

---

multimodal/tarko/agent-server/src/utils/share.ts

Automatically append `?replay=1` parameter to share URLs in `ShareService.uploadShareHtml()` method.
This ensures that shared links automatically enable replay mode when accessed, improving user experience by directly showing the shared session content.

feat(tarko): auto-append `replay=1` to share URLs

---

multimodal/tarko/agent-web-ui/src/standalone/workspace/components/FullscreenModal.tsx
multimodal/tarko/agent-web-ui/src/standalone/workspace/components/ThrottledHtmlRenderer.tsx

Set default white background for HTML rendering mode to ensure proper display of model-generated HTML content.

feat(tarko): defaults background to white for html renderer

---

multimodal/tarko/agent-web-ui/src/standalone/chat/ChatPanel.tsx
multimodal/tarko/agent-web-ui/src/standalone/chat/hooks/useScrollToBottom.ts

Fixes auto-scroll behavior in Replay mode to follow all position changes, not just sequential playback.
Previously, auto-scroll only triggered when `currentEventIndex` increased during sequential playback. This caused poor UX when users jumped to different positions via timeline scrubbing or control buttons - the view wouldn't scroll to bottom.
Now auto-scroll triggers for any `currentEventIndex` change in Replay mode, ensuring users always see the latest content regardless of how they navigate.

feat(tarko): auto-scroll for replay position changes

---

multimodal/tarko/agent-web-ui/src/common/state/actions/eventProcessors/handlers/MessageHandler.ts
multimodal/tarko/agent-web-ui/src/common/state/actions/sessionActions.ts
multimodal/tarko/agent-web-ui/src/common/types/index.ts
multimodal/tarko/agent-web-ui/src/standalone/chat/ChatPanel.tsx
multimodal/tarko/agent-web-ui/src/standalone/home/WelcomePage.tsx

Improves chat session state management by implementing immediate user message display and server-side deduplication to eliminate UI flickering and confusing intermediate states.
**Problem solved:**
- User messages not appearing immediately on screen
- UI flickering between `EmptyState` and `SessionCreatingState` 
- Complex state logic causing poor UX when navigating from `WelcomePage`
**Solution:**
- Immediately show user messages in UI when sent
- Deduplicate server-side `user_message` events using `isLocalMessage` flag
- Simplify `ChatPanel` state logic by removing confusing conditions
- Streamline `WelcomePage` navigation flow

fix(tarko): improve session UI state management

---

multimodal/tarko/agent-web-ui/src/standalone/chat/hooks/useScrollToBottom.ts

Fixes auto-scroll issue introduced in #1412 where refreshing a multi-turn conversation causes frequent up-down scrolling during event stream reconstruction.
The problem was that the `useScrollToBottom` hook treated all user messages as "new" during refresh, triggering auto-scroll for each historical message. Now auto-scroll only occurs for the last user message with `isLocalMessage` flag (indicating it was just sent by the user).

fix(tarko): prevent auto-scroll on refresh for historical user messages

---

multimodal/CHANGELOG.md
multimodal/tarko/pnpm-toolkit/src/cli.ts

Fixed the CHANGELOG.md issue where many release notes were missing from version 0.3.0 onwards due to incorrect `--filter-scopes` configuration.

chore: fix changelog filter scopes and restore missing entries

---

multimodal/omni-tars/omni-agent/src/index.ts
multimodal/tarko/agent-web-ui/src/config/web-ui-config.ts
multimodal/tarko/agent-web-ui/src/standalone/workspace/renderers/BrowserControlRenderer.tsx
multimodal/tarko/agent-web-ui/src/standalone/workspace/renderers/browser-control/ScreenshotDisplay.tsx
multimodal/tarko/interface/src/web-ui-implementation.ts

By default, a browser shell appears when a GUIAgent screenshot is rendered, which is suitable for most browser usage scenarios:
However, in Computer Use or Full-Screen-based Browser Use, rendering the Browser Shell will cause it to overlap with the Navigation Bar in the screenshot. Starting with 0.3.0-beta.11, Tarko supports `guiAgent.renderBrowserShell`. Options to control:
**Default Behavior**
**`guiAgent.renderBrowserShell: false`**

feat(tarko): add `guiAgent.renderBrowserShell` option

---

multimodal/tarko/agent/src/tool-call-engine/PromptEngineeringToolCallEngine.ts

Fixes JSON parsing errors in PromptEngineeringToolCallEngine when models generate trailing content after tool call JSON.
Close: #1360
- Extract only the JSON portion before parsing in `completeToolCall`
- Apply same fix to `finalizeStreamProcessing` and `extractToolCalls` methods
- Handle cases where models generate extra content like `}\n}\n` after valid JSON
The issue occurred when models generated valid tool call JSON followed by extra content:
```json
{
"name": "edit_file",
"parameters": {
// ... valid parameters
}
}\n}\n
```
`JSON.parse()` would fail with "Unexpected non-whitespace character after JSON" error.
Added regex pattern to extract only the JSON portion:
```typescript
const jsonMatch = toolCallContent.match(/^\s*\{[\s\S]*?\}(?=\s*(?:\}|\n|$))/);
if (jsonMatch) { …
```

fix(tarko-agent): improve JSON parsing in PromptEngineeringToolCallEngine (close: #1360)

---

multimodal/tarko/agent-web-ui/src/standalone/app/Router/SessionRouter.tsx

Fixes duplicate user message rendering when entering existing conversations from homepage by preventing duplicate session loading calls in `SessionRouter`.
**Root Cause:** The `SessionRouter` `useEffect` was missing `activeSessionId` in its dependency array, causing it to call `setActiveSession` even when the session was already active. This led to duplicate event processing and message rendering.
**Solution:** Added `activeSessionId !== sessionId` check to prevent calling `setActiveSession` when the session is already active, eliminating the race condition that caused duplicate user messages.

fix(tarko): prevent duplicate session loading in SessionRouter

---

multimodal/tarko/agent-ui/src/standalone/chat/MessageInput/ChatInput.tsx
multimodal/tarko/agent-ui/src/standalone/navbar/ModelSelector.tsx

Fixed React key spread warning and hooks render consistency issue in `@tarko/agent-ui`.
**Issues resolved:**
- React warning: "A props object containing a 'key' prop is being spread into JSX" in `ChatInput.tsx`
- "Rendered more hooks than during the previous render" error in `ModelSelector.tsx`
**Changes:**
- Replaced `{...{ ['ke' + 'y']: 'value' }}` with direct `key="value"` prop in motion buttons
- Moved `handleModelChange` callback before conditional returns to ensure consistent hook order
**Logs:**
```
ChatInput.tsx:496 Warning: A props object containing a "key" prop is being spread into JSX:
let props = {key: someKey, initial: ..., animate: ..., exit: ..., transition: ..., whileTap: ..., whileHover: ..., type: ..., onClick: ..., disabled: ..., className: ..., title: ..., children: …
```

fix(tarko): resolve react key spread warning and hooks render issue

---

multimodal/tarko/agent-server/src/api/controllers/oneshot.ts
multimodal/tarko/agent-server/src/api/controllers/sessions.ts
multimodal/tarko/agent-server/src/api/controllers/system.ts
multimodal/tarko/agent-server/src/api/middleware/session-restore.ts
multimodal/tarko/agent-server/src/core/AgentSession.ts
multimodal/tarko/agent-server/src/server.ts
multimodal/tarko/agent-server/src/services/ShareService.ts
multimodal/tarko/agent-server/src/storage/DatabaseStorageProvider.ts
multimodal/tarko/agent-server/src/storage/FileStorageProvider.ts
multimodal/tarko/agent-server/src/storage/MemoryStorageProvider.ts
multimodal/tarko/agent-server/src/storage/SQLiteStorageProvider.ts
multimodal/tarko/agent-server/src/storage/compatibility.ts
multimodal/tarko/agent-server/src/storage/types.ts
multimodal/tarko/agent-server/src/utils/share.ts
multimodal/tarko/agent-server/tests/SQLiteStorageProvider.test.ts
multimodal/tarko/agent-ui/src/common/hooks/useSession.ts
multimodal/tarko/agent-ui/src/common/services/apiService.ts
multimodal/tarko/agent-ui/src/common/state/actions/eventProcessors/handlers/AgentRunHandler.ts
multimodal/tarko/agent-ui/src/common/state/actions/sessionActions.ts
multimodal/tarko/agent-ui/src/common/state/atoms/session.ts
multimodal/tarko/agent-ui/src/common/state/atoms/ui.ts
multimodal/tarko/agent-ui/src/common/types/env.d.ts
multimodal/tarko/agent-ui/src/common/types/index.ts
multimodal/tarko/agent-ui/src/common/utils/modelUtils.ts
multimodal/tarko/agent-ui/src/standalone/navbar/AboutModal.tsx
multimodal/tarko/agent-ui/src/standalone/sidebar/ChatSession.tsx
multimodal/tarko/agent-ui/src/standalone/sidebar/SessionItem.tsx
multimodal/tarko/interface/src/server.ts

To make Agent UI Builder's API design **_cleaner_** at https://github.com/bytedance/UI-TARS-desktop/pull/1436, we renamed "SessionItemInfo" to "SessionInfo" throughout the multimodal directory to improve naming consistency. We also updated the comment to clarify that "SessionMetadata" is just a field of "SessionInfo".

refactor(tarko): rename `SessionItemInfo` to `SessionInfo`

---

.changeset/olive-mangos-leave.md
.gitignore
packages/agent-infra/create-new-mcp/CHANGELOG.md
packages/agent-infra/create-new-mcp/package.json
packages/agent-infra/create-new-mcp/template-default/package.json
packages/agent-infra/create-new-mcp/template-default/server.json
packages/agent-infra/mcp-client/CHANGELOG.md
packages/agent-infra/mcp-client/package.json
packages/agent-infra/mcp-servers/browser/CHANGELOG.md
packages/agent-infra/mcp-servers/browser/package.json
packages/agent-infra/mcp-servers/browser/server.json
packages/agent-infra/mcp-servers/commands/CHANGELOG.md
packages/agent-infra/mcp-servers/commands/package.json
packages/agent-infra/mcp-servers/commands/server.json
packages/agent-infra/mcp-servers/filesystem/CHANGELOG.md
packages/agent-infra/mcp-servers/filesystem/package.json
packages/agent-infra/mcp-servers/filesystem/server.json
packages/agent-infra/mcp-servers/search/CHANGELOG.md
packages/agent-infra/mcp-servers/search/package.json
packages/agent-infra/mcp-servers/search/server.json
packages/agent-infra/mcp-shared/CHANGELOG.md
packages/agent-infra/mcp-shared/package.json

- **feat(mcp-servers): support mcp offical registry**
- **chore: patch**
https://blog.modelcontextprotocol.io/posts/2025-09-08-mcp-registry-preview/

feat(mcp-servers): support mcp offical registry

---

multimodal/tarko/agent-ui/src/sdk/code-editor/CodeEditor.css
multimodal/tarko/agent-ui/src/sdk/code-editor/CodeEditor.tsx
multimodal/tarko/agent-ui/src/sdk/code-editor/CodeEditorHeader.tsx
multimodal/tarko/agent-ui/src/sdk/code-editor/DiffViewer.tsx
multimodal/tarko/agent-ui/src/sdk/code-editor/MonacoCodeEditor.tsx
multimodal/tarko/agent-ui/src/standalone/workspace/renderers/FileResultRenderer.tsx
multimodal/tarko/agent-ui/src/standalone/workspace/renderers/ScriptResultRenderer.tsx
multimodal/tarko/agent-ui/src/standalone/workspace/renderers/TabbedFilesRenderer.tsx
multimodal/tarko/agent-ui/src/standalone/workspace/utils/codeUtils.ts

Removed redundant TypeScript badge from  component since filename already indicates file type.
Changes:
- Removed  prop from  interface
- Removed language badge rendering logic
- Cleaned up unused CSS for

fix(tarko): remove language badge from code renderer header

---

multimodal/tarko/model-provider/src/llm-client.ts
multimodal/tarko/model-provider/tests/llm-client.test.ts

Reverts the breaking change from PR #1489 that added `'openai'` and `'anthropic'` to `NATIVE_PROVIDERS`. This change broke providers like `volcengine` that use `baseProvider: 'openai'` and need `extendModelList()` to register their custom models (e.g., `ep-20250613182556-7z8pl`).
**Root Cause**: High-level providers like `volcengine` use OpenAI-compatible APIs but with custom model IDs. They rely on `extendModelList()` to register these models with the underlying `@tarko/llm-client`. When `'openai'` was added to `NATIVE_PROVIDERS`, these providers were incorrectly treated as native and their models weren't extended, causing "Invalid 'model' field" errors.
**Technical Chain**:
1. `volcengine` provider → `baseProvider: 'openai'` → custom model `ep-20250613182556-7z8pl`
2. …

fix(model-provider): native providers regression issue

---

multimodal/tarko/mcp-agent-interface/src/index.ts
multimodal/tarko/mcp-agent/src/mcp-agent.ts
multimodal/tarko/mcp-agent/src/mcp-client-v2.ts

Adjust `defaultConnectionTimeout` from 180 to 60 seconds to address timeout issues in MCP agent connections.
Updated timeout values in:
- `@tarko/mcp-agent` - MCPAgent initialization
- `@tarko/mcp-agent` - MCPClientV2 constructor
- `@tarko/mcp-agent-interface` - interface documentation

feat(tarko-mcp-agent): adjust defaultConnectionTimeout from 180 to 60 seconds

---

multimodal/tarko/agent-ui/src/standalone/navbar/ModelSelector.tsx

Disable `ModelSelector` during agent execution to prevent model switching while agent is processing, consistent with share mode behavior.

feat(tarko-agent-ui): disable model selector during agent run

---

multimodal/package.json
multimodal/tarko/pnpm-toolkit/src/cli.ts
multimodal/tarko/pnpm-toolkit/src/commands/release.ts
multimodal/tarko/pnpm-toolkit/src/types.ts

Adds `--canary` flag support to `pnpm-toolkit` release command for automated canary releases.
**Usage:**
```bash
pnpm run release:canary
ptk release --canary --push-tag --build --ignore-scripts
```
**Example output:**
`0.3.0-beta.11-canary-404367f44-20250916065645`

ci(pnpm-toolkit): add canary release support

---

multimodal/tarko/agent-server-next/src/services/session/AgentSession.ts

feat(tarko-agent-server-next): add initial events for agent when change model

---

multimodal/websites/docs/docs/en/showcase/index.mdx
multimodal/websites/docs/docs/zh/showcase/index.mdx

Removed duplicate `# Showcase` header from showcase mdx files that was causing unexpected header display. The `ShowcaseHeader` component already renders the title, making the mdx header redundant.

docs: remove duplicate header

---

multimodal/gui-agent/action-parser/src/ActionParserHelper.ts
multimodal/gui-agent/action-parser/src/FomatParsers.ts
multimodal/gui-agent/action-parser/test/coordinates.test.ts

This PR introduces significant refactoring and optimization to the `ActionParserHelper` class, including the following improvements:
1. **parseCoordinates: renaming and logic optimization**
- Renamed the `standardlizeCoordinates` method to `parseCoordinates`
- Optimized coordinate parsing logic to support more formats:
- Supports `100, 200` and `100 200` formats (no longer throws errors)
- Extended bracket matching patterns to support `<point></point>` tags
- Used a more flexible splitting rule `/[,\\s]+/` to handle comma and space separators
- Throws clear error messages when invalid numbers are parsed
- Provides more detailed debug log output
2. **Added XML Object Standardization Methods**
- Added the `standardizeGUIActionsFromXMLObject` method
- Added the …

refactor(action-parser): refactor ActionParserHelper and optimizing coordinate parsing

---

multimodal/omni-tars/omni-agent/tarko.config.ts
multimodal/tarko/agent-server-next/examples/bootstrap.ts
multimodal/tarko/agent-server-next/src/controllers/sessions.ts
multimodal/tarko/agent-server-next/src/controllers/share.ts
multimodal/tarko/agent-server-next/src/middlewares/access-log.ts
multimodal/tarko/agent-server-next/src/middlewares/session-restore.ts
multimodal/tarko/agent-server-next/src/routes/sessions.ts
multimodal/tarko/agent-server-next/src/services/ShareService.ts
multimodal/tarko/agent-server-next/src/services/sandbox/SandboxScheduler.ts
multimodal/tarko/agent-server-next/src/services/session/AgentSession.ts
multimodal/tarko/agent-server-next/src/services/session/AgentSessionFactory.ts
multimodal/tarko/agent-server-next/src/types.ts
multimodal/tarko/agent-server-next/src/utils/index.ts
multimodal/tarko/agent-server-next/src/utils/logger.ts
multimodal/tarko/agent-server-next/src/utils/model-utils.ts
multimodal/tarko/agent-server-next/src/utils/slug-generator.ts
multimodal/tarko/agent-server-next/src/utils/url.ts
multimodal/tarko/agent-server-next/src/utils/webui/config.ts
multimodal/tarko/agent-server-next/src/utils/webui/index.ts
multimodal/tarko/agent-server/rslib.config.ts
multimodal/tarko/agent-server/src/services/ShareService.ts
multimodal/tarko/agent-ui-builder/README.md
multimodal/tarko/agent-ui-builder/src/builder.ts
multimodal/tarko/agent-ui-builder/tests/builder.test.ts
multimodal/tarko/agent-ui-cli/src/core.ts
multimodal/tarko/interface/src/web-ui-implementation.ts

1. agent-ui-builder supports obtaining remote html
2. fixed the issue that agent-server-next can't share  seesion
3. remove logger proxy

feat(agent-server): support remote static html and add share for server-next

---

multimodal/tarko/agent-ui/src/standalone/workspace/renderers/BrowserResultRenderer.tsx

Removed redundant URL actions bar from `BrowserResultRenderer` since `BrowserShell` already provides URL display functionality in its address bar.

fix(tarko-agent-ui): remove duplicate url actions bar from browser renderer

---

multimodal/websites/docs/docs/en/_nav.json
multimodal/websites/docs/docs/en/blog/index.mdx
multimodal/websites/docs/docs/zh/_nav.json
multimodal/websites/docs/docs/zh/blog/index.mdx
multimodal/websites/docs/src/components/BlogCard.tsx
multimodal/websites/docs/src/components/BlogIndex.css
multimodal/websites/docs/src/components/BlogIndex.tsx
multimodal/websites/docs/src/components/index.ts

Added a minimal and elegant Blog Index Page to replace the direct link to a specific blog post in the navigation. This enables better blog management and user experience.

docs(agent-tars): add blog index page

---

multimodal/tarko/agent-cli/src/core/options.ts
multimodal/tarko/agent-cli/tests/config-builder.test.ts

Adds support for `--model.displayName` CLI option in `@tarko/agent-cli`.
The `AgentModel` interface already includes the `displayName?: string` field, but the CLI was missing the corresponding option to set it from command line.

feat(tarko-agent-cli): add `--model.displayName` option support

---

multimodal/websites/tarko/docs/en/examples/getting-started.mdx

Fixed incorrect `AgentOptions` property names in examples documentation to match actual source code interface.
**Problem**: The getting-started examples used deprecated property names:
- `systemPrompt` instead of `instructions`
- `modelProvider` instead of `model`
- Included unnecessary `description` property
**Solution**: Updated all agent configurations in `/examples/getting-started.mdx` to use correct property names from `multimodal/tarko/agent-interface/src/agent-options.ts`.

docs(tarko): fix agent options in examples

---

multimodal/websites/tarko/docs/en/guide/_meta.json
multimodal/websites/tarko/docs/en/guide/cli/_meta.json
multimodal/websites/tarko/docs/en/guide/cli/built-in-agents.mdx
multimodal/websites/tarko/docs/en/guide/cli/commands.mdx
multimodal/websites/tarko/docs/en/guide/cli/configuration.mdx
multimodal/websites/tarko/docs/en/guide/cli/overview.mdx
multimodal/websites/tarko/docs/en/guide/deployment/cli.mdx
multimodal/websites/tarko/docs/zh/guide/_meta.json
multimodal/websites/tarko/docs/zh/guide/cli/_meta.json
multimodal/websites/tarko/docs/zh/guide/cli/built-in-agents.mdx
multimodal/websites/tarko/docs/zh/guide/cli/commands.mdx
multimodal/websites/tarko/docs/zh/guide/cli/configuration.mdx
multimodal/websites/tarko/docs/zh/guide/cli/overview.mdx
multimodal/websites/tarko/docs/zh/guide/deployment/cli.mdx

Restructured CLI documentation into proper sections with clear separation of concerns:
**New Structure:**
- `/guide/cli/` - Complete CLI reference aligned with `@tarko/agent-cli` README
- `/guide/deployment/cli.mdx` - Production deployment strategies only

docs(tarko): restructure cli documentation into separate sections

---

multimodal/tarko/agent-ui/src/config/web-ui-config.ts
multimodal/tarko/agent-ui/src/standalone/app/App.tsx
multimodal/tarko/interface/src/web-ui-implementation.ts

Adds `webui.layout.enableSidebar` configuration option to control sidebar visibility in the web UI. When set to `false`, the sidebar will be hidden across all views (home, session, and replay mode).

feat(tarko-agent-ui): add `webui.layout.enableSidebar` config

---

multimodal/tarko/agent-ui/src/config/web-ui-config.ts
multimodal/tarko/agent-ui/src/standalone/app/App.tsx
multimodal/tarko/interface/src/web-ui-implementation.ts

Add `webui.layout.enableHome` configuration option to control home route registration. When set to `false`, the home route "/" will not be registered, allowing for custom routing behavior.

feat(tarko-agent-ui): add `webui.layout.enableHome` config

---

multimodal/omni-tars/core/src/environments/prompt_t5.ts
multimodal/omni-tars/core/src/index.ts
multimodal/omni-tars/core/src/types.ts
multimodal/omni-tars/gui-agent/src/GUIAgentToolCallEngine.ts
multimodal/omni-tars/gui-agent/src/GuiToolCallEngineProvider.ts
multimodal/omni-tars/omni-agent/src/index.ts
multimodal/omni-tars/omni-agent/src/options.ts
multimodal/tarko/agent-server-next/examples/bootstrap.ts
multimodal/tarko/agent-server-next/package.json
multimodal/tarko/agent-server-next/src/controllers/sessions.ts
multimodal/tarko/agent-server-next/src/controllers/system.ts
multimodal/tarko/agent-server-next/src/routes/sessions.ts
multimodal/tarko/agent-server-next/src/services/session/AgentSession.ts
multimodal/tarko/agent-server-next/src/utils/logger.ts
multimodal/tarko/agent-server/src/core/AgentSession.ts

1. add runtime settings api in agent-server-next,   update related AgentSession code and server routes
2. support agent mode in omni agent;  update system prompt for gui-only scenario

feat(tarko): add runtime settings api in server-next

---

multimodal/tarko/agent-ui/src/standalone/workspace/renderers/ImageRenderer.tsx

Removed excessive background, padding, border, and shadow styling from `ImageRenderer` container that made it look bulky and ugly. The image now displays cleanly without unnecessary visual noise.

fix(tarko-agent-ui): remove ugly container from ImageRenderer

---

multimodal/omni-tars/core/src/AgentComposer.ts
multimodal/omni-tars/mcp-agent/src/McpAgentPlugin.ts
multimodal/omni-tars/omni-agent/src/index.ts
multimodal/omni-tars/omni-agent/src/options.ts
multimodal/tarko/agent-server-next/examples/bootstrap.ts
multimodal/tarko/agent-server-next/src/middlewares/session-restore.ts
multimodal/tarko/agent-server-next/src/services/session/AgentSession.ts

1. update agent mode config structure

feat(omni-agent): update agent mode config structure

---

multimodal/omni-tars/omni-agent/src/index.ts
multimodal/tarko/agent-server/src/utils/webui/config.ts
multimodal/tarko/agent-ui/src/standalone/app/App.tsx
multimodal/tarko/agent-ui/src/standalone/components/ThemeToggle.tsx
multimodal/tarko/agent-ui/src/standalone/components/index.ts
multimodal/tarko/agent-ui/src/standalone/home/WelcomeCards.tsx
multimodal/tarko/agent-ui/src/standalone/home/WelcomePage.tsx
multimodal/tarko/agent-ui/src/standalone/navbar/Navbar.tsx
multimodal/tarko/interface/src/web-ui-implementation.ts
welcomeCards-examples.json
welcomeCards-simple.json
welcomeCards-single-category.json

Added `welcomeCards` feature to support configurable cards on the homepage below `welcomePrompts`. Cards support title, prompt, avatar, category, and agentOptions fields with categorized display and tab navigation when multiple categories exist.

feat(tarko-agent-ui): welcome cards

---

multimodal/omni-tars/gui-agent/package.json
multimodal/omni-tars/gui-agent/src/GuiAgentPlugin.ts
multimodal/omni-tars/omni-agent/tarko.config.ts
multimodal/pnpm-lock.yaml

Use ImageCompressor to compress gui screenshots into webp format to reduce events size: 
```bash
compression stat:  {
originalSize: '79.09 KB',
compressedSize: '24.67 KB',
compressionRatio: '68.81% reduction'
}
```

feat(omni-agent): compress images for gui screenshot

---

multimodal/omni-tars/omni-agent/src/index.ts
multimodal/tarko/agent-ui/src/standalone/home/WelcomeCards.tsx
multimodal/tarko/interface/src/web-ui-implementation.ts

Fixed an issue where clicking `welcomeCards` would always send a user message, even when no `prompt` was configured. Now only sends a message when `card.prompt` exists.
**Before**: All cards triggered message sending regardless of prompt configuration  
**After**: Only cards with configured prompts trigger message sending

fix(tarko-agent-ui): make welcome cards prompt optional

---

multimodal/omni-tars/gui-agent/src/GuiAgentPlugin.ts
multimodal/tarko/agent-server/src/api/controllers/sessions.ts
multimodal/tarko/agent-server/src/core/AgentSession.ts
multimodal/tarko/agent-ui/src/common/services/apiService.ts
multimodal/tarko/agent-ui/src/common/state/actions/eventProcessors/handlers/SystemHandler.ts
multimodal/tarko/agent-ui/src/common/state/actions/sessionActions.ts
multimodal/tarko/agent-ui/src/standalone/home/CreatingPage.tsx

Resolves session initialization event persistence issue where events generated during `agent.initialize()` were stored in backend but not returned to frontend, causing them to only appear after page refresh.

feat(tarko-agent-server, agent-ui): return initialization events from session create

---

multimodal/omni-tars/gui-agent/package.json
multimodal/omni-tars/gui-agent/src/GuiAgentPlugin.ts
multimodal/omni-tars/gui-agent/src/utils/ImageCompressor.ts
multimodal/omni-tars/gui-agent/src/utils/index.ts
multimodal/pnpm-lock.yaml

Newly implemented images compressor, solves the problem of external dependence on cwebp-bin errors during online deployment：
compress ratio got to be higher:
```bash
[O-GUIAgent] emitScreenshotEvent compression stat:  {
originalSize: '1.05 MB',
compressedSize: '149.33 KB',
compressionRatio: '86.15% reduction'
}
```

feat(omni-agent): fix img compressor dependency issues

---

multimodal/tarko/agent-ui/src/common/state/actions/connectionActions.ts
multimodal/tarko/agent-ui/src/standalone/app/App.tsx

Fixed health check polling issues that caused unnecessary API calls and UI flickering. The problem was in `App.tsx` where `connectionStatus.connected` dependency triggered re-initialization on every connection status change, leading to cascading API calls:
1. Health check runs every 30s → calls `getAgentOptions()` → changes connection status
2. App.tsx `useEffect` re-runs → calls `loadSessions()` → triggers more API calls  
3. Results in brief "disconnected" state flashing before returning to normal
**Changes:**
- Removed `connectionStatus.connected` dependency from App.tsx useEffect
- Modified connection monitoring to load sessions only on initial connection/reconnection
- Skip sessions reload during periodic health checks when already connected
- Prevents unnecessary API call chains …

fix(tarko-agent-ui): optimize health check polling to prevent unnecessary API calls

---

multimodal/tarko/agent-server/src/core/AgentSession.ts

Removed redundant `console.log('Receive event', event)` statement in `AgentSession.createEventHandler()` that was causing performance overhead for streaming events. The log was being called for every event in the stream, creating unnecessary I/O operations and cluttering output.

fix(tarko-agent-server): remove redundant event logging

---

multimodal/tarko/agent-ui/src/standalone/home/CreatingPage.tsx
multimodal/tarko/agent-ui/src/standalone/home/WelcomePage.tsx

Fixed multimodal content being serialized as text when navigating from home page, preventing context overflow when images are pasted and sent from the Welcome Page.

fix(tarko-agent-ui): preserve multimodal content format when navigating from home page
