README.md

[Rendered](https://github.com/bytedance/UI-TARS-desktop/tree/chore/tweak-readme)

chore: tweak readme

---

package.json
pnpm-lock.yaml
src/main/agent/execute.test.ts
src/main/agent/execute.ts

Support dragging in any direction.

fix(execute): drag not work

---

.github/workflows/release.yml
README.md
build/entitlements.mac.plist
forge.config.ts
package.json
pnpm-lock.yaml
src/main/agent/execute.ts
src/main/utils/systemPermissions.ts

feat: add default osx sign

---

src/renderer/src/components/ThoughtChain/index.tsx

style(ui): add action content

---

README.md

docs: note dev

---

packages/visualizer/src/component/sidebar.less
packages/visualizer/src/component/sidebar.tsx

typo(visualizer): fix typo to separator

---

packages/shared/package.json
src/main/agent/execute.ts
src/main/agent/index.ts
src/main/agent/llm/base.ts
src/main/agent/llm/ui-tars.ts
src/main/store/create.ts
src/renderer/src/components/Header/index.tsx

- **chore: call_user action**
- **fix(agent): abort not break immediately**
- **fix(ui): disable logo dragged**

fix(agent): abort not break immediately

---

src/main/main.ts
src/main/store/types.ts
src/main/window/index.ts
src/renderer/src/pages/settings/index.tsx

- fix(settings): create window twice not work
- feat(vlmProvider): vLLM support

feat(vlmProvider): vLLM support

---

.github/workflows/test.yml
packages/shared/src/types/index.ts
src/main/agent/index.ts
src/main/store/ScreenMarker.ts
src/main/store/create.ts
src/main/store/runAgent.ts
src/main/store/types.ts
src/renderer/src/components/ChatInput/index.tsx
src/renderer/src/components/RunMessages/index.tsx
src/renderer/src/components/ThoughtChain/index.tsx
src/renderer/src/hooks/useRunAgent.ts
src/renderer/src/pages/home/index.tsx
src/renderer/src/utils/message.ts

- **feat(hitl): add human-in-the-loop, return control to human**
https://github.com/user-attachments/assets/cce6f314-31d0-444e-b3f1-3c9ea12f8a5d

feat(hitl): add human-in-the-loop, return control to human

---

rfcs/README.md
rfcs/template.md

See rendered:
- [UI-TARS-desktop RFCs](https://github.com/bytedance/UI-TARS-desktop/blob/chore/init-rfcs/rfcs/README.md)
- [UI-TARS-desktop RFC Template](https://github.com/bytedance/UI-TARS-desktop/blob/chore/init-rfcs/rfcs/template.md)

docs: init rfc process and template

---

package.json
packages/utio/package.json
packages/utio/src/index.ts
packages/utio/src/types.ts
packages/utio/tsconfig.json
packages/utio/tsup.config.ts
pnpm-lock.yaml
src/main/agent/index.ts
src/main/main.ts
src/main/services/utio.ts
src/main/store/types.ts
src/main/window/index.ts
src/preload/index.d.ts
src/preload/index.ts
src/renderer/src/components/ChatInput/index.tsx
src/renderer/src/pages/settings/index.tsx
src/renderer/src/typings/preload.d.ts

Implement **UTIO** (**U**I-**T**ARS **I**nsights and **O**bservation).

feat: UTIO (UI-TARS Insights and Observation)

---

src/main/store/create.ts
src/main/store/runAgent.ts
src/main/window/ScreenMarker.ts
src/renderer/src/hooks/useScreenRecord.ts

fix(screenMarker): action text screen marker not show for vlm

---

src/main/agent/index.ts
src/main/main.ts
src/main/window/index.ts
src/preload/index.ts
src/renderer/index.html
src/renderer/src/components/ChatInput/index.tsx
src/renderer/src/main.tsx

This pull request includes several changes to improve the application's window management, logging, and user interface. The most important changes include updating the app lifecycle events, modifying the main and settings window behaviors, and adding a loading spinner to the UI.
* [`src/main/main.ts`](diffhunk://#diff-7adaa52a2eacb085ba5e07e6683a61fb3601547dc00b51fd50fbaf685e13fe96L159-R181): Updated app lifecycle events to handle window closing, quitting, and activation more effectively. This includes logging events and ensuring windows are properly managed on different platforms.
* [`src/main/window/index.ts`](diffhunk://#diff-b481040ee59e5988fa7eabea6a5517c1ab20b25be9217a69dde83fc4177719a7L28-R43): Modified the behavior of the main and settings windows to hide instead of close on macOS …

fix(windows): windows fails to handle events when the dock bar is opened after being closed

---

package.json
src/main/main.ts

- **fix: not use system picker**
- **chore: version**

fix(share): not use system picker

---

packages/operators/nut-js/src/index.ts
src/main/agent/operator.ts

Close https://github.com/bytedance/UI-TARS/issues/62

fix(operator): macos cannot type

---

examples/operator-browserbase/README.md
packages/action-parser/README.md
packages/action-parser/src/actionParser.ts
packages/action-parser/test/actionParser.test.ts
packages/sdk/src/GUIAgent.ts
packages/sdk/src/Model.ts
packages/sdk/src/constants.ts
packages/sdk/src/types.ts
packages/sdk/src/utils.ts
packages/sdk/tests/GUIAgent.test.ts
packages/shared/src/utils/coords.ts
src/main/utils/coords.test.ts
src/main/utils/coords.ts

- **docs: browserbase fork from**
- **feat: support factors for different model coordinate systems**

refactor: sdk replace FACTOR to FACTORS(no breaking)

---

CONTRIBUTING.md

Close https://github.com/bytedance/UI-TARS-desktop/issues/168

docs: contribute for building

---

README.md

chore: fix logo url

---

apps/omega/src/renderer/src/components/CanvasPanel/EventPlayer/PlayerControls.tsx
apps/omega/src/renderer/src/components/CanvasPanel/EventPlayer/index.tsx
apps/omega/src/renderer/src/components/ChatUI/index.tsx

fix: clear the canvas display when deleting the history records

fix: clear the canvas display when deleting the history records

---

apps/omega/src/renderer/src/components/ChatUI/BeforeInputContainer.tsx
apps/omega/src/renderer/src/components/ChatUI/Replay.tsx

https://github.com/user-attachments/assets/d4ccb0cb-8ec1-4618-b049-c66fc050000e

fix: the replay page supports pause and resume

---

apps/omega/src/main/mcp/client.ts

fix: handle default exports correctly in dynamic imports

fix: handle default exports correctly in dynamic imports

---

apps/omega/src/main/utils/normalizeOmegaData.ts

fix: resolve path undefined error in normalizeOmegaData

fix: resolve path undefined error in normalizeOmegaData

---

.github/workflows/e2e.yml
.github/workflows/test.yml
package.json
turbo.json

- **chore: ci add bootstrap**
- **chore: bootstrap**

chore: ci speed

---

apps/omega/src/renderer/src/components/LeftSidebar/Settings/useAppSettings.ts

form validation for api version

fix: form validation

---

apps/omega/package.json
packages/agent-infra/browser-use/assets/buildDomTree.js
packages/agent-infra/browser-use/src/browser/page.ts
packages/agent-infra/browser-use/src/browser/utils.ts
packages/agent-infra/mcp-servers/browser/src/server.ts

- **fix(mcp): browser navigate waitForPageAndFramesLoad**
- **chore: publish mac before build reporter**
- **fix: browser bugs**
- **chore: prepare**

fix: browser navigator

---

apps/agent-tars/docs/quick-start.md

Fix the typo changing "Thead" to "Thread"

docs: small fix for the typo

---

apps/agent-tars/src/renderer/src/components/LeftSidebar/index.module.scss

refactor(agent-tars): title style

---

apps/agent-tars/src/renderer/src/index.scss

| Before |After |
| --- | --- |
| <img width="426" alt="image" src="https://github.com/user-attachments/assets/09217510-433a-4f4e-8c62-24c1b162f5b0" />| <img width="427" alt="image" src="https://github.com/user-attachments/assets/78514222-a502-4056-b064-f28019e11e1b" />|

refactor(agent-tars): enhance markdown font rendering

---

apps/agent-tars/src/renderer/src/components/ChatUI/MenuHeader.tsx

refactor(agent-tars): increase logo size

---

apps/agent-tars/src/renderer/src/components/LeftSidebar/Settings/ModelSettingsTab.tsx

fix(agent-tars): custom model name should keep state （close: #285）

---

apps/agent-tars/src/main/ipcRoutes/llm.ts
apps/agent-tars/src/main/llmProvider/index.ts

fix(agent-tars): cannot catch error within `askLLMTool ` （close: #285）

---

apps/agent-tars/src/main/ipcRoutes/settings.ts
apps/agent-tars/src/main/llmProvider/ProviderFactory.ts

fix(agent-tars): set `azure openai` but sent `openai` request (close: #290)

---

apps/agent-tars/src/main/index.ts
apps/agent-tars/src/main/utils/errorReporter.ts
apps/agent-tars/src/renderer/src/App.tsx
apps/agent-tars/src/renderer/src/services/errorHandlerService.ts
apps/agent-tars/tsconfig.web.json

feat(agent-tars): display all main errors (close: #240, #248)

---

apps/agent-tars/src/main/ipcRoutes/action.ts
apps/agent-tars/src/renderer/mock/ipc.ts
apps/agent-tars/src/renderer/src/agent/Executor/index.ts

Sharing page crash!
- **fix(agent-tars): share error**
- **chore: result log**
- **chore: highlight browser**

fix(agent-tars): share bugs

---

apps/agent-tars/src/renderer/src/agent/AgentFlow.ts
apps/agent-tars/src/renderer/src/agent/EventManager.ts
apps/agent-tars/src/renderer/src/agent/mockEvents.ts
apps/agent-tars/src/renderer/src/components/AgentFlowMessage/EventRenderer.tsx
apps/agent-tars/src/renderer/src/components/AgentFlowMessage/events/UserInteruption.tsx
apps/agent-tars/src/renderer/src/type/event.ts
packages/agent-infra/mcp-servers/commands/TODO.md
packages/agent-infra/search/browser-search/examples/github-search.ts
packages/ui-tars/sdk/src/Model.ts
packages/ui-tars/sdk/src/constants.ts
packages/ui-tars/sdk/src/utils.test.ts
packages/ui-tars/sdk/src/utils.ts
packages/ui-tars/sdk/tests/GUIAgent.test.ts

fix: typos

---

.github/ISSUE_TEMPLATE/bug_report_agent_tars_desktop.yml
.github/ISSUE_TEMPLATE/bug_report_ui_tars_desktop.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_requrest.yml

chore: add issue templates

---

apps/agent-tars/dev-app-update.yml
apps/agent-tars/package.json
apps/agent-tars/src/main/index.ts
apps/agent-tars/src/main/utils/updateApp.ts
apps/agent-tars/src/renderer/mock/ipc.ts
packages/common/electron-build/package.json
pnpm-lock.yaml

- **fix(agent-tars): electron updater**
- **chore: add ipc mock**

fix(agent-tars): app updater not work

---

apps/agent-tars/src/renderer/src/hooks/useFileSystemSettings.ts

fix(agent-tars): report white screen (close: #347)

---

apps/agent-tars/src/main/utils/logger.ts

feat(agent-tars): log file rotation (close: #360)

---

apps/agent-tars/src/renderer/src/agent/Aware.ts

- Close: #273 
- Close: #368 
- Close: #374

fix(agent-tars): probabilistic plan anomaly on gpt-4o (Closes #273)

---

apps/agent-tars/src/main/index.ts
apps/agent-tars/src/main/utils/links.ts

fix(agent-tars): should not open external links within app (close: #379)

---

apps/agent-tars/src/main/index.ts
apps/agent-tars/src/main/menu.ts
apps/agent-tars/src/main/utils/updateApp.ts

feat(agent-tars): add about and manually check updates menu (close: #349)

---

apps/agent-tars/src/renderer/src/components/CanvasPanel/EventPlayer/index.module.scss
apps/agent-tars/src/renderer/src/components/CanvasPanel/EventPlayer/index.tsx
apps/agent-tars/src/renderer/src/components/LeftSidebar/index.module.scss

- Add app-region drag capabilities to EventPlayer header
- Update LeftSidebar to support app dragging when collapsed
- Apply no-drag to interactive elements (close buttons, etc.)
- Create new EventPlayer SCSS module for drag styling
- close: #314
Video:
https://github.com/user-attachments/assets/0b5d855e-c497-4fcc-8a15-a463e8f1948b

fix(ui): implement app drag functionality :bug:

---

apps/agent-tars/src/main/utils/logger.ts

fix(agent-tars): log sequence (close: #361)

---

apps/agent-tars/src/renderer/src/components/LeftSidebar/SessionList/index.tsx
apps/agent-tars/src/renderer/src/hooks/useChatSession.ts

- Close: #356 
- Related to: #423

fix(agent-tars): new session should be added to the top (close: #356)

---

apps/agent-tars/src/main/customTools/search.ts
apps/agent-tars/src/main/ipcRoutes/action.ts
apps/agent-tars/src/main/ipcRoutes/llm.ts
apps/agent-tars/src/main/ipcRoutes/search.ts
apps/agent-tars/src/main/store/setting.ts
apps/agent-tars/src/renderer/src/components/CanvasPanel/EventPlayer/platform/SearchPanel.tsx
apps/agent-tars/src/renderer/src/components/LeftSidebar/Settings/SearchSettingsTab.tsx
apps/agent-tars/src/renderer/src/components/LeftSidebar/Settings/SettingsModal.tsx
apps/agent-tars/src/renderer/src/components/LeftSidebar/Settings/searchUtils.tsx
apps/agent-tars/src/renderer/src/components/LeftSidebar/Settings/useAppSettings.ts
packages/agent-infra/search/browser-search/examples/bing-search.ts
packages/agent-infra/search/browser-search/examples/google-search.ts
packages/agent-infra/search/browser-search/src/browser-search.ts
packages/agent-infra/search/browser-search/src/engines/baidu-engine.ts
packages/agent-infra/search/browser-search/src/engines/bing-engine.ts
packages/agent-infra/search/browser-search/src/engines/get-search-engine.ts
packages/agent-infra/search/browser-search/src/engines/google-engine.ts
packages/agent-infra/search/browser-search/src/types.ts
packages/agent-infra/search/browser-search/src/utils/misc.ts
packages/agent-infra/search/search/package.json
packages/agent-infra/search/search/src/index.ts
packages/agent-infra/shared/src/agent-tars-types/index.ts
packages/agent-infra/shared/src/agent-tars-types/search.ts
packages/agent-infra/shared/src/agent-tars-types/setting.ts
pnpm-lock.yaml

> [!IMPORTANT]
> This PR is related to multiple related but independent issues. Please DO NOT merge them in a squashed commit.
There are a lot of DuckDuckgo-related search issues here:
- #419 
- #385 
- #365 
This PR introduces **Local Browser Search** and turns it on by default.
https://github.com/user-attachments/assets/d86d86c0-c243-458c-a504-4583d0d39450
---
- Close: #436
When `needVisitedUrls` option is `false`, it means that the target page will not be opened for content extraction, but content is empty at this time. This MR adds the function of extracting snippets to browser search. Even if `needVisitedUrls` is `false`, the key information of the page (date, summary, etc.) can be extracted.
``` diff
{
"title": "GUI Agents with Foundation Models: A Comprehensive ...",
"url": …
```

feat: local browser search (close: #333)

---

apps/agent-tars/src/main/customTools/search.ts
apps/agent-tars/src/main/ipcRoutes/search.ts
apps/agent-tars/src/main/store/setting.ts
apps/agent-tars/src/renderer/src/components/CanvasPanel/EventPlayer/platform/SearchPanel.tsx
packages/agent-infra/shared/src/agent-tars-types/search.ts

Introduced at https://github.com/bytedance/UI-TARS-desktop/pull/414

chore(agent-tars): fix ci type check error and set default search engine to local browser search

---

apps/agent-tars/src/renderer/src/components/LeftSidebar/Settings/SettingsModal.tsx

Ref: https://github.com/agent-infra/agent-tars-website/pull/10

chore(agent-tars): add mcp config help link

---

.github/ISSUE_TEMPLATE/bug_report_agent_tars_desktop.yml
.github/ISSUE_TEMPLATE/feature_requrest.yml

1. Hoist `Local Browser Search` for issues;
2. Hoist `Agent TARS` for feature request;
3. Using checkboxes to replace dropdown

ci: update issue template

---

apps/agent-tars/src/renderer/src/state/canvas.ts

feat(agent-tars): hide canvas panel by default (close:#453)

---

apps/agent-tars/src/renderer/src/components/LeftSidebar/index.tsx

feat(agent-tars): remember the collapsed state of the sidebar (close: #453)

---

apps/agent-tars/src/renderer/src/components/LeftSidebar/Settings/SettingsModal.tsx
apps/agent-tars/src/renderer/src/components/LeftSidebar/Settings/useAppSettings.ts

feat(agent-tars): support reset setting (close: #429)

---

apps/agent-tars/src/renderer/src/agent/Greeter.ts

fix(agent-tars): greeter should not respond markdown or html format (close: #284)

---

apps/agent-tars/src/renderer/src/components/AgentApp/index.tsx
apps/agent-tars/src/renderer/src/components/ChatUI/index.tsx
apps/agent-tars/src/renderer/src/components/LeftSidebar/index.tsx
apps/agent-tars/src/renderer/src/components/WelcomeScreen/WelcomeScreen.module.scss
apps/agent-tars/src/renderer/src/components/WelcomeScreen/index.tsx

This Pull Request introduces a series of enhancements and adjustments to the `agent-tars` module. Key updates include collapsing the sidebar by default to improve interface usability, implementing a new welcome screen to guide user onboarding (close: #460), and hiding the canvas panel when creating a new session to streamline the workflow. Additionally, the `uploadFiles` feature has been disabled, and the transition effects for the main area have been removed for a smoother experience.
- Close: #460

feat(agent-tars): welcome screen (close: #460)

---

apps/agent-tars/src/main/ipcRoutes/llm.ts
apps/agent-tars/src/renderer/src/components/LeftSidebar/Settings/ModelSettingsTab.tsx

Added a test feature for Model Provider in the settings to validate the configuration in advance.

feat: Added a test feature for Model Provider

---

apps/agent-tars/src/main/index.ts
apps/agent-tars/src/main/menu.ts

1. Close the window
2. Open the window again
3. Click on the Reload button in the menu bar

fix(agent-tars): mainWindow.webContents typeError: Object has been destroyed

---

apps/agent-tars/docs/settings/mcp.md
apps/agent-tars/package.json
apps/agent-tars/src/renderer/package.json
apps/agent-tars/src/renderer/src/components/LeftSidebar/Settings/AddServerModal.tsx
apps/agent-tars/src/renderer/src/components/LeftSidebar/Settings/MCPServersSettingsTab.tsx
package.json
packages/agent-infra/mcp-client/package.json
packages/agent-infra/mcp-client/src/StreamableHttpClient.ts
packages/agent-infra/mcp-client/src/index.ts
packages/agent-infra/mcp-servers/browser/package.json
packages/agent-infra/mcp-servers/commands/package.json
packages/agent-infra/mcp-servers/filesystem/package.json
packages/agent-infra/mcp-shared/package.json
packages/agent-infra/mcp-shared/src/client/types.ts
pnpm-lock.yaml

feat(agent-tars): support streamable-http mcp server

---

README.md

- https://seed-tars.com/1.5
- https://seed-tars.com/showcase
- https://huggingface.co/ByteDance-Seed/UI-TARS-1.5-7B

docs: update README for UI-TARS-1.5

---

.github/workflows/release-ui-tars.yml
.gitignore
apps/ui-tars/package.json
packages/common/electron-build/src/hooks/postMake.ts
scripts/merge-yml/merge-yml.ts

Ref: https://github.com/lovell/sharp/issues/3622

fix(ui-tars): x64 and arm64 pkg

---

.github/workflows/e2e-agent-tars.yml
.github/workflows/e2e-ui-tars.yml

Close https://github.com/bytedance/UI-TARS-desktop/issues/510
Ref: https://github.com/lovell/sharp/issues/3622

fix(ui-tars): x64 bundle bug

---

apps/ui-tars/src/main/ipcRoutes/browser.ts
apps/ui-tars/src/main/ipcRoutes/index.ts
apps/ui-tars/src/main/main.ts
apps/ui-tars/src/main/services/browserCheck.ts
apps/ui-tars/src/main/services/runAgent.ts
apps/ui-tars/src/main/store/create.ts
apps/ui-tars/src/main/store/types.ts
apps/ui-tars/src/renderer/src/components/ChatInput/SelectOperator.tsx
apps/ui-tars/src/renderer/src/components/ui/tooltip.tsx
docs/quick-start.md
packages/ui-tars/operators/browser-operator/examples/default.ts
packages/ui-tars/operators/browser-operator/package.json
packages/ui-tars/operators/browser-operator/src/browser-operator.ts
pnpm-lock.yaml

Currently, if there is no local browser, the Browser use function is not available, but there is no feedback and the user can still interact normally.
This PR introduces **local browser availability detection**, which detects whether the browser is installed when the ui-tars application is started. If not, the Browser use option should be disabled, and the user will be informed that Chrome needs to be installed before continuing. In this notification tip, the user can also manually retry the detection. If the browser is detected, the Browser use option will change from disabled to available.
Also, If the current setting is browser but the browser is not available, automatically switched to Computer Use mode.
| Default                           | <img width="1204" alt="image" …

feat(ui-tars): local browser availability detection

---

apps/ui-tars/src/main/ipcRoutes/agent.ts
apps/ui-tars/src/renderer/src/components/ChatInput/index.tsx
apps/ui-tars/src/renderer/src/hooks/useRunAgent.ts
apps/ui-tars/src/renderer/src/pages/widget/index.tsx
apps/ui-tars/src/renderer/src/store/session.ts

fix(ui-tars): clear history in new session

---

apps/ui-tars/package.json

release(apps): ui-tars-desktop support UI-TARS-1.5 model

---

docs/quick-start.md

fix(document): docs/quick-start.md VLM Base URL

---

apps/ui-tars/src/renderer/src/components/ImageGallery/index.tsx
apps/ui-tars/src/renderer/src/components/ThoughtChain/index.tsx
apps/ui-tars/src/renderer/src/const/actions.tsx
apps/ui-tars/src/renderer/src/pages/widget/index.tsx
apps/ui-tars/src/renderer/src/store/session.ts

Some UI rendering scenarios did not handle cases where  `action_type` is empty string, causing page rendering errors. This PR fixes this issue.

fix(ui-tars): handle empty action_type to prevent white page

---

.github/ISSUE_TEMPLATE/bug_report_ui_tars_desktop.yml

Edit Issues Template for UI-TARS, adding new models (UI-TARS-1.5-7B and Doubao-1.5-UI-TARS).

chore(ci): update bug_report_ui_tars_desktop.yml

---

packages/agent-infra/browser/src/browser-finder/chrome-paths.ts
packages/ui-tars/operators/browser-operator/src/browser-operator.ts

- refactor `chrome-paths` package error

refactor(browser): refactor chrome-paths error

---

docs/quick-start.md
packages/agent-infra/browser-use/package.json
packages/agent-infra/browser/package.json
packages/agent-infra/browser/src/browser-finder/chrome-paths.ts
packages/agent-infra/browser/src/browser-finder/firefox-paths.ts
packages/agent-infra/browser/src/browser-finder/index.test.ts
packages/agent-infra/browser/src/browser-finder/index.ts
packages/agent-infra/browser/src/local-browser.ts
packages/agent-infra/mcp-servers/browser/package.json
packages/ui-tars/operators/browser-operator/src/browser-operator.ts
pnpm-lock.yaml

- add `firefox-paths`
- `browser-use` support firefox
- add unit tests

feat(browser): add `firefox-paths` and `browser-use` support firefox

---

apps/ui-tars/src/main/logger.ts
apps/ui-tars/src/main/menu.ts
apps/ui-tars/src/main/tray.ts

- Implemented log rotation mechanism with 5MB size limit per file
- Added log archiving with timestamp-based naming
- Limited maximum log files to 5 to prevent disk space issues
- Removed automatic log clearing on app exit
- Reorganized log-related menu items into a dedicated submenu
- Enhanced log file management utilities
- Enhanced user accessibility to log functions
- Preserved important log history

feat(ui-tars): refact log files management

---

README.md

docs(readme): add ask deepwiki

---

packages/ui-tars/action-parser/src/actionParser.ts
packages/ui-tars/action-parser/test/actionParser.test.ts

feat(action-parser): add support for <point> format in action parser

---

apps/ui-tars/src/renderer/src/components/RunMessages/Messages.tsx

fix(ui-tars): make error message expandable

---

README.md

docs: readme github-trending

---

apps/ui-tars/src/renderer/src/components/ChatInput/SelectOperator.tsx
apps/ui-tars/src/renderer/src/components/RunMessages/Messages.tsx
apps/ui-tars/src/renderer/src/components/RunMessages/Welcome.tsx
apps/ui-tars/src/renderer/src/components/ui/alert.tsx
apps/ui-tars/src/renderer/src/const/index.ts
apps/ui-tars/src/renderer/src/pages/settings/Settings.tsx
docs/quick-start.md

feat(ui-tars): add operator desc in the welcome page and update the ErrorMessage UI

---

apps/ui-tars/src/renderer/src/components/RunMessages/ShareOptions.tsx
apps/ui-tars/src/renderer/src/components/SideBar/share.tsx
packages/ui-tars/shared/src/types/data.ts
packages/ui-tars/visualizer/src/component/detail-side.less
packages/ui-tars/visualizer/src/component/detail-side.tsx
packages/ui-tars/visualizer/src/component/store.tsx
packages/ui-tars/visualizer/src/index.tsx
packages/ui-tars/visualizer/src/transform.ts

feat(visualizer): report html show model detail and actions

---

apps/ui-tars/src/main/window/index.ts

https://github.com/electron/electron/issues/20263#issuecomment-633179965

fix(ui-tars): where closing an Electron window in fullscreen mode leaves a black window

---

apps/ui-tars/package.json

release(apps): ui-tars-desktop v0.1.1

---

apps/ui-tars/src/main/window/ScreenMarker.ts
apps/ui-tars/src/renderer/src/pages/widget/index.tsx

feat(ui-tars): widget window displays a border on Windows systems

---

packages/multimodal/agent/src/mcp-agent/mcp-agent.ts
packages/multimodal/agent/src/mcp-agent/mcp-client-v2.ts
packages/multimodal/agent/src/mcp-agent/mcp-types.ts

This pull request updates the MCP agent to default to version 2 of the MCP client, simplifies the MCP client configuration by removing a conversion function, and enhances documentation for MCP-related types. Below are the most important changes grouped by theme.
* Changed the default `mcpClientVersion` from `'v1'` to `'v2'` in the `MCPAgent` constructor, using the nullish coalescing operator (`??`) for fallback. (`packages/multimodal/agent/src/mcp-agent/mcp-agent.ts`, [packages/multimodal/agent/src/mcp-agent/mcp-agent.tsL22-R22](diffhunk://#diff-e861938b027bd8d8cab2b37ee2b0de9e87c803cd4029320bb7298cc9e1ea82b8L22-R22))
* Updated the `MCPAgentOptions` interface to reflect the new default `'v2'` and added a note that this configuration is for testing purposes only. …

refactor(agent-tars): refine mcp types

---

apps/agent-tars/src/main/utils/updateApp.ts
apps/ui-tars/src/main/utils/updateApp.ts

fix: update checker bug

---

packages/ui-tars/operators/nut-js/src/index.ts

feat(nutjs): avoid compression to use png format instead

---

apps/ui-tars/src/main/agent/prompts.ts
apps/ui-tars/src/main/services/runAgent.ts
apps/ui-tars/src/main/store/types.ts
packages/ui-tars/operators/browser-operator/src/browser-operator.ts
packages/ui-tars/operators/nut-js/src/index.ts

Support doubao-1.5-thinking-vision-pro

---

apps/ui-tars/src/renderer/src/components/RunMessages/Messages.tsx
apps/ui-tars/src/renderer/src/components/RunMessages/index.tsx

feat(ui-tars): support assistant message style in history

---

apps/ui-tars/src/main/agent/prompts.ts
apps/ui-tars/src/main/services/runAgent.ts
apps/ui-tars/src/renderer/src/components/RunMessages/Messages.tsx
apps/ui-tars/src/renderer/src/components/ThoughtChain/index.tsx

Fix chores to support Doubao-1.5-thinking-vision-pro

---

apps/ui-tars/package.json

release(apps): ui-tars-desktop support Doubao-1.5-thinking-vision-pro

---

packages/multimodal/agent/examples/tool-calls/basic.ts
packages/multimodal/agent/rslib.config.ts
packages/multimodal/agent/src/agent/agent-runner.ts
packages/multimodal/agent/src/agent/agent.ts
packages/multimodal/agent/src/agent/message-history.test.ts
packages/multimodal/agent/src/agent/message-history.ts
packages/multimodal/agent/src/agent/runner/llm-processor.ts
packages/multimodal/agent/src/agent/runner/loop-executor.ts
packages/multimodal/agent/src/agent/runner/stream-adapter.ts
packages/multimodal/agent/src/agent/runner/tool-processor.ts
packages/multimodal/agent/src/tool-call-engine/NativeToolCallEngine.test.ts
packages/multimodal/agent/src/tool-call-engine/NativeToolCallEngine.ts
packages/multimodal/agent/src/tool-call-engine/PromptEngineeringToolCallEngine.test.ts
packages/multimodal/agent/src/tool-call-engine/PromptEngineeringToolCallEngine.ts
packages/multimodal/agent/src/tool-call-engine/shared.test.ts
packages/multimodal/agent/src/utils/multimodal.test.ts

The current Agent Runner is too large and difficult to maintain, so it is refactored into several classes with clearer responsibilities:
- The **AgentRunner** orchestrates the overall execution
- The **LLMProcessor** handles model interaction
- The **ToolProcessor** manages tool execution
- The **LoopExecutor** controls the reasoning loop flow
- The **StreamAdapter** converts internal events to streaming responses
Current snapshot tests help us to know the context build detail easier:
---

refactor(agent): agent runner and improve tests for core entities

---

packages/ui-tars/sdk/src/GUIAgent.ts
packages/ui-tars/sdk/src/Model.ts
packages/ui-tars/sdk/src/types.ts

feat(sdk): support thinking controll for model invoking

---

.changeset/config.json
packages/agent-infra/mcp-benchmark/CHANGELOG.md
packages/agent-infra/mcp-benchmark/package.json
packages/agent-infra/mcp-client/CHANGELOG.md
packages/agent-infra/mcp-client/package.json
packages/agent-infra/mcp-http-server/CHANGELOG.md
packages/agent-infra/mcp-http-server/README.md
packages/agent-infra/mcp-http-server/package.json
packages/agent-infra/mcp-http-server/src/startServer.ts
packages/agent-infra/mcp-http-server/tests/startServer-mcpServer.test.ts
packages/agent-infra/mcp-http-server/tests/startServer-server.test.ts
packages/agent-infra/mcp-servers/browser/.dockerignore
packages/agent-infra/mcp-servers/browser/CHANGELOG.md
packages/agent-infra/mcp-servers/browser/Dockerfile
packages/agent-infra/mcp-servers/browser/Dockerfile.http
packages/agent-infra/mcp-servers/browser/README.md
packages/agent-infra/mcp-servers/browser/package.json
packages/agent-infra/mcp-servers/browser/smithery.yaml
packages/agent-infra/mcp-servers/browser/src/constants.ts
packages/agent-infra/mcp-servers/browser/src/index.ts
packages/agent-infra/mcp-servers/browser/src/server.ts
packages/agent-infra/mcp-servers/commands/CHANGELOG.md
packages/agent-infra/mcp-servers/commands/package.json
packages/agent-infra/mcp-servers/commands/src/index.ts
packages/agent-infra/mcp-servers/filesystem/CHANGELOG.md
packages/agent-infra/mcp-servers/filesystem/package.json
packages/agent-infra/mcp-servers/filesystem/src/index.ts
packages/agent-infra/mcp-shared/CHANGELOG.md
packages/agent-infra/mcp-shared/package.json
pnpm-lock.yaml

https://smithery.ai/server/@bytedance/mcp-server-browser

chore:(mcp-server): add smithery remote

---

apps/agent-tars/package.json
apps/ui-tars/src/main/main.ts

chore: agent tars version

---

apps/agent-tars/forge.config.ts
apps/agent-tars/src/main/utils/updateApp.ts
apps/agent-tars/src/shared/constants.ts
apps/ui-tars/package.json
apps/ui-tars/resources/app-update.yml
apps/ui-tars/src/main/electron-updater/GitHubProvider.ts
apps/ui-tars/src/main/utils/updateApp.ts
packages/common/electron-build/src/hooks/postMake.ts
pnpm-lock.yaml

fix(app): update check and releaseNotes

---

apps/ui-tars/forge.config.ts
apps/ui-tars/package.json
apps/ui-tars/src/main/ipcRoutes/window.ts
apps/ui-tars/src/main/shared/constants.ts
apps/ui-tars/src/main/utils/updateApp.ts
apps/ui-tars/src/main/window/createWindow.ts
apps/ui-tars/src/preload/index.ts
apps/ui-tars/src/renderer/src/pages/settings/Settings.tsx

feat(ui-tars): settings add update checker

---

apps/ui-tars/src/renderer/src/components/ChatInput/index.tsx
apps/ui-tars/src/renderer/src/components/ChatInput/vlmDialog.tsx

feat(ui-tars): add VLM dialog component to chat input

---

apps/ui-tars/src/main/ipcRoutes/agent.ts
apps/ui-tars/src/main/services/runAgent.ts
apps/ui-tars/src/main/store/create.ts
apps/ui-tars/src/main/store/types.ts
apps/ui-tars/src/renderer/src/components/ChatInput/index.tsx
apps/ui-tars/src/renderer/src/hooks/useRunAgent.ts
apps/ui-tars/src/renderer/src/pages/launcher/index.tsx
packages/ui-tars/sdk/README.md
packages/ui-tars/sdk/src/GUIAgent.ts
packages/ui-tars/sdk/src/utils.ts

feat(ui-tars-sdk): support histroy context when agent running

---

packages/ui-tars/action-parser/src/actionParser.ts

fix(action-parser): fix the parsing bug for 1.5vl

---

.github/ISSUE_TEMPLATE/bug_report_agent_tars_cli.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_requrest.yml

We are in the final stages of releasing the Agent TARS CLI.

chore: add issue template about agent tars cli

---

.github/ISSUE_TEMPLATE/bug_report_agent_tars_cli.yml

This pull request updates the issue template for bug reports related to the Agent TARS CLI. The change refines the options for issue categorization by replacing generic labels with more specific ones that include package references.
* [`.github/ISSUE_TEMPLATE/bug_report_agent_tars_cli.yml`](diffhunk://#diff-2327262e6ef18be369f7cd206ef59f371852aa63029bfd3973dbd29b49c39be3L23-R28): Replaced generic labels such as "Agent Core" and "UI" with specific labels that include package references (e.g., `Agent TARS Web UI (@agent-tars/web-ui)`, `Agent Kernel (@multimodal/agent)`), improving clarity and specificity for bug reporting.

chore: enhance issue template

---

.github/workflows/agent_tars_test.yml
multimodal/agent-interface/package.json
multimodal/agent-tars/src/agent-tars.ts
multimodal/agent-tars/src/browser/browser-control-strategies/base-strategy.ts
multimodal/agent-tars/src/browser/browser-gui-agent.ts
multimodal/agent-tars/src/browser/browser-tools-manager.ts
multimodal/agent-tars/src/planner/deep-research.ts
multimodal/agent-tars/src/types.ts
multimodal/agent/package.json
multimodal/agent/snapshot/__snapshots__/index.test.ts.snap
multimodal/agent/src/agent/tool.ts
multimodal/agent/src/index.ts
multimodal/agent/src/utils/common.ts
multimodal/agent/tests/agent/message-history.test.ts
multimodal/codeact-agent/src/base.ts
multimodal/codeact-agent/src/node-code-act.ts
multimodal/codeact-agent/src/python-code-act.ts
multimodal/codeact-agent/src/shell-code-act.ts
multimodal/mcp-agent/package.json
multimodal/mcp-agent/src/index.ts
multimodal/mcp-agent/src/mcp-tool-adapter.ts
multimodal/mcp-agent/src/mcp-types.ts
multimodal/model-provider/package.json
multimodal/pnpm-lock.yaml

Resolved CI issues for the multimodal project by adding the `.github/workflows/agent_tars.yml` file to enhance GitHub Actions workflows. Also fixed build failures caused by shadow dependencies.

ci(multimodal): add `.github/workflows/agent_tars.yml`

---

multimodal/agent-tars-web-ui/src/common/types/index.ts
multimodal/agent-tars-web-ui/src/standalone/workspace/WorkspaceDetail.tsx
multimodal/agent-tars-web-ui/src/standalone/workspace/renderers/FileResultRenderer.tsx
multimodal/agent-tars-web-ui/src/standalone/workspace/renderers/ToolResultRenderer.tsx

fix(agent-tars-web-ui): workspace should render `read_file` (close: #693)

---

multimodal/agent/snapshot/__snapshots__/index.test.ts.snap
multimodal/agent/snapshot/index.test.ts
multimodal/agent/tests/agent/kernel/agent-base.test.ts
multimodal/agent/tests/agent/kernel/agent-running.test.ts
multimodal/agent/tests/agent/kernel/agent.test.ts
multimodal/agent/tests/agent/kernel/types.ts
multimodal/agent/tests/agent/kernel/utils/mockFactory.ts
multimodal/agent/tests/agent/kernel/utils/testUtils.ts

We have improved the unit test of `@multimodal/agent` to cover the basic state test of Agent class initialization and operation, in preparation for the subsequent addition of new features

test(agent): improve agent kernel unit tests

---

apps/ui-tars/src/renderer/src/pages/remote/cast/vnc.tsx
apps/ui-tars/src/renderer/src/pages/remote/free.tsx
packages/ui-tars/sdk/README.md

optimize VNC scaling
https://github.com/user-attachments/assets/d40846b4-5d20-46a4-aca2-19ecc003e6d3

fix(ui-tars): optimize VNC scaling

---

multimodal/agent-tars-server/src/api/controllers/sessions.ts
multimodal/agent-tars-server/src/core/AgentSession.ts
multimodal/agent-tars-server/src/utils/workspace.ts

fix(agent-tars-server): `workingDirectory` error when snapshot is enabled (close: #724)

---

multimodal/agent-tars-server/src/api/controllers/queries.ts
multimodal/agent-tars-server/src/api/controllers/sessions.ts
multimodal/agent-tars-server/src/api/controllers/share.ts
multimodal/agent-tars-server/src/api/controllers/system.ts
multimodal/agent-tars-server/src/express.d.ts
multimodal/agent-tars-server/src/types.ts

feat(agent-tars): add express locals type definition

---

multimodal/agent-tars-cli/bin/cli.js
multimodal/agent-tars-cli/rslib.config.ts
multimodal/agent-tars-cli/src/core/state.ts
multimodal/agent-tars-cli/src/env.d.ts
multimodal/agent-tars-cli/src/index.ts
multimodal/agent-tars-server/rslib.config.ts
multimodal/agent-tars/rslib.config.ts
multimodal/codeact-agent/rslib.config.ts
multimodal/deep-research-agent/rslib.config.ts
multimodal/mcp-agent-interface/rslib.config.ts
multimodal/mcp-agent/rslib.config.ts

fix(agent-tars-cli): displays old version (close: #729)

---

apps/ui-tars/src/renderer/src/components/Settings/category/vlm.tsx

fix(ui-tars): fix the UI flickering issue after importing preset config

---

multimodal/agent-tars-cli/src/config/builder.ts
multimodal/agent-tars-cli/src/core/interactive-ui.ts
multimodal/agent-tars-cli/src/utils/logo.ts

feat(agent-tars-cli): config `--workspace` shortcut (close: #752)

---

multimodal/agent-tars-cli/src/commands/options.ts
multimodal/agent-tars-cli/src/commands/workspace.ts

feat(agent-tars-cli): fine-grained global workspace control (close: #754)

---

multimodal/agent-tars-cli/src/core/interactive-ui.ts

- Close: #756
- Before:
- After

feat(agent-tars-cli): display current model info (close: #756)

---

multimodal/agent-tars-web-ui/src/standalone/workspace/WorkspaceDetail.tsx

fix(agent-tars-web-ui): `write_file` does not display file content

---

multimodal/agent-tars/src/agent-tars.ts
multimodal/agent-tars/src/browser/browser-control-validator.ts
multimodal/agent-tars/src/browser/index.ts

- Close: #760
In Agent TARS, we currently only support enabling `GUI Agent` for Doubao-1.5 VL, before this, if you enable GUI Agent (set `browser.control` to `mixed` or `gui-agent-only`) for Non-Doubao models, it will not work, resulting in unusable.
After this PR, the `browser.control` will be automatically redirected to `browser-use-only`, ensuring that Claude and OpenAI can complete the task based on DOM-based Browser Control.
The following is the current status of model compatibility:
| Model Provder | Model             | Text | Vision | Tool Call & MCP | GUI Grounding |
| ------------- | ----------------- | ---- | ------ | --------------- | ------------- |
| `volcengine`  | Seed1.5-VL        | ✔️   | ✔️     | ✔️              | ✔️            |
| `anthropic`   | claude-3.7-sonnet | ✔️ …

feat(agent-tars): add gui agent grounding check (close: #760)

---

multimodal/agent-tars-web-ui/src/standalone/home/WelcomePage.tsx

feat(agent-tars-web-ui): support multiple-line input in home

---

multimodal/CONTRIBUTING.md
multimodal/package.json
multimodal/pnpm-toolkit/src/cli.ts
multimodal/pnpm-toolkit/src/commands/dev.ts
multimodal/pnpm-toolkit/src/types.ts

When you're working on lower-level core packages (such as `@multimodal/agent`), it's recommended to use the following command:
```bash
pnpm dev:core
```
This will start the development server with the core packages already running by default, rather than waiting for changes to trigger their builds. Since some higher-level packages bundle these core dependencies (see [#745](https://github.com/bytedance/UI-TARS-desktop/pull/745)), this approach makes debugging much easier by ensuring the core packages are built and ready immediately.
You can also specify other packages to watch:
```bash
pnpm dev:core
pnpm ptk d --packages @package/name1,@package/name2
```

ci(agent-tars): add `dev:core` command for easier debugging

---

multimodal/agent-tars-cli/src/config/builder.ts
multimodal/agent-tars/src/agent-tars.ts
multimodal/agent-tars/src/index.ts
multimodal/agent-tars/src/shared/config-utils.ts
multimodal/agent-tars/tests/browser-control-strategies.test.ts
multimodal/agent-tars/tests/shared/config-utils.test.ts

fix(agent-tars): gui agent grounding check won't work when `browser.control` is not configured （close: #773）

---

multimodal/agent-tars-web-ui/public/index.html
multimodal/agent-tars-web-ui/src/standalone/workspace/renderers/CommandResultRenderer.tsx

feat(agent-tars-web-ui): introduce new `run_command` ui

---

multimodal/agent-tars/package.json
multimodal/pnpm-lock.yaml

Upgrade Agent TARS's core MCP Servers to latest version, especially `@agent-infra/mcp-server-browser`, to benefit from some optimizations about `browser_navigate` from https://github.com/bytedance/UI-TARS-desktop/pull/677.

feat(agent-tars): bump `@agent-infra/mcp-server-*` to `1.1.10` (#775)

---

multimodal/agent-tars-web-ui/src/standalone/chat/Message/index.tsx

fix(agent-tars-web-ui): missing view final environment state entry

---

apps/ui-tars/src/main/remote/proxyClient.ts

feat(ui-tars-sdk): add remote api's request id into log and error

---

multimodal/agent-tars/src/agent-tars.ts
multimodal/agent-tars/src/browser/browser-control-strategies/base-strategy.ts
multimodal/agent-tars/src/browser/browser-control-strategies/browser-dom-strategy.ts
multimodal/agent-tars/src/browser/browser-control-strategies/browser-hybrid-strategy.ts
multimodal/agent-tars/src/browser/browser-control-strategies/browser-visual-grounding-strategy.ts
multimodal/agent-tars/src/browser/browser-tools-manager.ts
multimodal/agent-tars/src/browser/tools/content.ts
multimodal/agent-tars/src/browser/tools/navigation.ts
multimodal/agent-tars/src/browser/tools/status.ts
multimodal/agent-tars/src/browser/tools/visual.ts
multimodal/agent-tars/tests/__snapshots__/browser_tools_dom.snap

Support `browser_screenshot` for models (e.g. claude 3.7) that currently only support DOM-based browser control, so that it can achieve graphic and text reports:

feat(agent-tars): support `browser_screenshot` tool for DOM-based control

---

apps/ui-tars/src/renderer/src/pages/remote/free.tsx

fix(ui-tars): clear time cache when time expired

---

multimodal/agent-tars-web-ui/src/standalone/app/Layout/Shell.tsx
multimodal/agent-tars-web-ui/src/standalone/app/Layout/index.tsx
multimodal/agent-tars-web-ui/src/standalone/app/index.tsx
multimodal/agent-tars-web-ui/src/standalone/chat/Message/Message.css
multimodal/agent-tars-web-ui/src/standalone/navbar/Navbar.tsx
multimodal/agent-tars-web-ui/src/standalone/sidebar/ChatSession.tsx
multimodal/agent-tars-web-ui/src/standalone/sidebar/SessionItem.tsx
multimodal/agent-tars-web-ui/src/standalone/sidebar/SessionSearch.tsx
multimodal/agent-tars-web-ui/src/standalone/sidebar/ToolBar.tsx

feat(agent-tars-web-ui): dark mode by default (#793)

---

multimodal/agent-tars-cli/src/commands/workspace.ts

User just want to upgrade the config, `workspace --init` should not remove existing files

feat(agent-tars-cli): `workspace --init` should not remove existing files

---

multimodal/agent-tars-server/src/core/AgioBatchProcessor.ts
multimodal/agent-tars-server/tests/core/AgioBatchProcessor.test.ts

Agio request itself is not a strong dependency, so errors can be ignored to make the log cleaner

feat(agent-tars-server): make agio request silent

---

multimodal/agent-tars-web-ui/src/sdk/markdown-renderer/CodeBlock.tsx
multimodal/agent-tars-web-ui/src/standalone/chat/Message/Message.css
multimodal/agent-tars-web-ui/src/standalone/chat/MessageInput.tsx
multimodal/agent-tars-web-ui/src/standalone/sidebar/ToolBar.tsx

Optimized the send message button, inline code, and code rendering

feat(agent-tars-web-ui): enhance message input and code block render

---

packages/ui-tars/operators/browser-operator/src/browser-operator.ts

fix(browser-operator): goto URL wait no events

---

apps/ui-tars/src/main/remote/shared.ts

feat(ui-tars): update proxy server's endpoint

---

.changeset/wild-meals-lay.md
packages/agent-infra/mcp-client/CHANGELOG.md
packages/agent-infra/mcp-client/package.json
packages/agent-infra/mcp-servers/browser/CHANGELOG.md
packages/agent-infra/mcp-servers/browser/package.json
packages/agent-infra/mcp-servers/commands/CHANGELOG.md
packages/agent-infra/mcp-servers/commands/package.json
packages/agent-infra/mcp-servers/filesystem/CHANGELOG.md
packages/agent-infra/mcp-servers/filesystem/package.json
packages/agent-infra/mcp-servers/search/CHANGELOG.md
packages/agent-infra/mcp-servers/search/package.json
packages/agent-infra/mcp-shared/CHANGELOG.md
packages/agent-infra/mcp-shared/package.json
packages/agent-infra/search/browser-search/CHANGELOG.md
packages/agent-infra/search/browser-search/examples/remote-browser.ts
packages/agent-infra/search/browser-search/package.json
packages/agent-infra/search/browser-search/src/browser-search.ts
packages/agent-infra/search/browser-search/src/types.ts
packages/agent-infra/search/search/CHANGELOG.md
packages/agent-infra/search/search/package.json

This pull request introduces support for connecting to a remote browser in the `BrowserSearch` module. The changes include adding a new configuration option (`cdpEndpoint`), updating the browser initialization logic, and providing an example for using the new functionality.
* [`packages/agent-infra/search/browser-search/src/types.ts`](diffhunk://#diff-1e32d77219ace84477ac63fce6218e9ea8c8d4de70f3a48687f2ec3d86a25800R59-R63): Introduced a new `cdpEndpoint` property in the `BrowserSearchConfig` interface to enable connecting to a remote browser. If `cdpEndpoint` is provided, other browser configuration options are ignored.
* [`packages/agent-infra/search/browser-search/src/browser-search.ts`](diffhunk://#diff-a021783a1be98696f9082014078312bf7241761b0656ca7663587ebefbd5998eL34-R46): Updated …

feat(browser-search): support `cdpEndpoint` to connect to remote browser

---

multimodal/agent-tars-web-ui/src/standalone/navbar/Navbar.tsx

feat(agent-tars-web-ui): enhance model info banner

---

multimodal/agent-tars/src/agent-tars.ts

This pull request improves the `write_file` tool in `agent-tars` by ensuring it resolves relative file paths using the workspace's `workingDirectory`, preventing potential file handling issues. 
Event stream:
```ts
{
"id": "826ac441-fd05-4349-8873-57f02acc15cd",
"type": "assistant_message",
"timestamp": 1751449030497,
"content": "I'll create a simple Python \"Hello World\" program and run it for you. Let me do that step by step.\n\nFirst, I'll create a Python file with the classic \"Hello World\" code:",
"toolCalls": [
{
"id": "tooluse_nGL5BGL6RvuAUODtDsplvQ",
"type": "",
"function": {
"name": "write_file",
"arguments": "{\"path\": \"hello_world.py\", \"content\": \"print(\\\"Hello, World!\\\")\"}"
}
}
],
"finishReason": "tool_calls",
"messageId": "msg_1751449027672_tadsmhjz"
},
{
"id": …
```

fix(agent-tars): `write_file` should respect workspace workingDirectory (close: #815)

---

multimodal/websites/docs/docs/zh/blog/2025-06-25-introducing-agent-tars-beta.mdx

Replace internal Feishu group links with public group links.
close #861

docs: fix feishu link

---

multimodal/agent-tars-web-ui/src/entry.css
multimodal/agent-tars-web-ui/src/sdk/markdown-renderer/MarkdownRenderer.tsx
multimodal/agent-tars-web-ui/src/standalone/workspace/WorkspaceDetail.tsx
multimodal/agent-tars-web-ui/src/standalone/workspace/components/FullscreenModal.tsx
multimodal/agent-tars-web-ui/src/standalone/workspace/components/ImageModal.tsx
multimodal/agent-tars-web-ui/src/standalone/workspace/components/WorkspaceHeader.tsx
multimodal/agent-tars-web-ui/src/standalone/workspace/renderers/generic/components/FileResultRenderer.tsx
multimodal/agent-tars-web-ui/src/standalone/workspace/types/index.ts
multimodal/agent-tars-web-ui/src/standalone/workspace/types/panelContent.ts
multimodal/agent-tars-web-ui/src/standalone/workspace/utils/contentStandardizer.ts

feat(agent-tars-web-ui): support full-screen markdown file rendering

---

apps/ui-tars/src/main/ipcRoutes/remoteResource.ts
apps/ui-tars/src/renderer/src/components/Settings/category/remoteBrowser.tsx
apps/ui-tars/src/renderer/src/components/Settings/global.tsx
apps/ui-tars/src/renderer/src/hooks/useRemoteResource.ts
apps/ui-tars/src/renderer/src/pages/remote/free.tsx

feat(ui-tars): switch remote browser cast type

---

multimodal/agent-tars-web-ui/package.json
multimodal/agent-tars-web-ui/src/common/state/actions/eventProcessor.ts
multimodal/agent-tars-web-ui/src/sdk/code-editor/CodeEditor.tsx
multimodal/agent-tars-web-ui/src/standalone/chat/Message/components/ToolCalls.tsx
multimodal/agent-tars-web-ui/src/standalone/workspace/utils/contentStandardizer/standardizer.ts
multimodal/pnpm-lock.yaml

This PR enhances the `agent-tars-web-ui` to support streaming tool calls, improving real-time updates and handling incomplete JSON data with the `jsonrepair` library. It refines tool call state management, introducing a "constructing" state with improved UI feedback. These changes ensure robust handling of streaming assistant messages and better user experience during ongoing operations.
- Added a null-check in the `CodeEditor` component to handle undefined `code`.
- Enhanced `standardizeContent` for proper formatting of streaming `write_file` operations.
- Updated dependencies to include `jsonrepair` library for safe JSON handling.

feat(agent-tars-web-ui): render streaming tool call

---

multimodal/agent-interface/src/agent-instance.ts
multimodal/agent-interface/src/agent.ts
multimodal/agent-interface/src/tool-call-engine.ts
multimodal/agent/examples/hooks/adaptive.ts
multimodal/agent/examples/hooks/inject-system-prompt.ts
multimodal/agent/src/agent/base-agent.ts
multimodal/agent/src/agent/runner/llm-processor.ts
multimodal/agent/src/tool-call-engine/NativeToolCallEngine.ts
multimodal/agent/src/tool-call-engine/PromptEngineeringToolCallEngine.ts
multimodal/agent/src/tool-call-engine/StructuredOutputsToolCallEngine.ts

Introduced the `onPrepareRequest` hook to enable dynamic modifications of the system prompt and tools during agent execution, enhancing flexibility. Refactored the `PrepareRequestContext` interface for improved clarity and consistency. 
**1. modify system prompt**
```ts
/**
* Simple example: How to modify system prompt dynamically using onPrepareRequest hook
*/
import { PrepareRequestContext, PrepareRequestResult, Agent } from '../../src';
class CustomAgent extends Agent {
public onPrepareRequest(context: PrepareRequestContext): PrepareRequestResult {
const { systemPrompt, tools, iteration } = context;
const enhancedPrompt = `IMPORTANT: You are in iteration ${iteration}.
${systemPrompt}
User name: ULIVZ.`;
return {
systemPrompt: enhancedPrompt,
tools,
};
}
}
async function main() {
const …
```

feat(agent-kernel): `onPrepareRequest` hook (#889)

---

apps/ui-tars/src/renderer/src/components/CountDown/index.tsx
apps/ui-tars/src/renderer/src/pages/remote/free.tsx

feat(ui-tars): update volcano engine FaaS url

---

apps/ui-tars/package.json

chore(ui-tars): update release version

---

multimodal/agent-tars-web-ui/src/standalone/chat/Message/Message.css
multimodal/websites/docs/docs/public/netlify.toml

This pull request introduces improvements to the user interface and updates to the website's redirect rules. The most important changes include enhancing text wrapping in message bubbles and adding a new redirect rule for the `/showcase/*` path.
* [`multimodal/agent-tars-web-ui/src/standalone/chat/Message/Message.css`](diffhunk://#diff-848ccdaa82aec10928ac5f3f6339c18350f3be03c46aac0b191c9a9fc7c73a24R23): Added `word-wrap: break-word;` to the `.message-bubble` class to improve text wrapping and prevent overflow issues.
* [`multimodal/websites/docs/docs/public/netlify.toml`](diffhunk://#diff-d1034078f87efa25fa741c517af8393fc92d4fc67b870f8f74ab8dded0418933R14-R17): Added a new redirect rule to redirect `/showcase/*` to `/`. This ensures users visiting showcase-related paths are directed to …

docs(agent-tars): add showcase redirects

---

multimodal/agent-tars-web-ui/src/common/constants/index.ts
multimodal/agent-tars-web-ui/src/common/services/apiService.ts
multimodal/agent-tars-web-ui/src/entry.tsx
multimodal/agent-tars-web-ui/src/sdk/dialog/AboutModal.tsx
multimodal/agent-tars-web-ui/src/sdk/dialog/index.tsx
multimodal/agent-tars-web-ui/src/standalone/navbar/Navbar.tsx

Introducing a simple about model to display version:

feat(agent-tars-web-ui): add about entry to display version

---

multimodal/agent-tars-web-ui/src/common/hooks/useReplay.ts

fix(agent-tars-web-ui): wrong initial position of draggable playhead

---

multimodal/agent-tars-web-ui/src/standalone/workspace/renderers/generic/components/FileResultRenderer.tsx

This pull request includes a minor change to the `FileResultRenderer` component in `FileResultRenderer.tsx`. The default state for `htmlPreviewMode` has been updated from `'code'` to `'preview'`.

feat(agent-tars-web-ui): display rendered HTML by default

---

multimodal/agent-tars-web-ui/src/standalone/app/Layout/index.tsx
multimodal/agent-tars-web-ui/src/standalone/navbar/Navbar.tsx

| Before | After |
| --- | --- |
|<img width="828" height="1774" alt="image" src="https://github.com/user-attachments/assets/b864d6d3-ed00-4307-9abe-245d302e6915" /> | <img width="826" height="1778" alt="image" src="https://github.com/user-attachments/assets/56b7e603-1df3-4079-ab61-6d24a1510674" />|

feat(agent-tars-web-ui): initial support for mobile-side layout (#927)

---

multimodal/agent-tars-cli/rslib.config.ts
multimodal/agent-tars-cli/src/core/headless-server.ts
multimodal/agent-tars-cli/src/core/interactive-ui.ts
multimodal/agent-tars-cli/src/core/server-run.ts
multimodal/agent-tars-cli/src/core/state.ts
multimodal/agent-tars-cli/src/env.d.ts
multimodal/agent-tars-cli/src/index.ts
multimodal/agent-tars-interface/src/server.ts
multimodal/agent-tars-server/src/api/controllers/sessions.ts
multimodal/agent-tars-server/src/api/controllers/system.ts
multimodal/agent-tars-server/src/server.ts
multimodal/agent-tars-server/src/services/ShareService.ts
multimodal/agent-tars-server/src/utils/share.ts
multimodal/agent-tars-web-ui/package.json
multimodal/agent-tars-web-ui/src/common/services/apiService.ts
multimodal/agent-tars-web-ui/src/common/types/env.d.ts
multimodal/agent-tars-web-ui/src/sdk/dialog/AboutModal.tsx
multimodal/pnpm-lock.yaml

This pull request introduces build metadata enhancements across the `Agent TARS` project, including the addition of **_git commit hash_** and **_build time information_**. These changes improve version tracking, enhance debugging capabilities, and provide more transparency in the user interface.

fix(agent-tars-web-ui): version info does not work at shared artifact

---

multimodal/agent/src/tool-call-engine/PromptEngineeringToolCallEngine.ts

This pull request enhances the `PromptEngineeringToolCallEngine` to handle incomplete tool calls caused by stop sequence truncation. Key updates include refining stop sequence support for OpenAI and AWS engines, enabling recovery of truncated JSON tool calls, and improving logging for better traceability. These changes aim to bolster tool execution reliability and debugging insights.
Added logging enhancements to provide detailed feedback during tool call recovery and summarization, improving transparency in tool processing outcomes.

feat(agent-tars): enable `stop_sequences` for kor engine

---

multimodal/agent-tars-web-ui/src/common/state/actions/sessionActions.ts

This pull request addresses an issue where duplicate abort messages were being generated in the `agent-tars-web-ui`.

fix(agent-tars-web-ui): duplicate abort message

---

multimodal/agent-tars/src/prompt.ts
multimodal/agent/tests/tool-call-engine/PromptEngineeringToolCallEngine.test.ts

This Pull Request enhances the system prompt, adding detailed rules for writing engaging content and generating deliverable reports.
Introduced guidelines for formatting deliverables in `.md` and `.html` files, ensuring robust and professional reporting standards.

feat(agent-tars): enhance system instruction for reporter

---

multimodal/agent-tars-server/src/services/ShareService.ts
multimodal/agent-tars-server/src/utils/index.ts
multimodal/agent-tars-server/src/utils/share.ts
multimodal/agent-tars-server/src/utils/url.ts
multimodal/agent-tars-server/src/utils/workspace-static-server.ts
multimodal/agent-tars-web-ui/src/common/constants/toolTypes.ts
multimodal/agent-tars-web-ui/src/common/hooks/useSession.ts
multimodal/agent-tars-web-ui/src/common/state/actions/eventProcessor.ts
multimodal/agent-tars-web-ui/src/common/state/actions/sessionActions.ts
multimodal/agent-tars-web-ui/src/common/state/atoms/files.ts
multimodal/agent-tars-web-ui/src/standalone/chat/ChatPanel.tsx
multimodal/agent-tars-web-ui/src/standalone/chat/FilesDisplay.tsx
multimodal/agent-tars-web-ui/src/standalone/chat/MessageInput.tsx
multimodal/agent-tars-web-ui/src/standalone/share/ShareModal.tsx
multimodal/agent-tars-web-ui/src/standalone/workspace/PlanView.tsx
multimodal/agent-tars-web-ui/src/standalone/workspace/renderers/PlanViewerRenderer.tsx
multimodal/agent-tars-web-ui/src/standalone/workspace/utils/contentStandardizer/standardizer.ts
multimodal/websites/docs/src/shared/urlUtils.ts

feat(agent-tars): handle generated files sharing

---

multimodal/agent-tars/src/browser/browser-gui-agent.ts
multimodal/agent-tars/tests/browser/parse-action.test.ts

Doubao 1.6 Model output GUI Action cannot be fully followed by prompt specifications. It needs to be compatible in parseAction. 
- doubao 1.5vl output is："click(point='<point>892 351</point>')"
- doubao 1.6 output is： "click(point='<point>450 565</point>"  ,  sometimes like  " click(point='<point>450 565</point>)"

fix(agent-tars): parseAction compatible with irregular model output

---

multimodal/agent-tars-web-ui/src/standalone/chat/MessageInput.tsx
multimodal/agent-tars-web-ui/src/standalone/share/ShareModal.tsx

Download html does not work as expected.

fix(agent-tars-web-ui): download html down not work

---

multimodal/agent/src/agent/agent-runner.ts
multimodal/agent/src/agent/agent.ts
multimodal/agent/src/agent/runner/loop-executor.ts
multimodal/agent/tests/agent/agent-modes.test.ts

Remove the duplicate system abort message since we have already have created assistant abort message

feat(agent-kernel): remove system abort message

---

multimodal/agent-tars-web-ui/src/common/hooks/useReplay.ts
multimodal/agent-tars-web-ui/src/common/hooks/useReplayMode.tsx
multimodal/agent-tars-web-ui/src/common/state/actions/eventProcessor.ts
multimodal/agent-tars-web-ui/src/common/state/actions/sessionActions.ts
multimodal/agent-tars-web-ui/src/standalone/workspace/WorkspacePanel.tsx
multimodal/agent-tars-web-ui/src/standalone/workspace/components/FullscreenModal.tsx

Currently, in the shared Replay, we have a playback mechanism based on Event Stream, but as time goes by, we find that many users do not necessarily need to see the Replay process, but pay more attention to the products delivered by Agent. Therefore, We plan to adjust the default behavior of Share Report
1. If Generated Files exist, the behavior is changed to directly go to the end
2. If Generated Files do not exist, directly display the final status
If this parameter exists and this file exists in Generated Files, the state switches to full screen rendering html or markdown, requiring the reuse of the existing WorkspaceDetail logic
If this parameter exists, the behavior is consistent with the existing logic, that is, the countdown completes the replay
1. Fix the full-screen path display …

feat(agent-tars-web-ui): refine share behavior

---

apps/ui-tars/src/renderer/src/pages/remote/cast/vnc.tsx

feat(ui-tars): change vnc default width and height

---

multimodal/agent-tars-cli/src/index.ts

fix(agent-tars-cli): remove unused log

---

multimodal/agio/agio-schema.json

Update the `agio-schema.json` due to the underlying type updates.

chore(agio): update `agio-schema.json`

---

multimodal/agent-tars-web-ui/src/common/state/atoms/ui.ts
multimodal/agent-tars-web-ui/src/common/types/index.ts
multimodal/agent-tars-web-ui/src/sdk/dialog/index.tsx
multimodal/agent-tars-web-ui/src/standalone/navbar/AboutModal.tsx
multimodal/agent-tars-web-ui/src/standalone/navbar/Navbar.css
multimodal/agent-tars-web-ui/src/standalone/navbar/Navbar.tsx

We'll re-design the navbar, since we have introduced `about` model at  https://github.com/bytedance/UI-TARS-desktop/pull/914 , Let's move the model info to here.

feat(agent-tars-web-ui): move model info to about modal

---

multimodal/agent-snapshot/src/agent-snapshot.ts

Agent snapshot should not couple with `TEST` env.

chore(agent-snapshot): remove test env setup

---

multimodal/CHANGELOG.md
multimodal/agent-interface/package.json
multimodal/agent-snapshot/package.json
multimodal/agent-tars-cli/package.json
multimodal/agent-tars-interface/package.json
multimodal/agent-tars-server/package.json
multimodal/agent-tars-test-workspace/package.json
multimodal/agent-tars-web-ui/package.json
multimodal/agent-tars/package.json
multimodal/agent/package.json
multimodal/agio/package.json
multimodal/benchmark/content-extraction/package.json
multimodal/codeact-agent/package.json
multimodal/config-loader/package.json
multimodal/deep-research-agent/package.json
multimodal/gui-agent/operator-browser/package.json
multimodal/llm-client/package.json
multimodal/llm/package.json
multimodal/mcp-agent-interface/package.json
multimodal/mcp-agent/package.json
multimodal/model-provider/package.json
multimodal/package.json
multimodal/pnpm-toolkit/package.json
multimodal/ui/package.json
multimodal/websites/docs/package.json
multimodal/websites/main/package.json

See [CHANGELOG](https://github.com/bytedance/UI-TARS-desktop/blob/1dfed3086deac2cedc156fad49c33e93785e18d3/multimodal/CHANGELOG.md)

release(agent-tars): release 0.3.0-beta.1

---

multimodal/agent-tars-server/src/api/controllers/queries.ts
multimodal/agent-tars-server/src/api/controllers/sessions.ts
multimodal/agent-tars-server/src/api/index.ts
multimodal/agent-tars-server/src/api/middleware/index.ts
multimodal/agent-tars-server/src/api/middleware/session-restore.ts
multimodal/agent-tars-server/src/api/routes/queries.ts
multimodal/agent-tars-server/src/api/routes/sessions.ts
multimodal/agent-tars-server/src/express.d.ts

1. fix: solve session not found issue when use headless server (introduced from #750 )
2. optimize:  add routing group function,  so a route can mount sessionRestoreMiddleware middleware to use session

feat(agent-tars-server): session read optimization

---

apps/ui-tars/src/renderer/src/components/CountDown/index.tsx
docs/quick-start.md

docs: quick-start.md add links for Volcano Engine's OS Agent

---

multimodal/websites/docs/docs/public/netlify.toml

docs: add new redirects

---

multimodal/websites/docs/docs/public/netlify.toml

docs: update redirects

---

multimodal/websites/docs/docs/en/_meta.json
multimodal/websites/docs/docs/zh/_meta.json
multimodal/websites/docs/src/components/Showcase/index.tsx
multimodal/websites/docs/src/services/dataProcessor.ts

- [fix(agent-tars-docs): make showcase public](https://github.com/bytedance/UI-TARS-desktop/pull/988/commits/7f54ea85b380d5479f8054708a61950818514baf)
- [chore: add showcase entry](https://github.com/bytedance/UI-TARS-desktop/pull/988/commits/403b378efb1f37c8e2c673aa886c5195bab3cac5)
- [chore: enable ?replay=1](https://github.com/bytedance/UI-TARS-desktop/pull/988/commits/361848f4ce50e2b66b891f0e3450b7e2ae0101c9)

docs(agent-tars): make showcase public

---

multimodal/agent-tars-web-ui/src/common/services/apiService.ts
multimodal/agent-tars-web-ui/src/common/services/socketService.ts
multimodal/agent-tars-web-ui/src/sdk/markdown-renderer/components/CodeBlock.tsx
multimodal/agent-tars-web-ui/src/sdk/markdown-renderer/syntax-highlight.css
multimodal/agent-tars-web-ui/src/standalone/app/Layout/Layout.css
multimodal/agent-tars-web-ui/src/standalone/chat/ImagePreview.tsx
multimodal/agent-tars-web-ui/src/standalone/chat/Message/components/MessageGroup.tsx
multimodal/agent-tars-web-ui/src/standalone/chat/Message/components/MessageTimestamp.tsx
multimodal/agent-tars-web-ui/src/standalone/chat/Message/components/MultimodalContent.tsx
multimodal/agent-tars-web-ui/src/standalone/chat/Message/index.tsx
multimodal/agent-tars-web-ui/src/standalone/share/ShareButton.tsx
multimodal/agent-tars-web-ui/src/standalone/share/shareService.ts
multimodal/agent-tars-web-ui/src/standalone/sidebar/ChatSession.tsx
multimodal/agent-tars-web-ui/src/standalone/sidebar/Sidebar.css
multimodal/agent-tars-web-ui/src/standalone/workspace/Workspace.css
multimodal/agent-tars-web-ui/src/standalone/workspace/renderers/BrowserControlRenderer.tsx
multimodal/agent-tars-web-ui/src/standalone/workspace/renderers/ResearchReportRenderer.tsx

Migrate all comments to English by using Agent TARS.

refactor(agent-tars-web-ui): comments

---

multimodal/agent-interface/src/agent.ts

Add `getTools` type as generic method in basic Agent interface.

feat(agent): add  `getTools` type

---

multimodal/agent-server/src/api/controllers/sessions.ts
multimodal/agent-tars/src/agent-tars.ts

This Pull Request completes the last task of **_decoupling Agent Server from Agent TARS_** - moving browser cleanup related work from Agent Server to Agent TARS's `onDispose` Hook

refactor(agent-server): sink dispose logic to agent tars

---

multimodal/tarko/agent-cli/src/config/builder.ts
multimodal/tarko/agent-cli/src/config/paths.ts
multimodal/tarko/agent-cli/src/core/cli.ts

Follows the configuration priority order:
* L0: CLI Arguments (highest priority)
* L1: Workspace Config File  
* L2: Global Workspace Config File
* L3: CLI Config Files
* L4: CLI Remote Config
* L5: CLI Node API Config (lowest priority)

feat(tarko-agent-cli): refine config priority

---

multimodal/tarko/agent-cli/src/core/cli.ts
multimodal/tarko/agent-cli/src/core/commands/start.ts
multimodal/tarko/agent-cli/src/core/options.ts
multimodal/tarko/agent-cli/src/utils/workspace-path.ts

This pull request enhances the `workspace` resolution, supports:
- home directory paths (`~/.workspace`)
- absolute paths  (`/path/to/workspace`)
- relative path  (`./workspace`)
Also,  set the default workspace to `process.cwd()`.

feat(tarko): refine workspace resolution

---

multimodal/agent-tars/core/src/agent-tars.ts
multimodal/agent-tars/core/src/index.ts
multimodal/tarko/agent-server/src/utils/agent-resolver.ts
multimodal/tarko/agent/src/agent/agent.ts
multimodal/tarko/agent/src/index.ts
multimodal/tarko/mcp-agent/src/index.ts
multimodal/tarko/mcp-agent/src/mcp-agent.ts

> [!IMPORTANT]  
> The current implementation is still **_experimental_**
This pull request refines the agent module path resolution in **_Agent Server_**, this handles **npm packages**, **relative paths**, and **directories** more robustly, for dynamically resolved Agents, it is required to use `default export` to export `AgentConstructor`:
```ts
import { Agent } from '@tarko/agent';
export default class MyAgent extends Agent {
static label = 'my-agent';
// ...
}
```
```ts
export * from './my-agent'
export { MyAgent as default } from './my-agent'
```

feat(tarko): refine agent module path resolution

---

multimodal/tarko/agent-cli/src/core/cli.ts

This pull request introduces a minor update to the initialization options for the agent server in the `AgentCLI` class. The change adds support for passing directory information to the server initialization.
* Added the `directories` property from `this.options` to the `agentServerInitOptions` object in `cli.ts`, allowing the agent server to receive directory configuration.

fix(tarko): agent cli should pass directories config

---

multimodal/tarko/agent-server/src/storage/DatabaseStorageProvider.ts
multimodal/tarko/agent-server/src/storage/index.ts
multimodal/tarko/agent-server/src/storage/types.ts
multimodal/tarko/interface/src/index.ts
multimodal/tarko/interface/src/server.ts
multimodal/tarko/interface/src/storage-implementation.ts

This pull request refactors the agent storage implementation type system to improve type safety and code organization. The main changes include:
1. **New Storage Implementation Type System**: 
- Created a new dedicated `storage-implementation.ts` file in the interface package
- Defined comprehensive type unions for different storage implementations (memory, file, sqlite, database)
- Added utility types and type guards for better type checking
2. **Improved Type Safety**:
- Replaced generic `AgentServerStorageOptions` with more specific `AgentStorageImplementation` types
- Updated `DatabaseStorageProvider` to use the new type system
- Enhanced constructor signatures with proper typing
3. **Better Code Organization**:
- Moved storage-related types from server.ts to dedicated …

refactor(tarko): improve agent storage implementation type system

---

multimodal/tarko/agent-web-ui/src/standalone/chat/ChatPanel.tsx

Removes the automatic scrolling behavior from the ChatPanel component in the Tarko agent web UI. This change eliminates the auto-scroll functionality that was triggered when new messages arrived or during processing states.
- Removed the `useEffect` hook that handled automatic scrolling to bottom
- Eliminated scroll position detection logic
- Removed smooth scrolling behavior for new messages
- Simplified the ChatPanel component by removing 23 lines of auto-scroll code
**File Modified:**
- `multimodal/tarko/agent-web-ui/src/standalone/chat/ChatPanel.tsx`
**Code Removed:**
- Auto-scroll `useEffect` that monitored `activeMessages` and `isProcessing`
- Scroll position detection (`isAtBottom` calculation)
- Conditional scrolling logic for user messages and processing states
- Smooth scroll …

feat(tarko): remove auto scroll behavior from ChatPanel

---

multimodal/agent-tars/core/src/agent-tars.ts
multimodal/agent-tars/core/src/filesystem/filesystem-tools-manager.ts
multimodal/agent-tars/core/src/filesystem/index.ts
multimodal/agent-tars/core/tests/filesystem/filesystem-tools-manager.test.ts

Fixes prompt overflow issues caused by the `directory_tree` tool when processing large directories. Implements a `FilesystemToolsManager` that replaces the problematic MCP `directory_tree` tool with a safe version featuring smart filtering and limits.
- **FilesystemToolsManager**: New manager class for filesystem tool registration and safety
- **Safe directory_tree replacement**: Implements depth limits, file count limits, and exclusion patterns
- **Format consistency**: Maintains exact compatibility with original MCP return format
- **Default exclusions**: Automatically excludes common large directories (`node_modules`, `.git`, `dist`, etc.)
- **Focused tests**: Simple, maintainable test coverage for core functionality
**Original MCP usage:**
```json
{"path": "/some/directory"}
```
**Our …

fix(agent-tars): `directory_tree` causes context overflow (close: #969)

---

multimodal/package.json

Add build:omni-tars script to package.json for building omni-tars packages and dependencies.

chore(scripts): add build:omni-tars script

---

multimodal/tarko/agent-web-ui/src/common/state/actions/eventProcessor.ts

Adds session validation to prevent cross-session content bleeding in workspace panel.
- Added `shouldUpdatePanelContent` helper function to validate sessionId consistency
- Updated all event handlers that modify `activePanelContentAtom` to use session validation
- Prevents panel updates when event sessionId doesn't match active session
- Skips panel updates during replay mode
The issue occurred because `processEventAction` updated workspace panel content for any session event, regardless of whether it matched the current active session. This caused incorrect content display when switching between sessions.
The fix validates that:
1. There is an active session
2. Event sessionId matches activeSessionId  
3. Not in replay mode (which handles its own content)
- ✅ Panel content only updates …

fix(tarko): validate session consistency before panel updates

---

multimodal/tarko/agent-server/src/api/controllers/sessions.ts

This PR implements a smart relevance-based scoring system for workspace search results to improve user experience when searching for files and directories.
**Problem**: When searching for package names like `@tarko/agent`, the most relevant directory (`@tarko/agent/`) was appearing lower in search results, buried under deeply nested files that contained the search term.
**Solution**: Implemented a multi-dimensional scoring algorithm that prioritizes search results based on:
- **Exact matches** (1000 points) - Perfect name matches get highest priority
- **Name prefix matches** (800 points) - Names starting with query
- **Name suffix matches** (700 points) - Specifically solves `@tarko/agent` search issue
- **Path suffix matches** (600 points) - Paths ending with query
- **Name contains** …

feat(tarko): improve search result relevance scoring

---

multimodal/tarko/agent-server/src/api/controllers/sessions.ts
multimodal/tarko/agent-server/src/api/controllers/system.ts
multimodal/tarko/agent-server/src/api/routes/system.ts
multimodal/tarko/agent-server/src/core/AgentSession.ts
multimodal/tarko/agent-server/src/server.ts
multimodal/tarko/agent-server/src/storage/SQLiteStorageProvider.ts
multimodal/tarko/agent-server/src/storage/types.ts
multimodal/tarko/agent-web-ui/src/common/hooks/useDarkMode.ts
multimodal/tarko/agent-web-ui/src/common/services/apiService.ts
multimodal/tarko/agent-web-ui/src/standalone/chat/ActionBar.tsx
multimodal/tarko/agent-web-ui/src/standalone/chat/MessageInput/MessageInput.tsx
multimodal/tarko/agent-web-ui/src/standalone/chat/MessageInput/MessageInputField.tsx
multimodal/tarko/agent-web-ui/src/standalone/chat/ModelSelector.tsx
multimodal/tarko/agent/src/agent/runner/llm-processor.ts

Adds runtime model switching capability to Tarko chat interface. Users can now switch between different AI models within individual chat sessions.
**Close: #1057**
- Extended `SessionMetadata` with `modelConfig` field for session-specific model settings
- Added database migration logic for backward compatibility
- New API endpoints: `GET /api/v1/models` and `POST /api/v1/sessions/model`
- Session-aware agent creation with model validation
- **ModelSelector component**: Dropdown interface with animations
- **Conditional rendering**: Only shows when multiple providers are configured
- **ActionBar integration**: Seamlessly integrated into existing chat UI
✅ **Session isolation** - Each chat session can use different models  
✅ **Persistent configuration** - Model choices persist across …

feat(tarko): support switching model at runtime (close: #1057)

---

multimodal/tarko/agent-interface/src/agent-instance.ts
multimodal/tarko/agent-interface/src/agent.ts
multimodal/tarko/agent/src/agent/base-agent.ts
multimodal/tarko/agent/src/agent/runner/loop-executor.ts

Adds a new lifecycle hook, `onEachAgentLoopEnd`, to the agent loop system, enabling custom logic execution at the end of each agent loop iteration.

feat(tarko-agent): add `onEachAgentLoopEnd` hook

---

multimodal/tarko/agent-web-ui/src/common/utils/formatters.ts
multimodal/tarko/agent-web-ui/src/standalone/workspace/renderers/CommandResultRenderer.tsx

Based on #1119 and #1120, this PR improved tool renderer mappings for O TARS integration and enhance command result handling with exit code support.

feat(tarko): improve tool renderer mappings and command result handling

---

multimodal/tarko/agent-web-ui/src/common/services/SearchService.ts
multimodal/tarko/agent-web-ui/src/sdk/markdown-renderer/MarkdownRenderer.tsx
multimodal/tarko/agent-web-ui/src/sdk/markdown-renderer/components/CodeBlock.tsx
multimodal/tarko/agent-web-ui/src/sdk/markdown-renderer/components/Headings.tsx
multimodal/tarko/agent-web-ui/src/sdk/markdown-renderer/components/Table.tsx
multimodal/tarko/agent-web-ui/src/sdk/markdown-renderer/components/TextElements.tsx
multimodal/tarko/agent-web-ui/src/standalone/chat/Message/components/ThinkingToggle.tsx
multimodal/tarko/agent-web-ui/src/standalone/chat/MessageInput/MessageInput.tsx
multimodal/tarko/agent-web-ui/src/standalone/workspace/renderers/LinkReaderRenderer.tsx

Based on #1119 and #1120, fixed the `link_reader` render regression issue, also, refactor type and markdown renderer

fix(tarko): `link_reader` render regression issue

---

multimodal/tarko/agent-web-ui/src/common/services/SearchService.ts
multimodal/tarko/agent-web-ui/src/common/utils/formatters.ts
multimodal/tarko/agent-web-ui/src/sdk/markdown-renderer/MarkdownRenderer.tsx
multimodal/tarko/agent-web-ui/src/sdk/markdown-renderer/components/CodeBlock.tsx
multimodal/tarko/agent-web-ui/src/sdk/markdown-renderer/components/Headings.tsx
multimodal/tarko/agent-web-ui/src/sdk/markdown-renderer/components/Table.tsx
multimodal/tarko/agent-web-ui/src/sdk/markdown-renderer/components/TextElements.tsx
multimodal/tarko/agent-web-ui/src/standalone/chat/Message/components/ThinkingToggle.tsx
multimodal/tarko/agent-web-ui/src/standalone/chat/MessageInput/MessageInput.tsx
multimodal/tarko/agent-web-ui/src/standalone/workspace/renderers/CommandResultRenderer.tsx
multimodal/tarko/agent-web-ui/src/standalone/workspace/renderers/LinkReaderRenderer.tsx

Thanks to #1119 and #1120, we have made a good adaptation for O TARS, see:
- #1129
- #1126

feat(tarko): o tars adaptation

---

multimodal/omni-tars/core/src/ComposableAgent.ts
multimodal/omni-tars/core/src/environments/code.ts
multimodal/omni-tars/omni-agent/package.json
multimodal/omni-tars/omni-agent/src/index.ts
multimodal/omni-tars/omni-agent/tarko.config.ts
multimodal/pnpm-lock.yaml

improves the o-agent configuration and performance optimization with the following key changes:
- **Fix plugin logging**: Corrected typo in ComposableAgent.ts where plugin names were not properly displayed in logs
- **Enhanced home directory instructions**: Updated code environment instructions to be more explicit about directory creation and project organization
- **Performance optimization**: Reduced maxTokens from 64000 to 32768
- **Configuration improvements**: Updated tarko.config.ts to use volcengine provider by default with proper environment variable handling

feat(o-agent): improve configuration and performance optimization

---

multimodal/gui-agent/action-parser/src/actionParser.ts
multimodal/gui-agent/agent-sdk/src/SeedGUIAgent.ts
multimodal/gui-agent/agent-sdk/src/SeedGUIAgentToolCallEngine.ts
multimodal/gui-agent/operator-browser/src/browser-operator.ts

feat(gui-agent): construct operator on demand

---

multimodal/tarko/agent-server/src/utils/config-sanitizer.ts
multimodal/tarko/agent-web-ui/src/standalone/sidebar/AgentConfigViewer.tsx
multimodal/tarko/agent-web-ui/src/standalone/sidebar/ToolBar.tsx

Adds a minimal agent configuration viewer

feat(tarko): add agent config viewer

---

multimodal/tarko/agent-cli/README.md

Improve agent-cli README by translating from Chinese to English and enhancing documentation structure with better developer experience.

docs(tarko): improve agent-cli documentation

---

multimodal/tarko/agent-server/README.md
multimodal/tarko/agent-server/src/api/controllers/oneshot.ts
multimodal/tarko/agent-server/src/api/controllers/sessions.ts
multimodal/tarko/agent-server/src/api/controllers/system.ts
multimodal/tarko/agent-server/src/api/middleware/session-restore.ts
multimodal/tarko/agent-server/src/core/AgentSession.ts
multimodal/tarko/agent-server/src/server.ts
multimodal/tarko/agent-server/src/services/ShareService.ts
multimodal/tarko/agent-server/src/storage/DatabaseStorageProvider.ts
multimodal/tarko/agent-server/src/storage/FileStorageProvider.ts
multimodal/tarko/agent-server/src/storage/MemoryStorageProvider.ts
multimodal/tarko/agent-server/src/storage/SQLiteStorageProvider.ts
multimodal/tarko/agent-server/src/storage/compatibility.ts
multimodal/tarko/agent-server/src/storage/types.ts
multimodal/tarko/agent-server/src/utils/share.ts
multimodal/tarko/agent-server/tests/SQLiteStorageProvider.test.ts
multimodal/tarko/agent-web-ui/src/common/hooks/useSession.ts
multimodal/tarko/agent-web-ui/src/common/services/apiService.ts
multimodal/tarko/agent-web-ui/src/common/state/actions/eventProcessors/handlers/AgentRunHandler.ts
multimodal/tarko/agent-web-ui/src/common/state/actions/sessionActions.ts
multimodal/tarko/agent-web-ui/src/common/state/atoms/session.ts
multimodal/tarko/agent-web-ui/src/common/types/env.d.ts
multimodal/tarko/agent-web-ui/src/common/types/index.ts
multimodal/tarko/agent-web-ui/src/standalone/sidebar/ChatSession.tsx
multimodal/tarko/agent-web-ui/src/standalone/sidebar/SessionItem.tsx
multimodal/tarko/interface/src/server.ts

Completely rewrite the semantics of **SessionMetada**, replaced it by **SessionItemInfo**, it's to avoid **_stupid `sessionMetadata.metadata`_** makes searching difficult and semantic understanding confusing
Example:
```diff
- runOptions.model = this.sessionMetadata.metadata.modelConfig.modelId;
+ runOptions.model = this.sessionItemInfo.metadata.modelConfig.modelId;
```

refactor(agent-server): refine session item info naming

---

multimodal/tarko/agent-server/src/api/controllers/sessions.ts
multimodal/tarko/agent-web-ui/src/common/services/apiService.ts
multimodal/tarko/agent-web-ui/src/common/state/actions/sessionActions.ts

Update agent info when creating session. In the implementation, the **agent name** is saved to the **session item info** when _createSession_, and returned to the front end to update this status.

fix(tarko): display "Unknown Agent" at initial rendering

---

multimodal/tarko/agent-web-ui/src/common/components/JsonRenderer.tsx
multimodal/tarko/agent-web-ui/src/common/sdk.md
multimodal/tarko/agent-web-ui/src/common/state/actions/connectionActions.ts
multimodal/tarko/agent-web-ui/src/common/state/actions/sessionActions.ts
multimodal/tarko/agent-web-ui/src/common/state/atoms/contextualSelector.ts
multimodal/tarko/agent-web-ui/src/sdk/code-editor/MonacoCodeEditor.css
multimodal/tarko/agent-web-ui/src/standalone/chat/ContextualSelector.tsx
multimodal/tarko/agent-web-ui/src/standalone/chat/Message/components/MessageGroup.tsx
multimodal/tarko/agent-web-ui/src/standalone/chat/Message/components/SkeletonLoader.tsx
multimodal/tarko/agent-web-ui/src/standalone/chat/Message/components/ThinkingAnimation.tsx
multimodal/tarko/agent-web-ui/src/standalone/chat/MessageInput/MessageAttachments.tsx
multimodal/tarko/agent-web-ui/src/standalone/navbar/Navbar.css
multimodal/tarko/agent-web-ui/src/standalone/sidebar/AgentConfigViewer.tsx
multimodal/tarko/agent-web-ui/src/standalone/sidebar/ToolBar.tsx
multimodal/tarko/agent-web-ui/src/standalone/workspace/Workspace.css
multimodal/tarko/agent-web-ui/src/standalone/workspace/WorkspaceDetail.tsx
multimodal/tarko/agent-web-ui/src/standalone/workspace/components/RawModeRenderer.tsx
multimodal/tarko/agent-web-ui/src/standalone/workspace/renderers/CommandResultRenderer.tsx

- Do not update model info from agent options (Remaining issues: Model select does not work)
- Remove `sessionMetadataCache`
- Refine Web UI code format.

refactor(tarko-web-ui): some enhancements

---

multimodal/tarko/agent-web-ui/src/standalone/workspace/renderers/CommandResultRenderer.tsx

Fully compatible with `str_replace_editor`, including success and failure cases.

feat(tarko): fully compatible with `str_replace_editor`

---

multimodal/tarko/agent-web-ui/src/common/utils/formatters.ts

Refactored `TOOL_TO_RENDERER_MAP` from static mapping to flexible condition-based system. Replaced hardcoded map with configurable array supporting both static mappings and dynamic function conditions, enabling easier maintenance and extensibility without if-else chains.

refactor(tarko): flexible condition-based system for tool renderer

---

multimodal/omni-tars/gui-agent/src/index.ts

feat(omni-gui-agent): migrate from local browser to AIO sandbox browser

---

multimodal/tarko/agent-web-ui/src/standalone/chat/ChatPanel.tsx
multimodal/tarko/agent-web-ui/src/standalone/chat/components/ScrollToBottomButton.tsx
multimodal/tarko/agent-web-ui/src/standalone/chat/hooks/useAutoScroll.ts

Implement intelligent auto-scroll functionality for Chat UI to enhance user experience during Agent multi-turn conversations.
**Problem**: When Agent generates streaming content that exceeds screen height, new content becomes invisible to users, requiring manual scrolling.
**Solution**: Smart bottom-attach scrolling with user interaction detection:
- Auto-scrolls to bottom when new messages arrive
- Detects manual user scrolling and respects user intent
- Shows floating scroll-to-bottom indicator when user has scrolled up
- Automatically resumes auto-scroll after user inactivity timeout (2s)
- Smooth animations and responsive user experience
**Key Features**:
- `useAutoScroll` hook for intelligent scroll management
- `ScrollToBottomButton` component with gradient backdrop and animations
- …

feat(tarko): add intelligent auto-scroll to chat UI

---

multimodal/omni-tars/core/src/environments/computer.ts

feat(omni-gui-agent): add navigate and navigate_back action space

---

multimodal/omni-tars/code-agent/src/index.ts
multimodal/omni-tars/core/src/environments/code.ts
multimodal/omni-tars/mcp-agent/src/index.ts
multimodal/omni-tars/mcp-agent/src/tools/linkReader.ts
multimodal/omni-tars/omni-agent/src/index.ts
multimodal/omni-tars/omni-agent/tarko.config.ts

feat(o-agent): modify linkreader

---

multimodal/tarko/agent-web-ui/src/standalone/workspace/renderers/BrowserControlRenderer.tsx

Refactor GUI agent renderer component in Tarko browser control renderer.

refactor(tarko): gui agent renderer

---

multimodal/omni-tars/omni-agent/src/index.ts

Add code server entry to workspace navigation and update VNC link with autoconnect parameter.

feat(o-tars): add code server entry

---

multimodal/omni-tars/omni-agent/src/index.ts

Update O-TARS agent to use new icon in configuration.

feat(o-tars): using new icon

---

multimodal/tarko/agent-web-ui/src/standalone/chat/Message/components/ToolCalls.tsx

Add compatibility for O-TARS tool call block in Tarko chat message components.

feat(tarko): compatible with o-tars' tool call block

---

multimodal/tarko/agent-web-ui/src/common/state/actions/eventProcessors/handlers/MessageHandler.ts
multimodal/tarko/agent-web-ui/src/common/state/actions/eventProcessors/index.ts

Adds streaming thinking rendering support to `tarko-web-ui`.

feat(tarko-web-ui): streaming thinking rendering support

---

multimodal/tarko/agent-web-ui/src/common/components/TooltipConfig.ts
multimodal/tarko/agent-web-ui/src/standalone/chat/Message/components/MessageFooter.tsx
multimodal/tarko/agent-web-ui/src/standalone/share/ShareButton.tsx
multimodal/tarko/agent-web-ui/src/standalone/workspace/renderers/browser-control/StrategySwitch.tsx

Extracted duplicate `tooltipProps` configuration from three components into a shared `getTooltipProps` utility function in `common/components/TooltipConfig.ts`.

refactor(tarko-web-ui): extract tooltip props to shared config

---

multimodal/tarko/agent-web-ui/src/standalone/workspace/renderers/BrowserControlRenderer.tsx
multimodal/tarko/agent-web-ui/src/standalone/workspace/renderers/browser-control/ScreenshotDisplay.tsx
multimodal/tarko/agent-web-ui/src/standalone/workspace/renderers/browser-control/StrategySwitch.tsx

Improve gui agent screenshot ui layout and placeholder

feat(tarko): improve gui agent screenshot ui layout and placeholder

---

multimodal/agent-tars/core/src/agent-tars.ts
multimodal/omni-tars/omni-agent/src/index.ts

This pull request introduces changes to the layout configuration options for both the `AgentTARS` and `OmniTARSAgent` classes.

chore(agent): update default layout config

---

multimodal/tarko/agent-web-ui/src/sdk/markdown-renderer/MarkdownRenderer.tsx
multimodal/tarko/agent-web-ui/src/sdk/markdown-renderer/components/Headings.tsx
multimodal/tarko/agent-web-ui/src/sdk/markdown-renderer/components/TextElements.tsx
multimodal/tarko/agent-web-ui/src/sdk/markdown-renderer/context/MarkdownThemeContext.tsx
multimodal/tarko/agent-web-ui/src/sdk/markdown-renderer/hooks/useMarkdownTheme.ts

**Optimized markdown theme architecture** with React Context and memoization for better performance and maintainability.
```typescript
// Every component calls useMarkdownTheme()
export const Paragraph = ({ children }) => {
const { colors } = useMarkdownTheme(); // 🚨 Duplicate calculation
return <p className={`${colors.text.primary} ...`}>{children}</p>;
};
```
```typescript
// Styles computed once, shared via context
export const Paragraph = ({ children }) => {
const styles = useTextStyles(); // ✅ Pre-computed, cached
return <p className={styles.paragraph}>{children}</p>;
};
```
- **MarkdownThemeProvider**: Computes styles once at the top level
- **Shared Context**: All components access the same pre-computed styles
- **Zero Duplication**: Eliminates redundant hook calls across …

refactor(tarko-web-ui): centralize markdown theme architecture

---

multimodal/omni-tars/core/src/environments/prompt_t5.ts
multimodal/omni-tars/gui-agent/src/GUIAgentT5Adapter.ts
multimodal/omni-tars/gui-agent/src/GuiToolCallEngineProvider.ts

feat(o-gui-agent): support navigate action for new model

---

multimodal/omni-tars/omni-agent/src/index.ts
multimodal/tarko/agent-web-ui/src/standalone/chat/Message/components/ToolCalls.tsx

This pull request introduces a minor configuration update to the `OmniTARSAgent` class. The change enables streaming of tool call events, which may improve real-time responsiveness when tools are invoked.

feat(o-agent): enable `enableStreamingToolCallEvents`

---

multimodal/gui-agent/operator-browser/src/browser-operator.ts
multimodal/omni-tars/gui-agent/src/GuiAgentPlugin.ts

**Problem:**
The GUI Agent was encountering `Tool "browser_vision_control" not found` errors due to improper operator type handling and unconditional URL content addition in environment events.
**Solution:**
This PR implements a temporary fix with the following changes:
1. **Type-safe operator handling**: Added `instanceof BrowserOperator` check before calling `getMeta()` method to ensure the operator supports browser-specific functionality
2. **Conditional URL content**: Modified the environment event content generation to only include URL information when it's actually available, preventing empty or undefined URL strings from being added to the content array
3. **Import addition**: Added proper import for `BrowserOperator` type to enable runtime type checking
**Key Changes:**
- Modified …

feat(o-gui-agent): temporary solution for getting metadata when screenshot

---

multimodal/omni-tars/core/README.md
multimodal/omni-tars/omni-agent/src/index.ts
multimodal/omni-tars/omni-agent/tarko.config.ts
multimodal/tarko/agent-cli/src/core/options.ts

chore(o-agent): update display texts

---

multimodal/tarko/agent-web-ui/src/common/hooks/useSession.ts
multimodal/tarko/agent-web-ui/src/common/state/actions/eventProcessors/handlers/AgentRunHandler.ts
multimodal/tarko/agent-web-ui/src/common/state/actions/eventProcessors/handlers/MessageHandler.ts
multimodal/tarko/agent-web-ui/src/common/state/actions/eventProcessors/handlers/ToolHandler.ts
multimodal/tarko/agent-web-ui/src/common/state/actions/eventProcessors/utils/panelContentUpdater.ts
multimodal/tarko/agent-web-ui/src/common/state/actions/sessionActions.ts
multimodal/tarko/agent-web-ui/src/common/state/atoms/ui.ts

Implements comprehensive session state isolation to prevent state leakage between different chat sessions.

feat(tarko): implement session state isolation

---

multimodal/omni-tars/core/src/environments/prompt_t5.ts
multimodal/omni-tars/core/src/utils/streamingParserT5/index.ts
multimodal/omni-tars/omni-agent/tarko.config.ts

add some new features for o agent
1. support native thinking mode,  add env variable to use
```bash
export NATIVE_THINKING=true
```
3. support dynamic think_token,  change think_token for runtime
```bash
export THINK_TOKEN='your think token here'
```

feat(o-agent): native think

---

multimodal/gui-agent/operator-aio/src/AIOComputer.ts
multimodal/gui-agent/operator-aio/src/AIOHybridOperator.ts

feat(gui-agent): delay 1s before screenshot on aio hybried operator

---

multimodal/tarko/agent-web-ui/src/sdk/markdown-renderer/components/CodeBlock.tsx
multimodal/tarko/agent-web-ui/src/standalone/workspace/renderers/LinkReaderRenderer.tsx

Redesigned `LinkReaderRenderer` with a more elegant and minimal design that better matches the application's clean aesthetic.

feat(tarko): refine LinkReaderRenderer

---

multimodal/tarko/agent-web-ui/src/sdk/markdown-renderer/utils/linkPreprocessor.ts

Improves `MarkdownRenderer` link parsing to handle additional edge cases that were not covered in PR #1358.
- **Code blocks**: URLs in ``` and ` blocks are no longer processed
- **HTML links**: URLs in `<>` syntax are preserved
- **Nested brackets**: URLs in `[url]` format avoid creating `[[url](url)]`
- **Trailing punctuation**: Properly excludes `.`, `,`, `;`, `:`, `!`, `?` from URLs
```
<https://example.com>页面 → <[https://example.com>](https://example.com>)页面 ❌
[https://example.com]页面 → [[https://example.com](https://example.com)]页面 ❌
`https://example.com页面` → `[https://example.com页面](https://example.com页面)` ❌
https://example.com.页面 → [https://example.com.](https://example.com.)页面 ❌
```
```
<https://example.com>页面 → <https://example.com>页面 ✅
[https://example.com]页面 → …

fix(tarko): improve markdown link parsing edge cases

---

multimodal/tarko/agent-web-ui/src/sdk/markdown-renderer/components/CodeBlock.tsx

Optimize the tight Code Block rendering space.

chore(tarko): enhance code block spacing

---

multimodal/tarko/agent-web-ui/src/standalone/chat/Message/components/MessageGroup.tsx
multimodal/tarko/agent-web-ui/src/standalone/chat/Message/components/ThinkingAnimation.tsx

Redesigned `ThinkingAnimation` component with elegant black-white-gray color scheme and fast left-to-right gradient transition. Removed complex phase-based color states and simplified the component for better visual consistency.

feat(tarko): refine thinking animation

---

multimodal/pnpm-lock.yaml
multimodal/tarko/agent-server/package.json
multimodal/tarko/agent-server/src/services/ShareService.ts
multimodal/tarko/agent-server/src/utils/share.ts
multimodal/tarko/agent-server/src/utils/slug-generator.ts

Significantly improves slug generation for multilingual content, especially Chinese text, by replacing basic fallbacks with professional transliteration.
**Before**: Chinese queries like `"这是在哪儿"` resulted in meaningless URLs:
```
/share/untitled-session-abc123?replay=1  ❌
```
**After**: Same query now generates semantic, readable URLs:
```
/share/zhe-shi-zai-na-er-17361c?replay=1  ✅
```
- **Added**: `transliteration` library for accurate pinyin conversion
- **Enhanced**: Technical term mapping (`代码` → `code`, `文件` → `file`)
- **Supports**: Chinese, Japanese, Korean, Cyrillic, and more
```
LLM Success → Use LLM result
↓ Fails
English Words → Extract and use English
↓ None
Transliteration → Professional conversion (NEW)
↓ Fails  
Language Labels → chinese-query, japanese-query, etc.
↓ …
```

feat(tarko): enhance slug generation with multilingual support

---

multimodal/tarko/agent-web-ui/src/standalone/chat/ChatPanel.tsx
multimodal/tarko/agent-web-ui/src/standalone/chat/components/EmptyState.tsx
multimodal/tarko/agent-web-ui/src/standalone/chat/components/SessionCreatingState.tsx
multimodal/tarko/agent-web-ui/src/standalone/workspace/WorkspaceContent.tsx

Improved the session UI to be more elegant and fixed the issue where "Start a conversation" state appears after users send messages.
**Changes:**
- Simplified `SessionCreatingState` component with minimal, clean design
- Removed excessive content and animations from "Preparing your session" UI
- Fixed `ChatPanel` logic to prevent `EmptyState` from showing when processing messages
- Removed unused imports
**Before:** Cluttered "Preparing your session" UI with too much content
**After:** Clean, minimal loading state that appears briefly during session creation

feat(tarko): refine all empty state

---

multimodal/tarko/agent-web-ui/src/sdk/code-editor/CodeEditor.css
multimodal/tarko/agent-web-ui/src/sdk/code-editor/CodeEditor.tsx
multimodal/tarko/agent-web-ui/src/sdk/code-editor/CodeEditorHeader.tsx
multimodal/tarko/agent-web-ui/src/sdk/code-editor/MonacoCodeEditor.tsx
multimodal/tarko/agent-web-ui/src/sdk/code-editor/index.ts
multimodal/tarko/agent-web-ui/src/standalone/workspace/renderers/FileResultRenderer.tsx

Clean up code editor components by removing performance bottlenecks and fixing UX issues:
**Key Changes:**
- **Removed framer-motion animations** - eliminated stuttering during code interactions
- **Simplified tooltip system** - removed complex hover tooltip with file path/size display
- **Fixed copy button behavior** - removed inappropriate download functionality, now properly copies code to clipboard
- **Consolidated header logic** - shared `CodeEditorHeader` component reduces duplication

refactor(tarko): simplify code editor components

---

multimodal/gui-agent/operator-aio/src/AIOBrowser.ts

Implement a two-phase approach for detecting active pages:
1. First attempt direct visibility check without waiting
2. Fall back to waitForFunction with increased timeout (3000ms)
This change improves reliability by:
- Reducing unnecessary waiting time when pages are immediately visible
- Increasing timeout from 1000ms to 3000ms to prevent TimeoutError
- Adding better error handling and logging
- Optimizing getActiveUrl to reuse getActivePage logic

feat(gui-agent): improve page visibility detection in AIOBrowser

---

multimodal/gui-agent/operator-aio/package.json
multimodal/gui-agent/operator-aio/src/AIOComputer.ts
multimodal/gui-agent/operator-aio/test/aioComputer.test.ts
multimodal/omni-tars/code-agent/package.json
multimodal/omni-tars/gui-agent/package.json
multimodal/pnpm-lock.yaml

This pull request updates the sandbox SDK from version 0.0.3 to 0.0.5 and adapts the gui-agent operator to work with the new SDK version. The changes include:
- Updated sandbox SDK dependency to version 0.0.5 across multiple packages
- Modified AIOComputer.ts to adapt to API changes in the new SDK version

feat(o-agent): update sandbox sdk and gui-agent operator

---

multimodal/gui-agent/shared/src/types/actions.ts

feat(gui-agent): add mobile actions into GUIAction

---

multimodal/websites/docs/docs/en/api/_meta.json
multimodal/websites/docs/docs/en/api/runtime/_meta.json
multimodal/websites/docs/docs/en/api/runtime/agent-api.md
multimodal/websites/docs/docs/en/sdk/mcp-agent/core.md
multimodal/websites/docs/docs/zh/api/_meta.json
multimodal/websites/docs/docs/zh/api/runtime/_meta.json
multimodal/websites/docs/docs/zh/api/runtime/agent-api.md
multimodal/websites/docs/docs/zh/sdk/mcp-agent/core.md

Add comprehensive documentation for `@tarko/mcp-agent` core functionality including API reference, configuration examples, and best practices for both Chinese and English versions.

docs: add `@tarko/mcp-agent`

---

multimodal/websites/docs/docs/en/api/runtime/agent-api.md
multimodal/websites/docs/docs/zh/api/runtime/agent-api.md

Added API documentation for the Tarko Agent API

docs(agent-tars): agent api documentation

---

multimodal/gui-agent/shared/package.json
multimodal/gui-agent/shared/src/base/index.ts
multimodal/gui-agent/shared/src/base/operator.ts
multimodal/gui-agent/shared/src/base/parser.ts
multimodal/gui-agent/shared/src/types/agents.ts
multimodal/pnpm-lock.yaml

Add new base abstractions for GUI Agent including Operator and Parser classes. Create type definitions for agent interactions in agents.ts with proper documentation. Update package dependencies and exports to support the new architecture.

feat(gui-agent): refactor GUI Agent APIs with improved abstractions

---

multimodal/gui-agent/shared/src/base/parser.ts

refactor(gui-agent): add JSDoc comments in BaseActionParser

---

multimodal/agent-tars/core/README.md
multimodal/agent-tars/core/src/agent-tars.ts
multimodal/agent-tars/core/src/browser/browser-manager.ts
multimodal/agent-tars/core/src/initializers/agent-tars-initializer.ts
multimodal/agent-tars/core/src/initializers/index.ts
multimodal/agent-tars/core/src/shared/config-utils.ts
multimodal/agent-tars/core/src/types.ts
multimodal/agent-tars/core/src/utils/index.ts
multimodal/agent-tars/core/src/utils/resource-cleaner.ts
multimodal/agent-tars/core/src/utils/tool-logger.ts

This PR significantly refactors the `@agent-tars/core` package to improve code architecture, maintainability, and documentation quality. The main goal was to address code quality issues while maintaining full backward compatibility.

refactor(agent-tars): improve code architecture and docs

---

multimodal/websites/docs/docs/zh/guide/basic/mcp.mdx

docs: correct typo in mcp documentation

---

multimodal/gui-agent/operator-nutjs/.gitignore
multimodal/gui-agent/operator-nutjs/README.md
multimodal/gui-agent/operator-nutjs/examples/test-runner.ts
multimodal/gui-agent/operator-nutjs/package.json
multimodal/gui-agent/operator-nutjs/rslib.config.ts
multimodal/gui-agent/operator-nutjs/src/NutJSOperator.ts
multimodal/gui-agent/operator-nutjs/src/index.ts
multimodal/gui-agent/operator-nutjs/tsconfig.json
multimodal/gui-agent/operator-nutjs/vitest.config.mts
multimodal/pnpm-lock.yaml

refactor(gui-agent): update nut-js operator with refactored api

---

multimodal/tarko/agent-ui/src/common/utils/modelUtils.ts
multimodal/tarko/agent-ui/src/standalone/navbar/ModelSelector.tsx

Unify and simplify model display logic across `@tarko/agent-ui` components with a more elegant approach.

refactor(tarko-agent-ui): unify model display logic

---

multimodal/tarko/agent-ui/src/common/components/LoadingSpinner.tsx
multimodal/tarko/agent-ui/src/sdk/dialog/ConfirmDialog.tsx
multimodal/tarko/agent-ui/src/sdk/markdown-renderer/components/Image.tsx
multimodal/tarko/agent-ui/src/standalone/chat/Message/components/ActionButton.tsx
multimodal/tarko/agent-ui/src/standalone/chat/Message/components/ReportFileEntry.tsx
multimodal/tarko/agent-ui/src/standalone/chat/Message/components/SkeletonLoader.tsx
multimodal/tarko/agent-ui/src/standalone/chat/Message/components/ThinkingAnimation.tsx
multimodal/tarko/agent-ui/src/standalone/chat/Message/components/ToggleButton.tsx
multimodal/tarko/agent-ui/src/standalone/chat/Message/components/ToolCalls.tsx
multimodal/tarko/agent-ui/src/standalone/chat/MessageInput/ChatInput.tsx
multimodal/tarko/agent-ui/src/standalone/chat/components/EmptyState.tsx
multimodal/tarko/agent-ui/src/standalone/chat/components/OfflineBanner.tsx
multimodal/tarko/agent-ui/src/standalone/chat/components/ScrollToBottomButton.tsx
multimodal/tarko/agent-ui/src/standalone/chat/components/SessionCreatingState.tsx
multimodal/tarko/agent-ui/src/standalone/navbar/ModelSelector.tsx
multimodal/tarko/agent-ui/src/standalone/navbar/Navbar.tsx
multimodal/tarko/agent-ui/src/standalone/replay/ReplayControlPanel.tsx
multimodal/tarko/agent-ui/src/standalone/share/ShareButton.tsx
multimodal/tarko/agent-ui/src/standalone/sidebar/LayoutSwitchButton.tsx
multimodal/tarko/agent-ui/src/standalone/sidebar/SessionItem.tsx
multimodal/tarko/agent-ui/src/standalone/sidebar/SessionSearch.tsx
multimodal/tarko/agent-ui/src/standalone/sidebar/ToolBar.tsx
multimodal/tarko/agent-ui/src/standalone/workspace/WorkspaceDetail.tsx
multimodal/tarko/agent-ui/src/standalone/workspace/components/FullscreenModal.tsx
multimodal/tarko/agent-ui/src/standalone/workspace/components/ShareButton.tsx
multimodal/tarko/agent-ui/src/standalone/workspace/components/WorkspaceHeader.tsx
multimodal/tarko/agent-ui/src/standalone/workspace/renderers/LinkRenderer.tsx
multimodal/tarko/agent-ui/src/standalone/workspace/renderers/generic/components/OperationHeader.tsx
multimodal/tarko/agent-ui/src/standalone/workspace/renderers/generic/components/StatusIndicator.tsx

Removed redundant and unnecessary `framer-motion` animations across Agent UI components to improve performance and reduce complexity while maintaining essential interactive feedback.

refactor(tarko-agent-ui): remove redundant motion animations

---

multimodal/pnpm-lock.yaml
multimodal/tarko/agent-ui/package.json
multimodal/tarko/agent-ui/src/common/components/MuiDialog.tsx
multimodal/tarko/agent-ui/src/sdk/dialog/ConfirmDialog.tsx
multimodal/tarko/agent-ui/src/sdk/markdown-renderer/components/ImageModal.tsx
multimodal/tarko/agent-ui/src/standalone/chat/ImagePreview.tsx
multimodal/tarko/agent-ui/src/standalone/navbar/AboutModal.tsx
multimodal/tarko/agent-ui/src/standalone/share/ShareModal.tsx
multimodal/tarko/agent-ui/src/standalone/sidebar/AgentConfigViewer.tsx

Replace `@headlessui/react` with simplified `@mui/material` Dialog component to reduce dependencies and maintain consistency.

refactor(tarko-agent-ui): remove `@headlessui/react`

---

multimodal/tarko/agent-ui/rsbuild.config.ts
multimodal/tarko/agent-ui/src/common/constants/index.ts
multimodal/tarko/agent-ui/src/config/config-loader.ts
multimodal/tarko/agent-ui/src/config/web-ui-config.ts
multimodal/tarko/agent-ui/src/config/webui-config-provider.tsx

1. fix env inject issues for web config load

fix(tarko-agent-ui): config issues

---

multimodal/gui-agent/shared/src/types/actions.ts

chore(gui-agent): add swipe action for gui actions

---

multimodal/tarko/agent-cli/README.md

Optimized `@tarko/agent-cli` README.md according to requirements:
- Updated title from "Agent CLI" to "Tarko Agent CLI"
- Added NPM link for Agent Kernel (`@tarko/agent`)
- Removed Environment Variables section
- Simplified Custom Development section to "Coming soon"
- Removed Deployment and Troubleshooting sections
- Added NPM links to all packages in API Reference section

docs(tarko-agent-cli): optimize README.md

---

multimodal/tarko/agent/src/agent/base-agent.ts
multimodal/tarko/agent/src/agent/index.ts
multimodal/websites/tarko/docs/en/guide/advanced/agent-hooks.mdx
multimodal/websites/tarko/docs/zh/guide/advanced/agent-hooks.mdx

Refine `guide/advanced/agent-hooks.mdx`

docs(tarko): refine agent hooks documentation

---

multimodal/websites/tarko/docs/en/api/agent.mdx
multimodal/websites/tarko/docs/zh/api/agent.mdx

Fix `AgentOptions` property names in API docs to match source code.

docs(tarko): refactor agent options 

---

multimodal/websites/tarko/docs/zh/examples/getting-started.mdx

Completed the missing Chinese examples documentation by translating and modernizing the English version.

docs(tarko): complete zh getting-started examples

---

multimodal/tarko/agent-cli/src/core/commands/start.ts
multimodal/tarko/agent-server/src/utils/webui/config.ts

Fixed `webui` configuration injection issue where `webui` configs are not deeply merged

fix(tarko-agent-cli): merged webui config in script injection (close: #1626)

---

multimodal/gui-agent/operator-aio/src/AIOHybridOperator.ts

fix(aio-hybrid-operator): transform arrowDirecton key to direction key

---

multimodal/tarko/agent-server-next/src/routes/sessions.ts

rmeove unexisted routes
remove unexisted routes

fix(tarko-server-next): remove unexisted routes

---

multimodal/omni-tars/omni-agent/tarko.config.ts

add default runtime settings in local environment for omni agent

feat(omni-agent): add default runtimeSettings

---

multimodal/omni-tars/gui-agent/src/GuiAgentPlugin.ts

feat(o-gui-agent): insert preset messages before real query from user

---

multimodal/tarko/agent-ui/src/standalone/home/WelcomeCards.tsx

1. Resize game welcome card:
2. Update runntimeSettings when click game welcome card

feat(omni-agent): optimize agent game mode UI

---

multimodal/omni-tars/gui-agent/src/GuiAgentPlugin.ts

feat(o-gui-agent): set waiting time as 5s when initailize screenshot

---

multimodal/tarko/agent-ui/src/standalone/chat/MessageInput/AgentOptionsSelector.tsx
multimodal/tarko/agent-ui/src/standalone/chat/MessageInput/ChatBottomSettings.tsx
multimodal/tarko/agent-ui/src/standalone/chat/MessageInput/agentIconUtils.tsx

Replaced the plus icon with a lightning bolt (`FiZap`) icon for the Agent Mode selector button to better represent AI agent functionality and provide a more intuitive visual cue.

feat(tarko-agent-ui): replace plus icon with lightning bolt for agent mode selector

---

multimodal/tarko/agent-ui/src/standalone/workspace/renderers/TerminalRenderer.tsx

Enhanced `TerminalRenderer` to detect URLs in JSON output and make them clickable links. URLs in JSON strings are automatically converted to clickable elements that open in new tabs, improving user experience when viewing API responses or tool outputs containing URLs.

feat(tarko-agent-ui): add clickable url links in terminal renderer json output

---

multimodal/gui-agent/operator-browser/package.json
multimodal/pnpm-lock.yaml

feat(gui-agent): add refactored dependancy into browser operator

---

multimodal/omni-tars/code-agent/src/CodeAgentPlugin.ts
multimodal/omni-tars/core/src/AgentComposer.ts
multimodal/omni-tars/core/src/ComposableAgent.ts
multimodal/omni-tars/omni-agent/src/index.ts
multimodal/omni-tars/omni-agent/tarko.config.ts
multimodal/tarko/agent-server-next/examples/bootstrap.ts
multimodal/tarko/agent-ui/src/config/web-ui-config.ts
multimodal/tarko/agent-ui/src/standalone/navbar/Navbar.tsx
multimodal/tarko/agent/src/agent/agent.ts
multimodal/tarko/agent/src/agent/tool-manager.ts

fix issues for omni,
1. **Agent Tool Processing Compatibility Fix**: Fixed critical compatibility issues in the tarko agent system when custom `onAfterToolCall` hooks don't return results, ensuring more robust tool execution
2. **Debug Environment Enhancement**: Updated debug environment configuration for AIO sandbox to improve development workflow
3. **Navigation UI Enhancement**: Added support for navitems link replacement functionality in the tarko agent UI for better user navigation experience
4. **Model Support Expansion**: Added T6.5 model ID support and updated hybrid UI configuration

feat: TARS platform enhancements and compatibility fixes

---

multimodal/gui-agent/agent-sdk/package.json
multimodal/gui-agent/agent-sdk/src/GUIAgent.ts

fix(gui-agent): return original result onAfterToolCall hook

---

packages/agent-infra/mcp-hub/README.md
packages/agent-infra/mcp-hub/examples/config.json
packages/agent-infra/mcp-hub/src/MCPHub.ts
packages/agent-infra/mcp-hub/src/mcp/server.ts
packages/agent-infra/mcp-hub/src/server.ts
packages/agent-infra/mcp-hub/tests/mcp-filter-integration.test.ts
packages/agent-infra/mcp-hub/tests/mcp-server-filter.test.ts

- **feat(mcp-hub): add @agent-infra/mcp-hub**
- **feat(mcp-hub): add @agent-infra/mcp-hub**
- **feat(mcp-hub): add @agent-infra/mcp-hub**
- **chore: v**
- **chore: update**
- **chore: reset**
- **chore: unused**
- **chore: unused**
- **chore: update pnpm**
- **feat: mcp-server filter**

feat: mcp hub search

---

multimodal/agent-tars/core/package.json
multimodal/agent-tars/core/src/environments/local/browser/browser-gui-agent.ts
multimodal/tarko/shared-utils/src/gui-agent.ts

refactor(agent-tars): integrate refactored browser operator and action parser
